### ISSUE TITLE
Add additional check for initialization

### ISSUE THREAD

**Issue by dbason** [banzaicloud/bank-vaults#1029]
**Is your feature request related to a problem? Please describe.**
Our use case is as follows:
We are using transit unseal, and storing the root token in a central parent vault instance (outside of kubernetes).  We protect the transit path with a period token, however we want to limit access to the root token for the operator managed cluster so we enforce a TTL on the token that provides access to the central KV store.  If the TTL has expired and a pod dies, the transit unseal works fine however the pod will not come up because the bank-vaults container can no longer access the kv store.

**Describe the solution you'd like**
If there is an error accessing the kv store on initialization bank-vaults should check if vault is already unsealed (due to transit).  If it is it should log a warning an continue on.

**Describe alternatives you've considered**
Haven't really considered others; I think this best fits our use case of having the team that administers the central vault separate to the team that administers kubernetes.

**Comment by dbason** [comment]
I think something like https://github.com/dbason/bank-vaults/commit/808dcb21dd17d5e8231d1e330b86d4a2963cba77.  I can tidy this up and open a PR if you like

**Comment by bonifaido** [comment]
Hi @dbason, thanks for the submission. We're glad to receive a PR for this.
