### ISSUE TITLE
Distribute CA cert without key

### ISSUE THREAD

**Issue by sanderma** [banzaicloud/bank-vaults#1031]
The CA cert that is distributed contains the key, which is not needed.

[PR 520](https://github.com/banzaicloud/bank-vaults/pull/520) removed the `server.crt` and `server.key`, but the `ca.key` is still distributed.

I do not see this being used, so is it perhaps a good idea to remove the key and only keep the ca.crt?

In file `vault_controller.go`:
```go
// We need the CA certificate only
	delete(currentSecret.StringData, "server.crt")
	delete(currentSecret.StringData, "server.key")
	delete(currentSecret.StringData, "ca.key") // add this
	delete(currentSecret.Data, "server.crt")
	delete(currentSecret.Data, "server.key")
	delete(currentSecret.Data, "ca.key") // and this
```

I'm happy to create a PR, but first wanted to check up in case I'm missing a very good reason for the key to be present.

**Comment by bonifaido** [comment]
Yes, `"ca.key"` it is absolutely not needed, happy to review the PR!

**Comment by sanderma** [comment]
Okay, I'll send one tonight (kids 😉)
