### ISSUE TITLE
example of configMapMutation?

### ISSUE THREAD

**Issue by tony-kerz** [banzaicloud/bank-vaults#1043]
apologies in advance if i missed it, and/or it's obvious,
but can someone provide an example of how config-map-mutation works?

**Comment by bonifaido** [comment]
Hi @tony-kerz,

it is very similar to Kubernetes Secret mutation, it happens only in creation/modification time of the given configmap, I suggest to check the examples from the acceptance test: https://github.com/banzaicloud/bank-vaults/blob/master/hack/acceptance-test.sh#L144

The given references are pulled out from Vault and they are replaced in the ConfigMap with the actual data from Vault.

I hope this helps.
