### ISSUE TITLE
Support Server Side Encryption (SSE) for AWS S3 buckets

### ISSUE THREAD

**Issue by ptzianos** [banzaicloud/bank-vaults#1053]
**Is your feature request related to a problem? Please describe.**
We have a blanket policy of enforcing SSE for every bucket that we use in our infrastructure. This is a problem when working with the Vault Operator, because the policy will prevent anything to be written in the bucket unless it specifically requests that the objects are encrypted at rest. 

**Describe the solution you'd like**
Add the ability to the Operator to request an object to be encrypted on the server side. There are two algorithms that can be used: `AES256` or `aws:kms`.
- In the case of `AES256` the user doesn't need to do anything, the S3 API will automatically use a key to encrypt the data at rest, transparently to the application. 
- In the case of `aws:kms`, the user must provide the ID of a Customer Managed Key (CMK) that will be used to encrypt the data at rest by the S3 API.
A potential way of implementing this would be to add a new flag called `s3SSEAlgo` which is of type string and has either the value `AES256` or `aws:kms`. If the algorithm is `AWS256`, then no `aws-kms-key-id` is needed and if one is provided, that will result in an error. If the algorithm is `aws:kms`, then the user must provide an `aws-kms-key-id`. According to the AWS docs, the region of CMK must be the same as the region of the bucket. If they are not, the Operator must throw an error.
This solution is backwards compatible, and should not need a lot of extra code to be implemented.

**Describe alternatives you've considered**
Can't think of any other alternative. Open to new ideas though.

**Additional context**
That's it.

**Comment by bonifaido** [comment]
Hi @ptzianos!

I absolutely like the idea and also that you thought about backward compatibility. Do you plan to implement this feature as well?

**Comment by ptzianos** [comment]
@bonifaido yeap, already on it. should have the PR ready in a few hours
