### ISSUE TITLE
Multi-architecture images

### ISSUE THREAD

**Issue by patoarvizu** [banzaicloud/bank-vaults#1076]
**Is your feature request related to a problem? Please describe.**
Currently, `bank-vaults` image published on Docker Hub is only built for the `linux/amd64` architecture.

**Describe the solution you'd like**
Cross-build and distribute the image for other architectures, specially ARM (`linux/arm64`, `linux/arm/v7`, `linux/arm/v6`).

**Describe alternatives you've considered**
There are no alternatives since the underlying architecture is a hard constraint.

**Additional context**
This would make it possible to run it on Raspberry Pi clusters.

**Comment by bonifaido** [comment]
FYI: working on this right now, one step towards this is: https://github.com/banzaicloud/bank-vaults/pull/1089

**Comment by patoarvizu** [comment]
I see you're already pushing images to the GitHub registry! I'm looking forward to seeing ARM images there soon. Thanks!

**Comment by bonifaido** [comment]
I think I will drop `linux/arm/v6` support, it is Raspberry PI 1, which is quite old, but increases the build time heavily. Most of the 32 bit ARMs are `linux/arm/v7` and `v8`.

**Comment by patoarvizu** [comment]
Yeah, `linux/arm/v7` should be good for Raspberry Pi 4. Thanks!
