### ISSUE TITLE
[vault-env] Allow using specific secret versions

### ISSUE THREAD

**Issue by david92rl** [banzaicloud/bank-vaults#1096]
**Is your feature request related to a problem? Please describe.**
We use vault-env in Kubernetes for services running lots of Pods.
When updating a secret, if a Pod gets restarted, it picks-up the new value causing multiple versions of the secret to be used at the same time with no control over it.

**Describe the solution you'd like**
Adding support to use specifc secret version will help people to roll-out those changes with more control. E.g. rolling updates.
It could be something like `vault:secret/data/test#MY_VAR?v=3`

**Describe alternatives you've considered**
The current workaround is to add a new key with the new value, so we have both `MY_VAR` and `MY_VAR_V3`

**Comment by bonifaido** [comment]
Thankfully this is already supported, though not well documented. Please try:

```
vault:secret/data/test#MY_VAR#3
```

**Comment by bonifaido** [comment]
Ah, it is there, I was mistaken:

https://banzaicloud.com/docs/bank-vaults/mutating-webhook/

> You can specify the version of a Vault secret as well if you define the version as shown in the following example...

**Comment by david92rl** [comment]
Awesome! Thank you so much
