### ISSUE TITLE
[charts] drop support for Helm 2 for all charts

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#1097]
Support for **Helm 2 will be discontinued at the end of 2020 September** by all Bank-Vaults charts.

This means that **they might work with Helm 2** as well, but we don't test and offer support installing/upgrading them with that Helm 2 version line.

See https://helm.sh/blog/2019-10-22-helm-2150-released/ for more details about the topic.

> 12 months after Helm 3's public release, support for Helm 2 will formally end.
> _Tue, Oct 22, 2019_

fixes: #1059

**Comment by patoarvizu** [comment]
Is this happening? 🙂

If you're looking for help for this, I'd be happy to contribute. We want to use the charts but the `v1`/`v2` situation breaks `helm lint` which is required in our CI/CD setup.

**Comment by bonifaido** [comment]
Hi @patoarvizu I got distracted a bit by other projects, so if you have a working solution I would be happy to review that PR! 🙂
