### ISSUE TITLE
[vault-secrets-webhook] Add all keys in vault path as env variables

### ISSUE THREAD

**Issue by rocpatel** [banzaicloud/bank-vaults#1098]
**Is your feature request related to a problem? Please describe.**

We have laid out our vault paths by applications.  So, each application gets its own path, thus the keys in the path are all the env variables we want to send to the app.  Right now, we have to add those same keys as env variables in our k8s manifests.  This can be somewhat error-prone, and extra work for the manifest developers.

**Describe the solution you'd like**

It would be nice to have a way of just specifying a vault path, and have vault-env add all the keys in that path as env variables to the process.

**Describe alternatives you've considered**

Couldn't really find any alternatives.  The only one is to explicitly have all the keys as env variables.

**Additional context**

I have already started working on a solution that adds an additional annotation with a comma-delimited list of vault paths to read from.  When this annotation is present, vault-env would read those paths and add all the keys as env variables.

**Comment by bonifaido** [comment]
@rocpatel I think we can close this now, right?

**Comment by bonifaido** [comment]
fixed in #1100
