### ISSUE TITLE
Open up Vault cluster address in Operator

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#110]

**Comment by gowthamsubbu** [comment]
@bonifaido Thanks a lot for the quick fix and response. I have been evaluating Bank-vault in the past few days to implement in our prod with etcd for Vault secrets management.

Please let me know, once the latest stable images are pushed and tested. We will be presenting the Bank-vault demo and evaluation report to our Architects for a Go/No-Go decision.

Thanks

**Comment by matyix** [comment]
@gowthamsubbu Good luck with the demo/presentation - let us know how it went.

**Comment by bonifaido** [comment]
@gowthamsubbu great to hear that! All images have been built now with the fixes.
