### ISSUE TITLE
[webhook] JWT token forces mutation of secret of type dockerconfigjson

### ISSUE THREAD

**Issue by tommy-heyde-olsen** [banzaicloud/bank-vaults#1122]
**Describe the bug**:
With the changes in this PR: https://github.com/banzaicloud/bank-vaults/pull/1026 combined with the behaviour of this if-statement: https://github.com/banzaicloud/bank-vaults/blob/7c55c84d06533d4273486f216d9a01adf67953cf/cmd/vault-secrets-webhook/secret.go#L54, we're always forced into the usage of JWT service discovery, and since we haven't configured this in Vault + Vault Secrets Webhook, we get the following error when applying a secret of type `dockerconfigjson`:

```
Error from server (InternalError): error when creating "dockerconfig.yaml": Internal error occurred: failed calling webhook "secrets.vault-secrets-webhook.admission.banzaicloud.com": Post https://vault-secrets-webhook.vault-secrets-webhook.svc:443/secrets?timeout=10s: context deadline exceeded
```

```
time="2020-09-25T11:41:24Z" level=error msg="failed to request new Vault token" app=vault-secrets-webhook err="Error making API request.\n\nURL: PUT https://vault.redacted/v1/auth/tooling-west-1/login\nCode: 400. Errors:\n\n* invalid role name \"default\""
```

This is happening on Azure Kubernetes Service (AKS) where the file `/var/run/secrets/kubernetes.io/serviceaccount/token` is present, because service account issuer discovery is enabled.

**Expected behaviour**:
I expected the secret of type dockerconfigjson to be able to be created when no mutation is expected to happen for the secret. So ideally a feature toggle for service account issuer discovery would be helpful.

**Steps to reproduce the bug**:
1) Use v. 1.3.3+ with a Kubernetes cluster with service account issuer discovery enabled.
2) Create a secret of type dockerconfigjson

**Additional context**:

**Environment details**:
- Kubernetes version: 1.17.9
- Cloud-provider/provisioner: AKS
- bank-vaults version: 1.3.3+
- Install method: helm3

/kind bug

**Comment by bonifaido** [comment]
Hi @tommy-heyde-olsen,

good catch, I just pushed https://github.com/banzaicloud/bank-vaults/pull/1123 to prevent this issue from happening again. BTW I don't think #1026 has anything to do with this, that change is backward compatible in the Vault client code [here](https://github.com/banzaicloud/bank-vaults/pull/1026/files#diff-66925bd79e13b4b8ee8eb7f75abf8d7d).

**Comment by tommy-heyde-olsen** [comment]
Hi @bonifaido,

Thank you for the swift reply and fix as well. 💪

**Comment by bonifaido** [comment]
Welcome @tommy-heyde-olsen, please find the latest fix in the images built from the master branch (this is called `latest` if you use the ghcr.io registry) branch, I will push out a release probably today.
