### ISSUE TITLE
Allow setting a custom path for fluent.conf

### ISSUE THREAD

**Issue by idgenchev** [banzaicloud/bank-vaults#1135]
**Is your feature request related to a problem? Please describe.**
We are using a custom fluentd image that expects fluent.conf to be under /etc/fluent/ and we need a way to customise it.

**Describe the solution you'd like**
Allow setting the path in the spec, like the custom fluentd image.

**Describe alternatives you've considered**
Can't think of suitable alternatives

**Comment by idgenchev** [comment]
Done in PR #1134 :)

**Comment by bonifaido** [comment]
Thanks for this @idgenchev !
