### ISSUE TITLE
[vault-secrets-webhook] option to run as daemon-set?

### ISSUE THREAD

**Issue by tony-kerz** [banzaicloud/bank-vaults#1141]
**Is your feature request related to a problem? Please describe.**
i'm currently experiencing a situation where i'm trying to drain a set of nodes (and migrate the work to a different set of nodes), but i'm seeing some issues around the web-hook not kicking in and secrets not being provided as normal.

however, if i delete the troubled pods, they start successfully, so i'm assuming that there is a timing issue around the web-hook not being present at the time of start up for some of the migrated pods.

this being the case, deploying the web-hook as a daemon-set would be one way of dealing with that scenario.

**Describe the solution you'd like**
allow an option in the helm chart to deploy the web-hook as a daemon-set

**Describe alternatives you've considered**
one alternative would be to script around it by specifically moving the web-hook first,
and then kicking off the more global drain command.

**Additional context**

**Comment by bonifaido** [comment]
Hi @tony-kerz, running a webhook as a DaemonSet could be a pretty heavy load I think, But TBH I have no contraindication about it if this won't be the default deployment strategy in the chart and if we can template it smartly in the chart, so only a small fraction of YAML has to be "duplicated".

Won't be just the scheduling of the webhook to the API server nodes a good idea maybe?

**Comment by bonifaido** [comment]
Due to lack of response closing this for now.

**Comment by tony-kerz** [comment]
thanks @bonifaido, revisiting this after a while, still struggling with https://github.com/banzaicloud/bank-vaults/issues/1491

considering various strategies including:

- https://github.com/banzaicloud/bank-vaults/issues/1510
- pod-disruption-budgets plus https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown
- running webhook on on-demand node-pool

i read your comment a while back, but at the time wasn't sure what you meant exactly, got distracted and never followed up, but can i ask now what you meant by this:

> Won't be just the scheduling of the webhook to the API server nodes a good idea maybe?

i'm not familiar with that strategy, can you elaborate? is that something i can do with the helm chart?
