### ISSUE TITLE
[webhook] hostNetwork

### ISSUE THREAD

**Issue by cpoule23** [banzaicloud/bank-vaults#1147]
Hello,

Is it possible to add  a "hostNetwok: true" inside spec (line 35)
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/templates/webhook-deployment.yaml

I need this feature for my EKS cluster as I need node ip address to go outside my cluster (architectural constrainght)

Thanks in advance,
Cyril

**Comment by bonifaido** [comment]
Hi @cpoule23, yes please open up a PR with a configurable value for with default `hostNetwork: false`. We are happy to pull that in.

**Comment by bonifaido** [comment]
Fixed by #1154
