### ISSUE TITLE
[vault-secrets-webhook] Configurable default behavior of vault-role

### ISSUE THREAD

**Issue by gw0** [banzaicloud/bank-vaults#1160]
Vault-secrets-webhook uses the env var `VAULT_ROLE` to provide the default role used for the Kubernetes auth method. If it is empty, it uses the ServiceAccount of the Pod. This is excellent for environments with tight security, but requires that ServiceAccounts and roles in Vault are always kept in sync. But in a bit more relaxed environments, one might want to use the Namespace of the Pod as a default role (which is currently not supported). It is true, that this can be accomplished by assigning a default ServiceAccount to all Pods, but it is troublesome to always set this in all Helm charts.

**Suggestion**
The env var `VAULT_ROLE` could accept two special values to specify what type of automatic default roles should be used. For example:

- `VAULT_ROLE="auto-serviceaccount"` (also `VAULT_ROLE=""`): uses the ServiceAccount of the Pod as the default role
- `VAULT_ROLE="auto-namespace"`: uses the Namespace of the Pod as the default role (maybe prefixed with `namespace-${namespace}`)

The logic needs to be added here:
- https://github.com/banzaicloud/bank-vaults/blob/7c55c84d06533d4273486f216d9a01adf67953cf/cmd/vault-secrets-webhook/main.go#L135-L144

**Comment by bonifaido** [comment]
@gw0 good idea, I agree with you about this is not always the best default behavior. Are you about to submit this change?

**Comment by gw0** [comment]
I could try, but my Go skills are lacking. Are the names `"auto-serviceaccount"` and `"auto-namespace"` good?

**Comment by bonifaido** [comment]
Yes, absolutely, Thanks! (I'm ready to help you through the process).

**Comment by Tolsto** [comment]
https://github.com/banzaicloud/bank-vaults/issues/954 is related to this.
Our serviceaccount names sometimes collide across namespaces. Prefixing the role name with the namespace would greatly help.
