### ISSUE TITLE
Install via helm 3 to the custom namespace

### ISSUE THREAD

**Issue by dzirg44** [banzaicloud/bank-vaults#1169]
Hi!
In helm 3 we have an opportunity to create resources in  different namespaces. Something like this
```
helm upgrade --install vault-operator banzaicloud-stable/vault-operator --namespace vault-operator
```
but i receive 
```json
{
  "level": "info",
  "ts": 1604061734.9495385,
  "logger": "controller_vault",
  "msg": "Reconciling Vault",
  "Request.Namespace": "bank-vault",
  "Request.Name": "vault"
}
{
  "level": "error",
  "ts": 1604061734.9539728,
  "logger": "controller",
  "msg": "Reconciler error",
  "controller": "vault-controller",
  "name": "vault",
  "namespace": "bank-vault",
  "error": "failed to get certificate from secret: failed to parse certificate PEM",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:90"
}
```
(feel free to use json formatters)

**Expected behaviour**:
create and run Vault 

**Steps to reproduce the bug**:
```
kubectl create ns bank-vault
helm upgrade --install vault-operator banzaicloud-stable/vault-operator --namespace bank-vault
git clone https://github.com/dzirg44/banzai
kubectl apply -f banzai
```

**Additional context**:
it seems that Vault operator cannot recognize  default secret volume mounts, but I haven't found it in the helm chart.

**Environment details**:
- Kubernetes version - v1.17 
- Cloud-provider/provisioner -  EKS
- Install method - helm (1.7.0):

**Comment by bonifaido** [comment]
Hi @dzirg44,

I tried to reproduce the error on a `kind` cluster according to your instructions:
```bash
kubectl create ns bank-vault
helm upgrade --install vault-operator banzaicloud-stable/vault-operator --namespace bank-vault
git clone https://github.com/dzirg44/banzai
kubectl apply -f banzai
```
But I have received this:
```
kubectl get pods -n bank-vault                                                                                      (docker-desktop/default)
NAME                                READY   STATUS    RESTARTS   AGE
vault-0                             3/3     Running   0          2m52s
vault-configurer-6567489456-fk962   1/1     Running   0          2m43s
vault-operator-66fdd6f497-rk4hh     1/1     Running   0          3m18s
```

Without any errors in the operator logs. Are you sure all changes and configuration settings are committed your repository?

I suspect there is something extra behind this: 
> it seems that Vault operator cannot recognize default secret volume mounts, but I haven't found it in the helm chart.

What does this mean exactly?

**Comment by dzirg44** [comment]
@bonifaido let me check in 1 -2 days. Maybe it happened because of old CRDs.

**Comment by bonifaido** [comment]
Any update on this @dzirg44 ?

**Comment by dzirg44** [comment]
@bonifaido working on it now.

**Comment by dzirg44** [comment]
@bonifaido  it looks like the old configuration  was the cause. 
I started with deleting chart , but after applying nothing changed. After that I deleted all config maps , crds, and secrets in all namespaces which were related to bank-vaults. Set everything up again, and now it's working.
I hope it will help somebody. Of course I will try to reproduce this situation, but for now it can be marked as solved.

**Comment by bonifaido** [comment]
Thanks Oleg! Closing this then!

**Comment by dzirg44** [comment]
@bonifaido  a little update here. After deleting and applying again , pod vault-0  doesn't work. 

```
time="2020-11-12T12:02:41Z" level=fatal msg="error initializing vault: error before init: value for key 'vault-root' already exists"
```
in the `bank-vaults` container.

i don't know how to solve it, because i guess this key in secrets creates operator.

**Comment by dzirg44** [comment]
deleting this

```bash
kubectl delete secret/vault-unseal-keys -n bank-vault
```

brings pod to life (because this secret isn't valid for the new configuration)

**Comment by bonifaido** [comment]
Unseal keys and the data live together, if you delete the data, you have to delete the keys as well, this is a manual process.
