### ISSUE TITLE
tls_disable: true break things

### ISSUE THREAD

**Issue by evgkrsk** [banzaicloud/bank-vaults#120]
**Describe the bug**
bank-vaults fails to start pod if TLS encryption not used (i.e. HTTP instead of HTTPS)

**To Reproduce**
1. helm install banzaicloud-stable/vault --set vault.config.listener.tcp.tls_disable="true"
2. Watch that 2 (of total 4) containers fails liveness/readyness probes

**Expected behavior**
All containers handles liveness/readyness probes.

**Additional context**
It is pretty easy to fix helm chart to use HTTP scheme for probes when vault.config.listener.tcp.tls_disable is true, but next issue arises: vault-unsealer and vault-configurer always try to connect to vault via HTTPS (and stops at HTTP answer). Seems like scheme is hardcoded somewhere. Can you point out place in code where look for ?

P.S.: additionally, seems like HTTPS scheme hardcoded for probes in operator code, too.

P.P.S.: enabling ingress for helm chart is useless without tls_disable:true

**Comment by bonifaido** [comment]
Hi @evgkrsk, HTTPS is our opinionated point of view about using Vault, but it is not pointed out anywhere or not reported when someone disables it, I will do that.

I think we need to solve the issue the other way around, why is *P.P.S.: enabling ingress for helm chart is useless without tls_disable:true* for you? For example we are using Traefik as an ingress controller, and having no issues with TLS backends.

**Comment by evgkrsk** [comment]
Honestly, I can't figure out, how to use non-selfsigned (default) TLS certificate. I have tried to mount LetsEncrypt tls secret via customSecrets and tls_cert_file/tls_key_file, but vault cant handle it somehow.

With default k8s ingress controller, turning on ingress in chart makes non-working configuration where nginx cant recognize HTTPS answers from TLS backend. This configuration will successfully work with tls_disable:true.

**Comment by bonifaido** [comment]
If you are using nginx-ingress you can set the protocol of the backends as described here: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#backend-protocol could you please try that? I still strongly suggest to not to drop TLS.

**Comment by evgkrsk** [comment]
Indeed, I used "secure-backends: true" for my version of ingress, but still cant figure out how to use custom TLS certificate instead of self-signed one (inside vault container, not for ingress).

**Comment by bonifaido** [comment]
Could you please give me a pointer which nginx-ingress are you using, which version, repository, etc?

**Comment by evgkrsk** [comment]
Standard k8s nginx-based ingress controller (https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.13.0).

**Comment by bonifaido** [comment]
Ok, could you please try adding a server-snippet to the Ingress definition for Vault?

```yaml
nginx.ingress.kubernetes.io/server-snippet: |
"proxy_ssl_verify off;"
```

**Comment by evgkrsk** [comment]
Oh, my fault. Vault answers fine via ingress (seems like nginx ignores self-signed cert), but fails to work inside k8s cluster, like that:
```
# kubectl -n logging exec -ti es-logging-0 -- curl -v -s https://vault-ha-va
ult.vault:8200/v1/sys/health
* About to connect() to vault-ha-vault.vault port 8200 (#0)
*   Trying 10.1.53.78...
* Connected to vault-ha-vault.vault (10.1.53.78) port 8200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
*       subject: CN=vault-ha-vault
*       start date: Aug 09 09:29:23 2018 GMT
*       expire date: Aug 09 09:29:23 2019 GMT
*       common name: vault-ha-vault
*       issuer: CN=vault-ca
* NSS error -8179 (SEC_ERROR_UNKNOWN_ISSUER)
* Peer's Certificate issuer is not recognized.
* Closing connection 0
command terminated with exit code 60
```

**Comment by bonifaido** [comment]
Yes, however, the ca-cert is deployed to the namespace into a secret where Vault is running, you can use that to validate or pass -k to curl.

**Comment by evgkrsk** [comment]
Sure, but it is not trivial to add HTTPS support with custom certificate/key/ca in all applications that uses vault (they lives in different namespace). Currently HTTP is used.

**Comment by bonifaido** [comment]
It is not trivial, however, all you have to do is to pass in one environment variable:

https://www.vaultproject.io/docs/commands/index.html#vault_skip_verify

or this one:

https://www.vaultproject.io/docs/commands/index.html#vault_cacert
+ Mount the certificate into the Pod as a volume.

**Comment by bonifaido** [comment]
This might be an opinionated view, but the whole point is to store secrets in a secure way and move secrets over the transport layer which is encrypted. So I don't think to add HTTP support here is the right solution. HTTP should only be used for development purposes in the case of Vault. I suggest rather making your custom client configurable to turn on TLS cert verification, which shouldn't be a big effort IMHO.

**Comment by hatemosphere** [comment]
@bonifaido but what if we use e.g service mesh and it provides us unified TLS across all pods in Kubernetes cluster? IMO we should have an option to make bank-vaults work with tls_disabled since Vault has support for it and again, you can implement network encryption using external tools

**Comment by bonifaido** [comment]
I will take a look at this in the following days, and will come back with a solution how to disable TLS in the operator easily. If I understand correctly that is what you want, am I right? @hatemosphere @evgkrsk

**Comment by evgkrsk** [comment]
Yes, you are right.

**Comment by bonifaido** [comment]
Hi @evgkrsk and @hatemosphere! We have implemented the TLS configuration disablement option as described here: https://github.com/banzaicloud/bank-vaults/pull/122

This will be available in 0.2.13 release, which is already under build by Docker HUB, let's give a few minutes to let them arrive there.

Should you have any questions about it, write it up here or in another issue.

**Comment by evgkrsk** [comment]
Seems like corresponding changes drops only in operator's code, not in image itself (we use helm chart to install docker image, so operator is not used).

**Comment by bonifaido** [comment]
I don't really understand the issue, so you are using the helm chart? If yes, I think it's rather easy to change the scheme to http I instead of https in the health checks. If you have done that could you please open up a pull request to make it configurable and leave https as the default?

**Comment by bonifaido** [comment]
I'm asking for the PR beceasue it it would give more possibility to understand and debug the issue. The solution doesn't hav

**Comment by evgkrsk** [comment]
Yes, I have patched templates/deployment.yaml from helm chart like that:

```
        livenessProbe:
          httpGet:
            {{ if .Values.vault.config.listener.tcp.tls_disable }}
            scheme: HTTP
            {{ else }}
            scheme: HTTPS
            {{ end }}
            path: /v1/sys/init
            port: vault
        # This probe makes sure that only the active Vault instance gets traffic
        # See: https://www.vaultproject.io/api/system/health.html
        readinessProbe:
          httpGet:
            {{ if .Values.vault.config.listener.tcp.tls_disable }}
            scheme: HTTP
            {{ else }}                                                                                                        
            scheme: HTTPS
            {{ end }}
            path: /v1/sys/health
            port: vault
```

Now probes dont failed but satellite containers (unsealer/configured) still use HTTPS and write errors in log:

```
# kubectl -n vault logs -f vault-ha-vault-855f76756b-55g4l -c vault-unsealertime="2018-08-13T11:44:46Z" level=info msg="initializing vault..."
time="2018-08-13T11:44:50Z" level=fatal msg="error initializing vault: error testing if vault is initialized: Get https://127.0.0.1:8200/v1/sys/init: http: server gave HTTP response to HTTPS client"

# kubectl -n vault logs -f vault-ha-vault-855f76756b-55g4l -c vault-configurer
time="2018-08-13T11:43:47Z" level=info msg="New config file change \"Initial\": CREATE"
time="2018-08-13T11:43:47Z" level=info msg="checking if vault is sealed..."
time="2018-08-13T11:43:52Z" level=error msg="error checking if vault is sealed: error checking status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client, waiting 30s before trying again..."
time="2018-08-13T11:44:22Z" level=info msg="checking if vault is sealed..."
time="2018-08-13T11:44:26Z" level=error msg="error checking if vault is sealed: error checking status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client, waiting 30s before trying again..."
time="2018-08-13T11:44:56Z" level=info msg="checking if vault is sealed..."
time="2018-08-13T11:44:59Z" level=error msg="error checking if vault is sealed: error checking status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client, waiting 30s before trying again..."
time="2018-08-13T11:45:29Z" level=info msg="checking if vault is sealed..."
time="2018-08-13T11:45:33Z" level=error msg="error checking if vault is sealed: error checking status: Get https://127.0.0.1:8200/v1/sys/seal-status: http: server gave HTTP response to HTTPS client, waiting 30s before trying again..."
```

According to file diff in #122 my guess is that http/https switching code dont included in bank-vault's Docker hub image (only in operator binary).

**Comment by bonifaido** [comment]
Yes, where you can see VAULT_CACERT env vars you also have to include the VAULT_ADDR env car, where the scheme is http in your case, by default it is https.

**Comment by evgkrsk** [comment]
Thanks, it helps, but now unsealer write following error log:

```
time="2018-08-13T13:29:40Z" level=info msg="checking if vault is sealed..."
time="2018-08-13T13:29:40Z" level=info msg="vault sealed: true"
time="2018-08-13T13:29:44Z" level=error msg="error unsealing vault: fail to send unseal request to vault: Error making API request.\n\nURL: PUT http://127.0.0.1:8200/v1/sys/unseal\nCode: 500. Errors:\n\n* failed to create cipher: crypto/aes: invalid key size 33"
```

**Comment by bonifaido** [comment]
Could you please try with the TLS related env vars removed?

**Comment by evgkrsk** [comment]
@bonifaido , seems like unseal problem was related to already initialized etcd storage. Dropping vault data in etcd fixes it.

Please review/merge my PR for helm chart (https://github.com/banzaicloud/banzai-charts/pull/303)

**Comment by matyix** [comment]
@evgkrsk merged, thx.
