### ISSUE TITLE
`serviceMonitorEnabled` makes Prometheus scrapes Vault replicas twice & standby nodes can't be scraped

### ISSUE THREAD

**Issue by sdurrheimer** [banzaicloud/bank-vaults#1209]
**Describe the solution you'd like**

Currently, when using `serviceMonitorEnabled: true`, Vault is scraped twice by Prometheus because both `vault` and `vault-<number>` services are matching the ServiceMonitor matchLabels selector.
This will create duplicated metrics for the same vault instance.

When using HA, for example with 2 replicas, the problem is even worth. You will get 4 targets in Prometheus and 2 of them will be in error because standby nodes can't be scraped.

**Describe alternatives you've considered**

Currently, besides patching manually the ServiceMonitor created by the operator, you can't change the matchLabels selector to avoid duplicated metrics for the same replica.

**Additional context**

Here a screenshot showing the Prometheus targets:
![image](https://user-images.githubusercontent.com/1931038/101627501-baa90100-3a1e-11eb-9f38-2102bea50652.png)

**Comment by bonifaido** [comment]
Hm, I guess the solution would be here to scrape only the per-instance vault services, or what do you think @sdurrheimer ?

**Comment by sdurrheimer** [comment]
> Hm, I guess the solution would be here to scrape only the per-instance vault services, or what do you think @sdurrheimer ?

I think so yes.

But ideally, we would also want to not scrape standby nodes if it is really not possible to make it work, or Prometheus will always complain that targets are down (which might trigger unnecessary alerts).

**Comment by bonifaido** [comment]
I'm about to fix this, I managed to remove the duplicates now, but the standby instances are not emitting any kind of metrics, since the /v1/sys/metrics endpoint is token protected and standby instances can't check tokens:

```json
{"errors":["error performing token check: Vault is in standby mode"]}
```

I think we should scrape the main service only, or live with red standby instances.

**Comment by bonifaido** [comment]
Ah just found this: https://www.vaultproject.io/docs/configuration/listener/tcp#telemetry-parameters

**Comment by bonifaido** [comment]
Just submitted https://github.com/banzaicloud/bank-vaults/pull/1211 to resolve this.

**Comment by sdurrheimer** [comment]
Thank you, I'm gonna check that.

**Comment by sdurrheimer** [comment]
@bonifaido Vault instances are still scraped twice right?

With the latest vault-operator release, deleted the ServiceMonitor to force recreation, single vault instance:
![image](https://user-images.githubusercontent.com/1931038/102647027-606a1780-4165-11eb-84fe-7a4420c6e656.png)

**Comment by bonifaido** [comment]
You need to use the :latest image tags for this (which is built from master) since it is not yet released.

**Comment by moustafab** [comment]
I have a similar situation, but the solution above can't work for me. It isn't secure and I can't have the endpoint exposed to unauthenticated traffic. Is there a chance we could have a separate service and have the configurer or operator update the leader pod with a label that the service selects for?
