### ISSUE TITLE
[vault-secrets-webhook] Vault agent templating with projected service account token

### ISSUE THREAD

**Issue by aelbarkani** [banzaicloud/bank-vaults#1219]
Hi all,

I've been trying to use [Vault Agent Templating](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/vault-agent-templating/) or [Consul templating](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/consul-template/) with JWT authentication through projected service account tokens with no success. It seems there is no way to indicate to webhook to mount a projected service account token. Is that right or is there something I missed ? Any workaround for this ?

**Comment by bonifaido** [comment]
There is no automated way of doing this, but you can set the path of the projected JWT in the vault-agent config, see: https://www.vaultproject.io/docs/agent/autoauth/methods/kubernetes#configuration
