### ISSUE TITLE
Question about bound_service_account_namespaces parameter

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/bank-vaults#1226]
Hi,
Many `Vault` CR examples contain `bound_service_account_namespaces` parameter:
- charts/vault/values.yaml
- operator/deploy/**.yaml

 but I can't find any reference in the bank-vault chart. Has this parameter been deprecated?

**Comment by bonifaido** [comment]
This is an original Vault parameter that is why you can see it in see it around the examples and default settings: https://www.vaultproject.io/api-docs/auth/kubernetes#bound_service_account_namespaces
