### ISSUE TITLE
Chart dependency on etc-operator breaks deployment

### ISSUE THREAD

**Issue by j-zimnowoda** [banzaicloud/bank-vaults#1240]
**Describe the bug**:

I am unable to install that chart:
```
Failed to render chart: exit status 1: Error: found in Chart.yaml, but missing in charts/ directory: etcd-operator
```

In Chart.yaml there is a dependency on etcd-operator chart.
But the etcd-operator chart has been removed from `vault-operator/charts/etcd-operator/`

**Expected behaviour**:
It looks like the dependencies from Chart.yaml should be removed. 
But it depends on intended behaviour to the maintainer.

**Steps to reproduce the bug**:
- 

**Environment details**:
- Kubernetes version: 1.18
- Cloud-provider/provisioner EKS
- bank-vaults version: 1.11.0
- Install method: helm

/kind bug

**Comment by bonifaido** [comment]
what is your helm install command? are you deploying from our chart repo?

**Comment by j-zimnowoda** [comment]
I am using helmfile but under hood helm performs the following command:
```
helm diff upgrade --reset-values --allow-unreleased vault-operator ../charts/vault-operator --disable-validation --namespace vault --values /tmp/values107179787 --detailed-exitcode
```
The `../charts/vault-operator` is the chart from git repo (bank-vaults/charts/vault-operator/) not helm repo.

**Comment by bonifaido** [comment]
You can install etcd-operator with `--set etcd-operator.enabled=true`, as usual.

**Comment by bonifaido** [comment]
Of course, you have to build the chart with `helm`. Installing plain charts can work in some cases, but charts that have dependencies have to be built.
