### ISSUE TITLE
Create SA and RBAC for running vault

### ISSUE THREAD

**Issue by davidkarlsen** [banzaicloud/bank-vaults#1258]
**Is your feature request related to a problem? Please describe.**
The operator only handles the sts. It would be nice if it dealt with:
* creating serviceaccount
* create role&rolebinding
in order to run the sts

**Describe the solution you'd like**
See description

**Describe alternatives you've considered**
As of now some setup is manual, rest is handled with operator

**Additional context**
N/A

**Comment by bonifaido** [comment]
This would require the operator to run in god-mode, so be able to create service accounts, roles and cluster roles, and this is something we always wanted to avoid.
I think setting up service accounts and roles for applications is outside of the scope of this operator.
