### ISSUE TITLE
There is no docker image with tag 1.11.4

### ISSUE THREAD

**Issue by malcolm061990** [banzaicloud/bank-vaults#1279]
**Describe the bug**:
There is no docker image with tag 1.11.4 that is used by helm [chart](https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-operator/Chart.yaml) in your master branch. So I can't deploy your app using helm and your master branch.

**Expected behaviour**:
The image with tag 1.11.4 exists OR the correct version in chart must be 1.11.2.

**Steps to reproduce the bug**:
Just run:
```
docker pull ghcr.io/banzaicloud/vault-operator:1.11.4
```

/kind bug

**Comment by bonifaido** [comment]
Sorry for that, it was bumped by mistake in one of the chart PRs.

https://github.com/banzaicloud/bank-vaults/pull/1280 will fix this.
