### ISSUE TITLE
Revoke root token after init and generate one on the fly via unseal keys during reconfiguration

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#129]
https://www.vaultproject.io/docs/concepts/tokens.html#root-tokens

**Comment by raoofm** [comment]
can be a flag to enable/disable revoke

**Comment by raoofm** [comment]
@matyix sure

**Comment by raoofm** [comment]
https://learn.hashicorp.com/vault/operations/ops-generate-root

**Comment by matyix** [comment]
@raoofm Shall we wait for the PR you might be going to open, or we should go ahead and do this (it's a simple fix)?

**Comment by raoofm** [comment]
@matyix as you have seen I have been collecting details for the open issues. Though I would like to contribute dev but I'm not a go programmer. I could give it a try if guided where to start and if this is not urgent.

**Comment by ptzianos** [comment]
@bonifaido @raoofm @matyix @jamie-34254 if nobody else is working on a PR I can start working on this ASAP. It has become high priority for my team.

**Comment by jamie-34254** [comment]
We're not currently working on this

**Comment by bonifaido** [comment]
Hi @ptzianos, please go ahead, we highly appreciate it!

**Comment by raoofm** [comment]
@ptzianos thanks. we are not working on this, please proceed

**Comment by priyanka-gupta-appd** [comment]
any update regarding this ?
