### ISSUE TITLE
Generated CRDs require `unsealConfig.aws.s3Region` and `unsealConfig.aws.kmRegion` conflicts with functionality

### ISSUE THREAD

**Issue by TimJones** [banzaicloud/bank-vaults#1292]
**Describe the bug**:
On upgrading bank-vaults operator from 1.10 to 1.11 I get the following error:

```
error validating data: [ValidationError(Vault.spec.unsealConfig.aws): missing required field "kmsRegion" in com.banzaicloud.vault.v1alpha1.Vault.spec.unsealConfig.aws, ValidationError(Vault.spec.unsealConfig.aws): missing required field "s3Region" in com.banzaicloud.vault.v1alpha1.Vault.spec.unsealConfig.aws]; if you choose to ignore these errors, turn validation off with --validate=false
```

The AWS region is generated automatically in an AWS EKS cluster with IRSA enabled, as supported #1221. Since it is expected to *not* provide the `s3Region` or `kmsRegion` in order to use the `AWS_REGION`, the CRD need tso not list these fields as required.

**Expected behaviour**:
CRD is updated and Vault spec is maintained.

**Steps to reproduce the bug**:
* Install v1.10 on an EKS cluster with IRSA
* Give the Service Account a role annotation
* Deploy a Vault spec with unseal config but no s3Region or kmsRegion
* Upgrade to v.1.11

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.19
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17): v1.10.0 & v1.11.3
- Install method (e.g. helm or static manifests): helm

/kind bug

**Comment by TimJones** [comment]
I found a workaround, that is I set them as empty strings, it passes the CRD validation but also still falls back to `AWS_REGION` environment variable as it should.

```yaml
unsealConfig:
  s3Prefix: "/"
  s3Region: ""
  s3Bucket: "<snip>"
  kmsRegion: ""
  kmsKeyId: "<snip>"
```

**Comment by bonifaido** [comment]
Totally valid, pushing a PR to fix this, thanks for reporting.
