### ISSUE TITLE
double base64 processing for secrets in k8s

### ISSUE THREAD

**Issue by avoidik** [banzaicloud/bank-vaults#13]
the secrets in k8s being stored in base64 when you're creating them, and bank-vaults is adding additional base64 encoding layer before writing them either, thus on retrieval you have to decode base64 secrets twice (for cli tools) and once (for secrets refs), is that expected behavior?

**Comment by bonifaido** [comment]
If the API encodes it in base

**Comment by bonifaido** [comment]
Fixed by #15
