### ISSUE TITLE
Vault - Operator Error with version 0.2.14

### ISSUE THREAD

**Issue by AniGarikipati** [banzaicloud/bank-vaults#130]
@bonifaido 

When deploying vault-operator version 0.2.14, with the etcd operator and given deployment mechanism, we see the below error. Vault Operator does not bring up Vault pods, but sits in a crash loop state around 10 times before exiting with error in Kubernetes.

Error Stack Trace:
kubectl logs vault-operator-7f4768ff77-j98p8 -n secrets
time="2018-08-22T18:09:45Z" level=info msg="Go Version: go1.10.3"
time="2018-08-22T18:09:45Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-08-22T18:09:45Z" level=info msg="operator-sdk Version: 0.0.5+git"
time="2018-08-22T18:09:45Z" level=info msg="operator namespace: "
time="2018-08-22T18:09:45Z" level=info msg="starting vaults controller"
ERROR: logging before flag.Parse: E0822 18:09:48.818517       1 runtime.go:66] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/hashmap_fast.go:696
/go/src/github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1/types.go:122
/go/src/github.com/banzaicloud/bank-vaults/operator/pkg/stub/handler.go:370
/go/src/github.com/banzaicloud/bank-vaults/operator/pkg/stub/handler.go:103
/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/sync.go:87
/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/sync.go:53
/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/sync.go:37
/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/informer.go:88
/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 57 [running]:
github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1148160, 0x13b87a0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1.(*VaultSpec).GetAnnotations(...)
	/go/src/github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1/types.go:122
github.com/banzaicloud/bank-vaults/operator/pkg/stub.statefulSetForVault(0xc4200a8960, 0xc4202303f0, 0x13baf01, 0xc4202303f0)
	/go/src/github.com/banzaicloud/bank-vaults/operator/pkg/stub/handler.go:370 +0x671
github.com/banzaicloud/bank-vaults/operator/pkg/stub.(*Handler).Handle(0x1bcce70, 0x13d5660, 0xc4200b2018, 0x13be480, 0xc4200a8960, 0xc4200b9c00, 0x0, 0x0)
	/go/src/github.com/banzaicloud/bank-vaults/operator/pkg/stub/handler.go:103 +0x130
github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.(*informer).sync(0xc4203cb500, 0xc4200b3a10, 0xd, 0x10e0b80, 0xc420215960)
	/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/sync.go:87 +0x11a
github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.(*informer).processNextItem(0xc4203cb500, 0xc420296800)
	/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/sync.go:53 +0xd2
github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.(*informer).runWorker(0xc4203cb500)
	/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/sync.go:37 +0x2b
github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.(*informer).(github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.runWorker)-fm()
	/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/informer.go:88 +0x2a
github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420266910)
	/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420266910, 0x3b9aca00, 0x0, 0x1, 0x0)
	/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420266910, 0x3b9aca00, 0x0)
	/go/src/github.com/banzaicloud/bank-vaults/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer.(*informer).Run
	/go/src/github.com/banzaicloud/bank-vaults/vendor/github.com/operator-framework/operator-sdk/pkg/sdk/informer/informer.go:88 +0x209

**Comment by bonifaido** [comment]
@AniGarikipati sorry, this scenario wasn't executed before, I think in your case there are no annotations at all in the Vault CR. I have pushed a fix for this, which will be getting released soon. Please see: #131

**Comment by bonifaido** [comment]
Fix is tagged: https://github.com/banzaicloud/bank-vaults/releases/tag/0.2.15
Takes a couple of minutes for DockerHub to build the images.
