### ISSUE TITLE
extensions/v1beta1 Ingress is deprecated

### ISSUE THREAD

**Issue by Voziv** [banzaicloud/bank-vaults#1304]
**Is your feature request related to a problem? Please describe.**
When doing `kubectl get ingress vault` we're met with the warning: `Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

**Describe the solution you'd like**
Upgrade the ingress definitions to use `networking.k8s.io/v1`

**Describe alternatives you've considered**
I don't think there's any viable alternatives when using the vault-operator.

**Additional context**
Would be nice to remove the default backend from the definition. Will be filed under a different issue if it's not a configuration issue on our end.

**Comment by bonifaido** [comment]
Partially fix is implemented in https://github.com/banzaicloud/bank-vaults/commit/eb95ded0258f6eed76844637231616e9146fa54e

I will update the ingress API as well today.
