### ISSUE TITLE
[Operator] Add cross namespace check to configuration validation

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#132]
It is possible that the Vault configuration in the CR doesn't match what the Operator thinks about the current state of namespaces, so we need to add a validation that makes sure that the namespace is where the CR was submitted to matches the namespace of the configuration.

**Comment by nzoueidi** [comment]
I am going to work on this. It would be very appreciated if there is any hints.

**Comment by bonifaido** [comment]
Hi @nzoueidi, great, I'm happy to help you during the implementation. This issue is related to https://github.com/banzaicloud/bank-vaults/issues/127#issuecomment-415044350 where the Vault configuration mismatched the CRD namespace configuration, this can be validated in [this](https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/controller/vault/vault_controller.go#L100) function, but maybe there are better places (like some kind JSON schema validation), anyhow I suggest to try that function first! ;-)

**Comment by bonifaido** [comment]
Hi @nzoueidi, have you managed to start working on this?

**Comment by bonifaido** [comment]
Any update on this @nzoueidi ?
