### ISSUE TITLE
Fluentd to the helm chart

### ISSUE THREAD

**Issue by viniciusgarcia-hotmart** [banzaicloud/bank-vaults#1322]
I have a question, I saw that fluentd is implemented in crd but I can't find it on the helm chart. Do you know if there is any way to implement it or is it a feature yet to be developed?

**Comment by bonifaido** [comment]
The fluentD field is for enabling the fluentD sidecar for a Vault instance, you have these options to configure:
```go
	// FluentDEnabled specifies if FluentD based log exportation should be enabled
	// default: false
	FluentDEnabled bool `json:"fluentdEnabled,omitempty"`

	// FluentDImage specifices the FluentD image to use for Vault log exportation
	// default: fluent/fluentd:edge
	FluentDImage string `json:"fluentdImage,omitempty"`

	// FleuntDConfLocation is the location of the fluent.conf file
	// default: "/fluentd/etc"
	FleuntDConfLocation string `json:"fleuntdConfLocation,omitempty"`

	// FluentDConfig specifices the FluentD configuration to use for Vault log exportation
	// default:
	FluentDConfig string `json:"fluentdConfig,omitempty"`
```

**Comment by viniciusgarcia-hotmart** [comment]
Yes, but this is specific to the CRD you created, here on the helm chart I can’t find any fluentd related containers
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault/values.yaml

**Comment by bonifaido** [comment]
We don't install FluentD just a sidecar to Vault expose the logs if needed, but I think it is possible to grab the logs in a properly logging configured Kubernetes cluster even without this sidecar. Someone from the users just needed this in the past and sent a PR for this, but we never used this feature, maybe we should remove it.
