### ISSUE TITLE
[vault-secrets-webhook] Registry pinging error

### ISSUE THREAD

**Issue by Ais8Ooz8** [banzaicloud/bank-vaults#1349]
**Describe the bug**:

```
vault-secrets-webhook-f6fc96f66-4qr6c vault-secrets-webhook time="2021-06-03T19:01:32Z" level=error 
msg="admission webhook error: cannot fetch image descriptor: Get \"https://index.docker.io/v2/\": 
dial tcp 34.202.206.152:443: connect: connection refused" app=vault-secrets-webhook
```

**Expected behaviour**:
It seemed that this issue has already been resolved (registry pinging  = off) https://github.com/banzaicloud/bank-vaults/pull/750

**Environment details:**

* Kubernetes version (e.g. v1.10.2): v1.19.7
*  bank-vaults version (e.g. 0.4.17): 1.11.3
* Install method (e.g. helm or static manifests): helm

/kind bug

**Comment by bonifaido** [comment]
This seems to be a networking issue: `dial tcp 34.202.206.152:443: connect: connection refused`
If we turn ping off the next HTTP request towards the registry would result in the same error. I think this is a network configuration issue in your cluster rather.

**Comment by Ais8Ooz8** [comment]
The point is that I can run the image as long as I don't use secret injection, where the image is checked first.   

Is it possible to somehow turn ping off?
