### ISSUE TITLE
Mutating webhook is not idempotent

### ISSUE THREAD

**Issue by jasmdk** [banzaicloud/bank-vaults#1352]
**Describe the bug**:
We intend to use Velero to perform cluster backup including restic integration for volume snapshot, however Velero makes a backup of all resources including pods and does a restore of those as well. If we exclude pods, restic can not gain access to the mounted volumes to perform a snapshot.
The problem is when the pod is restored, then it already contains the copy-vault-env container, but the mutating webhook ignores that and appends another container and volume anyway. Kubernetes then fails with a validation error:
```
Pod "kiali-oauth2-proxy-76cdff896c-55p26" is invalid: [spec.volumes[3].name: Duplicate value: "vault-env", spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/vault/": must be unique, spec.initContainers[1].name: Duplicate value: "copy-vault-env"]
```

**Expected behaviour**:
According to the documentation https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#idempotence then the webhook must be idempotent:
> Mutating webhooks must be idempotent, able to successfully process an object they have already admitted and potentially modified. This is true for all mutating admission webhooks, since any change they can make in an object could already exist in the user-provided object, but it is essential for webhooks that opt into reinvocation

**Steps to reproduce the bug**:

1. Pick a pod which has already been mutated `kubectl get po <some-name> -o yaml > vault-test-pod.yaml`
2. Delete the pod `kubectl delete po <some-name>`
3. Re-create the original pod: `kubectl apply -f vault-test-pod.yaml`
4. Observe the validation error
```
The Pod "<some-name>" is invalid:
* spec.volumes[3].name: Duplicate value: "vault-env"
* spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/vault/": must be unique
* spec.initContainers[1].name: Duplicate value: "copy-vault-env"
```

**Additional context**:
Code shows that container and volume is appended if criterias match, but does not take into account if it has already been appended:
https://github.com/banzaicloud/bank-vaults/blob/master/pkg/webhook/pod.go#L49

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.19.7
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): k3d
- bank-vaults version (e.g. 0.4.17): 1.10.1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): see reproduce steps
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: any - see reproduce steps

/kind bug

**Comment by kannamr** [comment]
@jasmdk Hi, I am running into same issue. By any chance do you fix for this issue?

**Comment by bonifaido** [comment]
Totally valid I will push a fix for this shortly.

**Comment by bonifaido** [comment]
https://github.com/banzaicloud/bank-vaults/pull/1419 is incoming.
