### ISSUE TITLE
[Helm Vault] Unable to deploy to OpenShift due to hard-coded fsgroup

### ISSUE THREAD

**Issue by chris1786** [banzaicloud/bank-vaults#1353]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to deploy this chart to OpenShift, due to the pod fsGroup being hard-coded to 65534.

By default, each project in Openshift has an individual allocation of allowed group IDs, meaning a hard-coded default will not work, as a project will not generally have permission to use the requested group.

**Describe the solution you'd like**
My preference for working around this would be to follow the solution used by the Hashicorp Vault chart, and define a global flag that is set if the chart is being deployed to OpenShift, i.e. `globals.openshift` The securityContext block would then be wrapped within an if statement which checks that this flag is false, i.e.:

```
{{- if not .Values.global.openshift }}
securityContext:
  fsGroup: 65534
{{- end }}
```

**Describe alternatives you've considered**
An alternative would be to add a value for the fsGroup, setting the default in `values.yaml`, i.e.:

```
securityContext:
  fsGroup: {{ .Values.securityContext.fsGroup }}
```

**Additional context**
Happy to raise a PR for either of these changes

**Comment by bonifaido** [comment]
Totally valid @chris1786. Happy to review this as a PR!
