### ISSUE TITLE
[vault-env] Inline mutation doesn't use cache

### ISSUE THREAD

**Issue by moskitone** [banzaicloud/bank-vaults#1375]
**Describe the bug**:
[vault-env] Inline mutation doesn't use cache
        - name: DATABASE
          value: "postgres://${vault:database/production/creds/user#username}:${vault:database/production/creds/user#password}@${some_ip}:5432/database"
Having configuration like this vault-env does not use cache and makes two reads two from vault. In this case process receives wrong credentials

**Expected behaviour**:
Vault-env uses cache and does one read from vault.

**Steps to reproduce the bug**:
        - name: DATABASE
          value: "postgres://${vault:database/production/creds/user#username}:${vault:database/production/creds/user#password}@${some_ip}:5432/database"

**Additional context**:

/kind bug

**Comment by gaineryns** [comment]
hello,
i have a same bug. please how did you fixed it ?
