### ISSUE TITLE
[vault-secrets-webhook] helm deployments fail on AKS

### ISSUE THREAD

**Issue by dm91** [banzaicloud/bank-vaults#1384]
**Describe the bug**:
When doing helm deployments into the cluster replicasets fail to create in AKS with the error message seen below. Tested manually deploying a deployment using kubectl and the same image from the same registry and this deploys fine and is able to get secrets from vault. Also to note a helm deployment of that creates a job and not a replicaset didn't have any issues.

As a note we are running this config in AWS on EKS with no issues.

**Expected behaviour**:
replicaset's deploy fine with no issues

**Steps to reproduce the bug**:
AKS cluster with vault and vault-secret webhooks charts installed
Private acr registry for images

**Additional context**:
N/A

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.19
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AKS
- bank-vaults version (e.g. 0.4.17): vault-secret-webhook helm chart - 1.13.2, vault chart - 1.13.1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): these are the logs we get from the replicaset when trying to deploy via helm
`Warning FailedCreate 110s replicaset-controller Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"887288aa-a5f3-46d3-b212-01b085cf2aa5\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: cannot fetch image descriptor: GET <removed azure private registry address>: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.\"}}}") has prevented the request from succeeding`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
debug: true

certificate:
  useCertManager: true
  generate: false

env:
  VAULT_IMAGE: <private registry>/vault:1.6.2

vaultEnv:
  repository: <private registry>/vault-env

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    additionalLabels:
      release: prometheus

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 500m
    memory: 256Mi

image:
  repository: <private registry>/vault-secrets-webhook

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: vault-secrets-webhook
      topologyKey: "kubernetes.io/hostname"
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: vault-secrets-webhook
        topologyKey: "failure-domain.beta.kubernetes.io/zone"

podsFailurePolicy: Fail

objectSelector:
  matchExpressions:
  - key: k8s-app
    operator: NotIn
    values:
    - kube-proxy

tolerations:
  - operator: Equal
    key: arch
    value: arm64
    effect: NoSchedule
```

/kind bug

**Comment by bonifaido** [comment]
cc @sebader

**Comment by dm91** [comment]
doing some research I found an issue with similar error messages:
https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/55
although it's not vault-secret-webhook it looks similar in what it is trying to achieve so thought I would add it into here incase it help with this issue.

**Comment by josueCarvajal** [comment]
We had an issue similar to this when working with AKS, and it is a limitation or a caveat when using ACR (Azure container registry) keep that in mind that if your pod whatever it is deployments/statefulsets contains other sidecar containers for example istio, 

You will need to add a command in your .yaml for your deployment and for those sidecar containers that are being injected for example: 

`
command:
            - /entrypoint.sh
`

We had this issue and it was related that istio did not have the entry point and failed exactly with the same error when running it!
