### ISSUE TITLE
interacte with a Vault server  is fail

### ISSUE THREAD

**Issue by liuqi-sun** [banzaicloud/bank-vaults#1396]
vault server:
![image](https://user-images.githubusercontent.com/48784730/129046869-f3588691-d7d9-4d1e-a6e6-547447bab291.png)

bank valut client:
![image](https://user-images.githubusercontent.com/48784730/129047054-59c7c6e2-5e63-486c-ad23-e62858deda1a.png)

curl client:
success.
![image](https://user-images.githubusercontent.com/48784730/129052472-94445d21-dfb4-4966-a9ab-12c30ce0eab7.png)
bank valut client:
![image](https://user-images.githubusercontent.com/48784730/129052689-67f0f658-f64a-4025-a354-8bff99949f87.png)

**Comment by bonifaido** [comment]
Since with curl you hit the http endpoint please change the example to use http as well instead of https, or start a server with a proper TLS configuration.
