### ISSUE TITLE
vault-operator helm chart fails to install

### ISSUE THREAD

**Issue by dyvol777** [banzaicloud/bank-vaults#1410]
**Describe the bug**:
I am trying to install helm chart of vault-operator.
> helm upgrade --install vault-operator banzaicloud-stable/vault-operator

it fails with message 

> Error: failed to install CRD crds/etcd-cluster-crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

But etcd operator is disabled by default.

**Expected behaviour**:
Chart should installed correctly.

**Environment details**:
- Kubernetes version: 1.22.1
- Cloud-provider/provisioner: bare-metal
- Chart version: 1.13.2
- Install method: helm

/kind bug

**Comment by bonifaido** [comment]
Pushed https://github.com/banzaicloud/bank-vaults/pull/1411 to heal this. First step of the deprecated etcd-operator support removal.

Thanks for reporting!
