### ISSUE TITLE
Helm chart install failure due to missing apiVersion policy/v1 on K8s 1.20

### ISSUE THREAD

**Issue by adamantal** [banzaicloud/bank-vaults#1420]
**Describe the bug**:
The `vault` and `vault-secrets-webhook` Helm charts could not be installed after #1404 on Kubernetes `<v1.21`.

**Expected behaviour**:
Expected the install to succeed.

**Steps to reproduce the bug**:
Just following the steps described [here](https://github.com/banzaicloud/bank-vaults/tree/master/charts/vault):
```bash
$ kubectl create secret generic aws --from-literal=AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --from-literal=AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
$ helm install vault banzaicloud-stable/vault --set "vault.customSecrets[0].secretName=aws" --set "vault.customSecrets[0].mountPath=/vault/aws"
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1"
```

**Additional context**:
In #1404, more precisely [here](https://github.com/banzaicloud/bank-vaults/pull/1404/files#diff-db784479ce8c49f3f3a4add50408e44c4b12889d54bce11256e45f28e18431b5L2) the PDB's apiVersion has been changed from `policy/v1beta1` to `policy/v1`. The latter is only available from Kubernetes version 1.21 according to the [migration guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125).

**Environment details**:
- Kubernetes version (e.g. v1.10.2): `v1.20.6`
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): PKE
- bank-vaults version (e.g. 0.4.17): 1.14.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): -
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: -
- Helm version: v3.5.4

/kind bug

**Comment by bonifaido** [comment]
This should have been fixed in https://github.com/banzaicloud/bank-vaults/commit/d03bedf261cf4f1bf1bac32af7ccb397d4ba6d0d are you using this version @adamantal ?
