### ISSUE TITLE
Update Vault to 0.11

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#147]
https://www.hashicorp.com/blog/vault-0-11

**Comment by gowthamsubbu** [comment]
@bonifaido Please hold on for Vault 0.11.1. There is a problem with policy provisioning which is fixed and expected to be released in 0.11.1 and it is not available yet.

https://github.com/hashicorp/vault/issues/5219

**Comment by bonifaido** [comment]
Hi @gowthamsubbu, it was updated to Vault 0.11 already (https://github.com/banzaicloud/bank-vaults/releases/tag/0.2.19), but you can always set the Vault image tag in each of our projects (operator, helm chart)
