### ISSUE TITLE
Redis deployment doesn't read Vault secret

### ISSUE THREAD

**Issue by amirkhonov** [banzaicloud/bank-vaults#1472]
**Describe the bug**:
I'm trying to pass a password for Redis deployment in Kubernetes, but Redis can't see the secret from Vault. As a result, my Celery workers can't connect to Redis with AUTH key.

**Expected behaviour**:
Redis can view environment variable value and run correctly.

**Steps to reproduce the bug**:
1. Create a deployment in k8s - https://github.com/amirkhonov/vault-in-k8s-testing/blob/main/redis-deployment.yaml
2. Try to connect to Redis with AUTH key in Redis container and set a key. For example:
    ```bash
    # redis-cli -h localhost -a redis_password_from_secret
    Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
    localhost:6379> GET *
    (error) NOAUTH Authentication required.
    ```
3. You can see also errors in the application:
```
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 340, in read_response
    raise error
redis.exceptions.AuthenticationError: invalid password
```

**Additional context**:
vault-secrets-webhook mutating is working correctly. But there is something wrong with reading secrets from environment variables. I know that only main process can see secrets vault.

I've also tried to change the deployment command to:
```yaml
          command:
            - /usr/local/bin/docker-entrypoint.sh
            - redis-server
            - '--requirepass'
            - $REDIS_PASSWORD
```
with no effect.

Mutated pod looks like:
```yaml
      image: 'redis:5.0.14'
      command:
        - /vault/vault-env
      args:
        - /usr/local/bin/docker-entrypoint.sh
        - redis-server
        - '--requirepass'
        - $REDIS_PASSWORD
```

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.19.5
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): on-premises
- bank-vaults version (e.g. 0.4.17): HashiCorp Vault 1.7.0+prem
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):

/kind bug

**Comment by pbalogh-sa** [comment]
Hi @amirkhonov . Please execing into redis container and check the injected secret value using vault-env: `/vault/vault-env sh -c 'env'`. Maybe some character escaping issue happened.

**Comment by amirkhonov** [comment]
> Hi @amirkhonov . Please execing into redis container and check the injected secret value using vault-env: `/vault/vault-env sh -c 'env'`. Maybe some character escaping issue happened.

It is available here:
```bash
/data # /vault/vault-env sh -c 'env' | grep REDIS
INFO[0000] received new Vault token                      addr= app=vault-env path=kubernetes-dev role=k8s-dev
INFO[0000] initial Vault token arrived                   app=vault-env
INFO[0000] spawning process: [sh -c env]                 app=vault-env
....
REDIS_PASSWORD=password
....
```

**Comment by pbalogh-sa** [comment]
@amirkhonov 
As you wrote you used this command checking the connection:
```
# redis-cli -h localhost -a redis_password_from_secret
```
In this case the redis-cli didn't wrapped with vault-env so the redis-cli used the vault path instead of secret value defined in the ENV.

Please try to use:
```
# /vault/vault-env sh -c 'redis-cli -h localhost -a redis_password_from_secret'
```
