### ISSUE TITLE
[fluent-bit support] Allow setting a custom config name for fluentdConfig

### ISSUE THREAD

**Issue by thpham** [banzaicloud/bank-vaults#1475]
The goal of the feature request is to allow swapping the fluentd sidecar image with fluent-bit with minimal effort.

For the moment the name of the data attribute in `vault-fluentd-config` configmap is `fluent.conf` and is hardcoded [here](https://github.com/banzaicloud/bank-vaults/blob/1.14.3/operator/pkg/controller/vault/vault_controller.go#L1692).

We could then configure the vault CR with something like this:

```
fluentdEnabled: true
fluentdImage: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.21.2
fleuntdConfLocation: "/fluent-bit/etc/"

fluentdConfFile: "fluent-bit.conf"

fluentdConfig: |
  [PARSER]
      Name   json-vault
      Format json
      Time_Key time
      Time_Format %Y-%m-%dT%H:%M:%S %z

    [INPUT]
      Name        tail
      path        /vault/logs/vault.log
      Parser      json-vault
      Tag         s3.vault.audit

    [OUTPUT]
      Name s3
      Match *
      bucket bank-vaults
      region eu-west-1
      total_file_size 10M
      upload_timeout 1m
      use_put_object On
      s3_key_format_tag_delimiters .
      s3_key_format /logs/$TAG[2]/%Y/%m/%d/vault.json
      role_arn <iam_role_arn>
      content_type application/json
```

_Another point is that `envsConfig` are not propagated and available in the `auditlog-exporter` sidecar, which makes impossible to configure fluentd/fluent-bit sink plugins (S3/Cloudwatch/...) with `IAM Roles for Service Accounts (IRSA)` or `ACCESS_KEY / SECRET_ACCESS_KEY` that is already available like for the bank-vault container._

EDIT:

sorry, I just notice that `sidecarEnvsConfig` can do the job !

and another options would be that the fluent-bit image allows to define the path to the config through an environment variable. but this is not possible at the moment. I asked them if it could be added as well in the follwing [issue](https://github.com/aws/aws-for-fluent-bit/issues/270) and [PR](https://github.com/aws/aws-for-fluent-bit/pull/271).

If they accept, we could use the following attribute in the vault CR:

```
sidecarEnvsConfig:
    - name: FLUENT_BIT_CONFIG_FILE
      value: /fluent-bit/etc/fluent.conf
```  

I know that both projects could help to find a solution, please advise me what could be the best.

I hope you will find this request relevant for your product, thank you for your consideration.

EDIT:

here is a [draft commit](https://github.com/thpham/bank-vaults/commit/506ffdcc9bba5fcafe5333fe31c06dfa3d8f5773) of the idea.

**Comment by bonifaido** [comment]
Hi @thpham!

Thank you for the detailed analysis. Sounds like a really valuable addition. If the aforementioned PR can go into the fluentbit image, this would be a really great addition to our side as well.

I'm more than happy to review a PR for this!

**Comment by thpham** [comment]
@bonifaido , cool thank you.

here is the [PR]( https://github.com/banzaicloud/bank-vaults/pull/1476).
