### ISSUE TITLE
Auto renew ca.crt not working

### ISSUE THREAD

**Issue by kingdruid** [banzaicloud/bank-vaults#1521]
**Describe the bug**:
In case when **ca.crt** is older then **server.crt** by an amount greater than **tlsExpiryThreshold** option, the renew does not work. This is because only the server certificate is checked for the expiration date.

**Expected behaviour**:
Renew the certificate when CA expiration duration less then **tlsExpiryThreshold** option.

**Steps to reproduce the bug**:

1. Install vault-operator with helm chart
2. Apply the Vault Custom Resource with spec.size = 1
3. Wait more times than the threshold (tlsExpiryThreshold)
4. Resize the Vault cluster to 3 nodes (spec.size = 3) - at this step, the server certificate will be renewed, but the CA is not
5. Now the CA will expire before the renewal procedure is started

**Additional context**:
In our case, the end dates of the certificates differed by 6 months and **tlsExpiryThreshold** was 168h (by default).
When the **ca.crt** was expired, the expiration duration of the server certificate was greater than the threshold.
The CA certificate was not renewed and the vault cluster broke down.

**Environment details**:
- Kubernetes version: 1.20.11-do.0
- Cloud-provider/provisioner: DOKS
- bank-vaults version: 1.14.4
- Install method: Helm

/kind bug

**Comment by bonifaido** [comment]
So simply saying, if would check the **ca.crt** expiry time as well, this thing wouldn't happen, right?

**Comment by kingdruid** [comment]
Yes that's right

**Comment by bonifaido** [comment]
Great, fix on the way!

**Comment by bonifaido** [comment]
Could you please check https://github.com/banzaicloud/bank-vaults/pull/1525?
