### ISSUE TITLE
Automatically set the mount_accessor for a vault policy

### ISSUE THREAD

**Issue by BojanZelic** [banzaicloud/bank-vaults#1533]
**Is your feature request related to a problem? Please describe.**
When creating the vault CRD we have to provide mount accessor paths for any policies that use the the authentication method in the policy template. It would be nice to automatically retrieve this information. 

In my situation, I have multiple vault servers to setup and have to provide different values for each one.

For example:
```
externalConfig:
    policies:
      - name: read-namespace-secrets
        rules:  
            path "secret/data/namespace/{{identity.entity.aliases.auth_kubernetes_0a00d852.metadata.service_account_namespace}}/*" {
              capabilities = ["read"]
            }
    auth:
      - type: kubernetes
        path: kubernetes
        roles: 
         - name: test
            bound_service_account_names = ["*"]
            bound_service_account_namespaces = ["*"]
            policies = ["read-namespace-secrets"]
            ttl = "1h"
```
**Describe the solution you'd like**
It would be nice to be able to reference the mount_accessor value in the CRD somehow. Maybe via some sort of templating parameters?

ex:
```
externalConfig:
    policies:
      - name: read-namespace-secrets
        rules:  
            path "secret/data/namespace/{{identity.entity.aliases.{{ vault.kubernetes.mount_accessor }}.metadata.service_account_namespace}}/*" {
              capabilities = ["read"]
            }
    auth:
      - type: kubernetes
        path: kubernetes
        roles: 
         - name: test
            bound_service_account_names = ["*"]
            bound_service_account_namespaces = ["*"]
            policies = ["read-namespace-secrets"]
            ttl = "1h"
```

**Describe alternatives you've considered**
* maybe the mount_accessor value could be stored in a confimap & then referenced via an ENV variable

**Additional context**

**Comment by aabouzaid** [comment]
I've the exact use case.

**Comment by patoarvizu** [comment]
I'm also interested in this feature. What are the chances that this gets implemented and/or the timeline for it?

**Comment by JoseFMP** [comment]
This is a must. 
Othwerise, how do we know the `mount_accessor` ? Means this requires extra work or manual work to figure out the `mount_accesor` and put it manually into the template. But the original purpose of the template was to simplify the writing of the policies.

**Comment by patoarvizu** [comment]
Tagging maintainers @bonifaido @pbalogh-sa @baluchicken @matyix.

Is there any interest in adding this feature? Looks like there's some interest from the community, so it would be great to have some info on the likelihood or timeline for it.

(Related Slack thread if you'r rather discuss it there: https://community-banzaicloud.slack.com/archives/CFJJW9L94/p1656534023906849)

**Comment by bonifaido** [comment]
This is a really valuable feature and there is still interest in it.

I got really filled up with other stuff, but we are looking for a new maintainer at Banzai who can join us and help out here to speed up things!

**Comment by patoarvizu** [comment]
Thanks @bonifaido!

I think I've come up with a possible approach to get this done. Should I open a draft PR so you can have an early look and see if it's something that we could move forward with? It may take me a day or so to have something to show, but I can try to do it before the weekend.

**Comment by bonifaido** [comment]
I'm always here for a review! Take your time.

**Comment by patoarvizu** [comment]
@bonifaido I created draft PR #1651 with an initial approach for this. Thanks!
