### ISSUE TITLE
LDAP configuration without users

### ISSUE THREAD

**Issue by salkin** [banzaicloud/bank-vaults#155]
**Describe the bug**
When using externalConfig for ldap without mapping users bank-vaults prints error and stops configuring vault

**To Reproduce**
Create an externalConfig block with LDAP with only config and group blocks.
On bringup of vault the vault-configurer is printing:
```
time="2018-09-13T06:23:54Z" level=info msg="vault is not sealed, configuring..."
time="2018-09-13T06:23:54Z" level=error msg="error configuring vault: error finding users block for ldap: unable to cast <nil> of type <nil> to map[string]interface{}"
```

**Expected behavior**
Possible to have LDAP configuration without explicit need to give separate users access.

**Comment by bonifaido** [comment]
@salkin, thanks for the report, you are totally right, currently, these options were enforced, I have pushed a fix for it, and will release it soon. I will let you know.

**Comment by bonifaido** [comment]
0.2.22 is released now, from both bank-vault and the vault-operator.
