### ISSUE TITLE
[vault-secrets-webhook] Construct full database connection in the one environment variable

### ISSUE THREAD

**Issue by arturkasperek** [banzaicloud/bank-vaults#1553]
**Is your feature request related to a problem? Please describe.**
I wanna build a connection to the database. I'm holding on vault as well HOST and DB info. I ended up with the following template:
```
postgresql://${vault:database/creds/database#username}:${vault:database/creds/database#password}@${vault:secret/data/database#HOST}:5432/${vault:secret/data/database#DB}
```
Unfotently that template creates 2 separate database user leases. I end up with connection string that uses username from first lease and password from the second leasone - as a result I can't connect to the database

**Describe the solution you'd like**
I guess we should track common paths like `database/creds/database` and make only one lease

**Comment by bonifaido** [comment]
Hi @arturkasperek, which version of Bank-Vaults are you using? There is a path caching fix in the most recent version of BV.

**Comment by arturkasperek** [comment]
@bonifaido hi, my bank vault version is 1.15.0

**Comment by bonifaido** [comment]
Please try 1.15.1

**Comment by arturkasperek** [comment]
Will try, thanks for the advise :)

**Comment by arturkasperek** [comment]
@bonifaido the problem has not gone away  - I just tested that with `ghcr.io/banzaicloud/vault-secrets-webhook:1.15.1`

**Comment by arturkasperek** [comment]
@bonifaido It's fixed - thank you :)

**Comment by bonifaido** [comment]
Cool stuff @arturkasperek , would you mind if I close (or you close) this issue? :)

**Comment by arturkasperek** [comment]
Closed
