### ISSUE TITLE
Fluentd logging sidecar

### ISSUE THREAD

**Issue by gowthamsubbu** [banzaicloud/bank-vaults#163]
@bonifaido We are planning to introduce a fluentd side car in the vault deployment to manage Vault logs (audit, sys) and we can create a PR to get this feature added. Please let us know if you have any questions or concern.

**Comment by bonifaido** [comment]
Hi @gowthamsubbu, all PRs are welcome, this sounds like a nice addition. The only requirement from our side is that it should be optional, so users can turn it off if they don't want to use it.

**Comment by bonifaido** [comment]
Fixed by #174.
