### ISSUE TITLE
vault-env daemon setting incorrect TTL, causing app to crash

### ISSUE THREAD

**Issue by chrism417** [banzaicloud/bank-vaults#1643]
**Describe the bug**:
Occasionally the vault-env daemon will try to renew database creds for an app and will receive any other TTL that's not our default (3600s) such as 600/1716/etc.

The app logs show:

`time="2022-06-28T11:23:29Z" level=info msg="secret database/creds/db-redacted renewed for 743s" app=vault-env
time="2022-06-28T11:23:29Z" level=info msg="secret renewal for database/creds/db-redacted has stopped, sending SIGTERM to process" app=vault-env error="<nil>"
time="2022-06-28T11:23:29Z" level=info msg="received signal: terminated" app=vault-env`

**Expected behaviour**:
Creds renewing without error

**Steps to reproduce the bug**:
Enable dynamic creds for a database, inject them into an app (I see the issue in golang and java), and watch until it happens

**Additional context**:
This has been happening for several releases of bank vaults, including the latest and also including 1.14.2 and 1.15.3.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.22.6 and 1.23.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): kops
- bank-vaults version (e.g. 0.4.17): 1.15.3 and 1.14.2
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): See above

/kind bug

**Comment by chrism417** [comment]
Anyone available to assist with this? We're seeing it across all our apps every 24 hours

**Comment by caiofralmeida** [comment]
@macmiranda We experienced the same problem and discovered that the leases were missing access permissions. The permissions we added to the "default" policy were as follows:

```hcl
# Allow a token to renew a lease via lease_id in the request body; old path for
# old clients, new path for newer
path "sys/renew" {
   capabilities = ["update"]
}

path "sys/leases/renew" {
   capabilities = ["update"]
}

# Allow looking up lease properties. This requires knowing the lease ID ahead
# of time and does not disclose any sensitive information.
path "sys/leases/lookup" {
   capabilities = ["update"]
}
```
