### ISSUE TITLE
Idempotency issues when auth engine is already configured

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#167]
When using Vault 0.11:

```
time="2018-09-27T05:20:06Z" level=error msg="error configuring vault: error enabling kubernetes auth method for vault: Error making API request.\n\nURL: POST https://127.0.0.1:8200/v1/sys/auth/kubernetes\nCode: 400. Errors:\n\n* path is already in use"
```

~~```time="2018-09-17T21:40:39Z" level=error msg="error configuring vault: error configuring secret engines for vault: error mounting secret into vault: Error making API request.\n\nURL: POST https://127.0.0.1:8200/v1/sys/mounts/secret\nCode: 400. Errors:\n\n* existing mount at secret/"```~~(this got fixed in #177)

**Comment by granadacoder** [comment]
I would agree.  Show an "already configured' message if possible.

**Comment by bonifaido** [comment]
Fixed already.
