### ISSUE TITLE
vault-secrets-webhook: Mutation is not working

### ISSUE THREAD

**Issue by shaileshlaghane** [banzaicloud/bank-vaults#1687]
Describe the bug:
I am trying to update vault from 0.6.5 to 1.16, fetched all upstream changes, vault, vualt-operator, vault-configure, vault-secrets-webhook all pods are up and running fine. But getting psp error while other pods tries to fetch secret from vault.

`
  Warning  FailedCreate  2m42s (x5 over 3m25s)  statefulset-controller  create Pod xxxxx in StatefulSet xxxxx failed error: pods "xxxxx" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.initContainers[0].securityContext.runAsNonRoot: Invalid value: false: must be true spec.initContainers[0].securityContext.capabilities.add: Invalid value: "CHOWN": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "SETFCAP": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "SETGID": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "SETPCAP": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "SETUID": capability may not be added spec.initContainers[1].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden spec.initContainers[2].securityContext.runAsNonRoot: Invalid value: false: must be true spec.initContainers[2].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[2].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "CHOWN": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "SETFCAP": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "SETGID": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "SETPCAP": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "SETUID": capability may not be added]
  `

Expected behaviour:
The value of secret should be fetched in the pod

Steps to reproduce the bug:
Update vault to 1.16 from 0.6.5, try to fetch secret in a pod.

Additional context:
Can extract the value if tried manually using `vault kv get` command

Environment details:

Kubernetes version (e.g. v1.10.2): v1.20
Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
bank-vaults version (e.g. 0.4.17): 1.16
Install method (e.g. helm or static manifests): Helm
Logs from the misbehaving component (and any other relevant logs):
Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
/kind bug

**Comment by bumarcell** [comment]
How was this issue closed at the end? :D
