### ISSUE TITLE
Vault cross account role permission denied with 0.2.26

### ISSUE THREAD

**Issue by gowthamsubbu** [banzaicloud/bank-vaults#171]
@bonifaido  We are seeing the following error in configurer pod only when using 0.2.26 and not anything below. 

msg="error configuring vault: error configuring aws auth roles for vault: error putting vault-crossaccount-role-platformlive aws role into vault: Error making API request.\n\nURL: PUT https://vault.secrets:8200/v1/auth/aws/role/vault-crossaccount-role-platformlive\nCode: 400. Errors:\n\n* unable to resolve ARN \"arn:aws:iam::************:role/VaultCrossAccountRole-PlatformInfrastructure\" to internal ID: AccessDenied: Access denied\n\tstatus code: 403, request id: dbd4ecf0-c65e-11e8-ad97-d3c20a6b5ad9"

#140 was submitted to support cross account access.

**Comment by bonifaido** [comment]
It looks to me that the credentials that Vault was given are not allowed to access the role API in your AWS account.

**Comment by gowthamsubbu** [comment]
@bonifaido Found the issue related to our EKS IAM role. Thanks !

**Comment by bonifaido** [comment]
Great! Thanks :-)
