### ISSUE TITLE
Getting error : Errors:\n\n* claim \"iss\" is invalid" during OKE Cluster upgrade v1.21.1

### ISSUE THREAD

**Issue by signinred** [banzaicloud/bank-vaults#1722]
Version: banzaicloud/vault-env:0.8.1

Error:

`time="2022-11-18T08:14:04Z" level=info msg="Failed to request new Vault token Error making API request.\n\nURL: PUT https://topsecret-vault.system-secret:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* claim \"iss\" is invalid"
time="2022-11-18T08:14:09Z" level=info msg="Failed to request new Vault token Error making API request.\n\nURL: PUT https://topsecret-vault.system-secret:8200/v1/auth/kubernetes/login\nCode: 500. Errors:\n\n* claim \"iss\" is invalid"
time="2022-11-18T08:14:10Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token" app=vault-env`

> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:

**Expected behaviour**:
A concise description of what you expected to happen.

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- bank-vaults version (e.g. 0.4.17):
- Install method (e.g. helm or static manifests):
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by signinred** [comment]
@bonifaido Can you please help.

**Comment by signinred** [comment]
@akijakya  I have upgraded my vault to the fix version 1.13.0 and some of the pods is running now. Fix if working. 

But the upgraded image is not picking up by some of the vault pods. Could you please tell me in a kubernetes cluster (3 worker nodes) how many vault containers should be there. We have 7 PODs for vault. I am not familiar with vaults.  Thanks.

**Comment by akijakya** [comment]
Hi! Did you install Bank-Vaults via Helm chart? I would advise to upgrade all Vault components to the same version, which would be at least 1.13.1 (mind the patch version) for your issue to go away. The Vault version in use is also pretty outdated, but feel free to use it if you don't have any issues with it. 🙂 
As far as I know the number of Vault pods is related to the size given in the Custom Resource, not the number of your nodes.

**Comment by akijakya** [comment]
I assume the issue got solved! 🙂
