### ISSUE TITLE
vault operator is not allowing the update to statefulset annotations

### ISSUE THREAD

**Issue by suhastm19** [banzaicloud/bank-vaults#1757]
I am using [wave](https://github.com/wave-k8s/wave) which updates the stateful set annotation managed by vault operator when the secret is changed, but the operator is not allowing the change. Is there a way to allow wave to update this annotation in the stateful set?

**Comment by akijakya** [comment]
Hi! Could you specify more what you mean about the operator not allowing the change? Could this be a RBAC-kind of problem which can be solved by configuring wave to have access to vault?

**Comment by suhastm19** [comment]
Closing this issue since vault operator already has a mechanism of watching secrets with annotation, so no need for wave.
