### ISSUE TITLE
vault-addr annotation being ignored.

### ISSUE THREAD

**Issue by guirgouveia** [banzaicloud/bank-vaults#1794]
**Describe the bug**:
I'm trying to create a deployment with the annotations below, but the VAULT_ADDR variable is not being set, so vault-env is running with the default address and fails to obtain the token with the error below. 
It's happening with many deployments, not just one. 

```
 vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
 vault.security.banzaicloud.io/vault-role: omaticcloudrecordroutingservice
 vault.security.banzaicloud.io/vault-tls-secret: vault-tls
 vault.security.banzaicloud.io/vault-env-passthrough: "VAULT_ADDR, VAULT_ROLE"
```
```
omaticcloudrecordroutingservice time="2023-02-11T02:40:25Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault:8200/v1/auth/kubernetes/login\": dial tcp: lookup vault on 10.0.0.10:53: no such host"
omaticcloudrecordroutingservice time="2023-02-11T02:40:29Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault:8200/v1/auth/kubernetes/login\": dial tcp: lookup vault on 10.0.0.10:53: no such host"
omaticcloudrecordroutingservice time="2023-02-11T02:40:31Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token" app=vault-env
Stream closed EOF for omatic/omaticcloudrecordroutingservice-5567cb9d79-8pnv2 (copy-vault-env)
Stream closed EOF for omatic/omaticcloudrecordroutingservice-5567cb9d79-8pnv2 (omaticcloudrecordroutingservice)
```

**Expected behaviour**:
It was expected that the value set by the annotation created an environment variable VAULT_ADDR withm the value defined previously so that vault-env is able to request a new token. The variable VAULT_ADDR exists, but with the default value, not the one I set. 

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Environment details**:
- Kubernetes version (e.g. v1.23.12):
- Cloud-provider/provisioner: AKS
- bank-vaults version: 1.18.0
- Install method: helm
- Logs from the misbehaving component (and any other relevant logs):
-- Secrets webhook show nothing about the deployment
- Resource definition: https://gist.github.com/guirgouveia/00f07041e70b00de86ad8e7c1c6387aa
/kind bug

**Comment by akijakya** [comment]
Hi @guirgouveia! In the annotations of your example you used the `vault-addr` with the default value, that is why it was used by vault-env. Basically the annotations here are for configuring envs for vault-env, and the `vault-env-passthrough` annotation is used when you want an env var to be passed to the other containers in the pod by vault-env.

Also looking at the example on the link, these annotations should go under spec/template/metadata, like in [this](https://github.com/banzaicloud/bank-vaults/blob/7bcb69031294414610bda32ff98e2a5b3dcc1a21/deploy/test-deployment.yaml#L14) example.

I hope this helps you figuring out the correct configuration, please drop a feedback whether it worked or not!
