### ISSUE TITLE
Vault instances with large number of leases are unable to start

### ISSUE THREAD

**Issue by nosammai** [banzaicloud/bank-vaults#1813]
**Describe the bug**:
On a vault cluster with a large number of leases, the vault pods enter CrashLoopBackoff state due to the liveness probe failing during startup. Likely this could be fixed by adding a startup probe to the container to grant it additional time on first startup before the liveness probe takes over.

**Expected behaviour**:
Vault should be allowed a reasonable amount of time to fully start before the liveness probe can kill it.

**Steps to reproduce the bug**:
Populate a vault cluster with a large amount of leases, on our cluster we saw this at around 40-50k leases.
Restart a vault container

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.24.9
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): GKE
- bank-vaults version (e.g. 0.4.17): 1.13.1
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):
```
Liveness probe failed: Get "https://<ip redacted>:8200/v1/sys/init": dial tcp <ip redacted>:8200: connect: connection refused
Back-off restarting failed container
```
/kind bug

**Comment by jpuskar** [comment]
Did you find a workaround?
