### ISSUE TITLE
[vault-secrets-webhook] Helm chart 'vault-secrets-webhook.servingCertificate' include returns incorrect secret name

### ISSUE THREAD

**Issue by arjen-s** [banzaicloud/bank-vaults#1844]
**Describe the bug**:

When setting the 'certificate.servingCertificate' value in the Helm chart it should set the deployment's 'serving-cert' volume's secret, but it does not.
This turns out to be caused by the 'vault-secrets-webhook.servingCertificate' include in the _helpers.tpl file always returning the same string, **"%s-webhook-tls" (include "vault-secrets-webhook.fullname" .)"**, regardless of the certificate.servingCertificate variable having been set or not.

**Expected behaviour**:
The 'vault-secrets-webhook.servingCertificate' include in the _helpers.tpl file should return the name of the secret set in vault-secrets-webhook.servingCertificate if that's been set, not the default secret name.

**Steps to reproduce the bug**:
I'm using the vault-secrets-webhook v1.19.0 Helm chart to deploy the webhook.
I already have my own certificate and key in a secret and want to use that instead of having the chart generate its own.
I'm setting certificate.servingCertificate to the name of the secret containing the cert/key info like this:

```
certificate:
    useCertManager: false
    generate: false
    servingCertificate: internal-tls
```

Now note the 'vault-secrets-webhook' deployment's 'serving-cert' volume's secret being set incorrectly as it should have been set to 'internal-tls'.

**Environment details**:
- vault-secrets-webhook v1.19.0 Helm chart

/kind bug

**Comment by akijakya** [comment]
Hi @arjen-s, thanks for reporting this issue, also sorry for the late response! The solution you also suggested seemed to be easy to implement, so I went ahead and created a working solution, expect a PR soon!
