### ISSUE TITLE
Cannot unseal vault

### ISSUE THREAD

**Issue by bazzilio** [banzaicloud/bank-vaults#200]
**Describe the bug**
After install, bank-vaults can't unseal the vault database

**To Reproduce**
1. Install operator
```
# kubectl apply -f operator/deploy/rbac.yaml 
# kubectl apply -f operator/deploy/operator.yaml
```
```# kubectl logs vault-operator-74ffb56b8-cgfvp
time="2018-11-12T10:57:38Z" level=info msg="Go Version: go1.11.2"
time="2018-11-12T10:57:38Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-11-12T10:57:38Z" level=info msg="operator-sdk Version: 0.0.5+git"
time="2018-11-12T10:57:38Z" level=info msg="operator namespace: default"
time="2018-11-12T10:57:38Z" level=info msg="starting vaults controller"
time="2018-11-12T10:57:38Z" level=info msg="Liveness probe listening on: 8080"
```
2. Create vault instance
```
kubectl apply -f operator/deploy/cr.yaml
``` 
3. View logs:
https://gist.github.com/bazzilio/297349bf03b7a84f99bbb2900b75272f

It seems, that bank-vaults does not create secret when initialisation of cluster.

**Expected behavior**
Vault unsealed and vault keys exist in kubectl secrets

** Software version
kubernetes v1.12.2
docker 18.06.1-ce
ubuntu 18.04.1
bank-vaults and operator version - latest from github

**Comment by bonifaido** [comment]
Hi @bazzilio, this means that your default ServiceAccount in which the operator currently starts the Vault Pod doesn't have access to the Kubernetes Secrets API in the corresponding namespace. Right now there is no way to specify which ServiceAccount to use when creating the Vault instances with the CRD. I will add that option in a PR.

**Comment by bonifaido** [comment]
Fix incoming in: https://github.com/banzaicloud/bank-vaults/pull/201

**Comment by bonifaido** [comment]
@bazzilio #200 added support for specifying the ServiceAccount for the Vault instances, however the fix can be also applied by adding the right rule to the default service account which the operator started the instance, this will be released in https://github.com/banzaicloud/bank-vaults/releases/tag/0.3.13
