### ISSUE TITLE
vault unable to get unseal keys

### ISSUE THREAD

**Issue by GoingFast** [banzaicloud/bank-vaults#205]
**Describe the bug**
everything has gone ok so far but cant get vault running. when I check logs its saying

` level=error msg="error unsealing vault: unable to get key 'vault-unseal-0': error getting secret for key 'vault-unseal-0': secrets \"vault-unseal-keys\" not found"` 

why is it that? config is https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr.yaml. operator is deployed using helm

**To Reproduce**
helm install banzaicloud-stable/vault-operator --set image.tag=latest
kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/cr.yaml
kubectl logs vault-0 -c bank-vaults

**Comment by GoingFast** [comment]
@bonifaido it was my problem the config was fucked. I someho wmanaged to edit it after downloading it, configurer was logging errors.

this is fixed but I got one more question. are there any examples for setting up intermediate ca? I cant find any and searching the code for "intermediate" comes up nothing. its not implemented?

**Comment by bonifaido** [comment]
@GoingFast have you managed to set up the PKI configuration? (If this is what you were looking for)

**Comment by GoingFast** [comment]
yes sorry for delay all working ty
