### ISSUE TITLE
Custom SSL certificate

### ISSUE THREAD

**Issue by giovannicandido** [banzaicloud/bank-vaults#206]
I use vault as ssh otp token among other things. The problem is vault ssh client has one know attack: main in the middle.

If the vault server is switched to a hacker instance, then it can send fake ok answers and the hacker will get access to all servers. This is fairly easy to do.
The remediation to this is to validate the SSL certificate. Vault SSH helper has a **ca_cert** configuration, which is the path to a certificate auhority certification that validates the certification of vault server, also there is **tls_skip_verify** which skips this verification (and offcourse is insecure to use).

One could in theory access the ca certification that is generated by bankvault and use this as the validation. Problem is the generated certification has a common name of "vault.default" which is a dns valid only inside kubernetes cluster. This should be a parameter and must have ways to changeit.

The other alternative, is to use a user generated certificate, in other worlds, a custom SSL certificate.

That way someone could have a custom certificate authority, and validate the certificate using this. That is my case, I think is more convenient and secure.

By the way, the only way to trust this is by emitting your own CA, and validate against it. That is because valid SSL like letsencrypt can be emitted by anyone on internet.

Another alternative is to add a Ingress with the custom certificate. That is the route I will take.
For this to be a complete solution, I would like to disable the node port exposed service and the ssl, since internal trafic is already cryptographed on kubernetes (using weave or calico) which is avalible with **tls_disable** flag on installation.

So in resume, add the configurations:

* Add a mode to use custom CA and certificate on installation
* Disable the NodePort service or switch to internal service.
* Add a **common name** parameter (problem is this can change later)
* keep the tls_disable flag

I think this will offer compreensive alternatives to solve the problem.

**Comment by bonifaido** [comment]
Hi @giovannicandido,

- It is possible to disable NodePort Service type via the `serviceType: ClusterIP` attribute, see: https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/apis/vault/v1alpha1/types.go#L73

There are no plans to remove the detection of `tls_disable` Vault configuration.

You have to create an Ingress for the Vault service yourself to be able to expose this on a public way, we could automate the Ingress creation with the Operator if you think that is a good idea, I have no issues with that personally, only that it should be stated explicitly to create an Ingress and won't be enabled by default.

Would this work for you?

**Comment by bonifaido** [comment]
Yeah, sorry, the `serviceType` attribute wasn't documented, I will document it in the examples.

I think if we add the support for generating the Ingress resource for the user by the operator we shouldn't hardcode the annotations (the usual way of configuring Ingress controllers through Ingress resources) and for example TLS certificates. https://kubernetes.io/docs/concepts/services-networking/ingress/#tls But rather pass in a simplified Ingress block, like:
```yaml
ingress:
  annotations:
    key: value
  tls:
  - hosts: sslexample.foo.com
    secretName: testsecret-tls
```

I think the OTP documentation doesn't explicitly require self-signed certifices:
```This risk can be mitigated by using TLS for the connection to Vault and checking certificate validity.``` For me this reads means if you are using Let's encrpyt you are also validating the CA, it's just not a custom CA but it's a trusted one, so you don't have to pass it in explicitly the CA cert, because your client most probably knows about it (https://letsencrypt.org/certificates/).

I think instead of OTP SSH connections the signed certificate based way is mutch better, I have already blogged about it a few months ago: https://banzaicloud.com/blog/vault-dynamic-ssh/ and as the official documentation says it's the most powerful SSH based login:

```The signed SSH certificates is the simplest and most powerful in terms of setup complexity and in terms of being platform agnostic. By leveraging Vault's powerful CA capabilities and functionality built into OpenSSH, clients can SSH into target hosts using their own local SSH keys.```

**Comment by giovannicandido** [comment]
I forgot that in other to create a certificate you have to prove ownership of the dns name. I was thinking on an attacker that could create a valid certificate in other trusted certificate authority (like Geotrust) but that won't happen. The attack surface is smaller even on cloud (where dns and arp poisoning is doable but has local effects). So letsencrypt will do the job.

I will check the signed SSH certificates. The reason for me to use the OTP is to enforce reauthentication. I don't want indefinitely access to the servers, I want this to expire on each login and ask for password again. Delegate access is easy, terminate then is hell :-). Also there is the risk of compromised workstations. A liitle paranoid? Maybe... :-)

Thank you for good discussion here.

**Comment by giovannicandido** [comment]
Well I bet NSA can do it... but they have no intert in my clusters... lolololol

**Comment by giovannicandido** [comment]
Good to know they have TTL. I read the documentation, with a little automation on the client side (script to retrieve the ssl siging key and start the ssh session) it will indeed offer the same security level while keeping convinicence.

About the separate issue, it makes sense.
Thanks.

**Comment by bonifaido** [comment]
Thanks, closing this in favor of https://github.com/banzaicloud/bank-vaults/issues/208
