### ISSUE TITLE
Operator: create Ingress if specified

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#208]
I think if we add the support for generating the Ingress resource for the user by the operator we shouldn't hardcode the annotations (the usual way of configuring Ingress controllers through Ingress resources) and for example TLS certificates. https://kubernetes.io/docs/concepts/services-networking/ingress/#tls But rather pass in a simplified Ingress block, like:
```
ingress:
  annotations:
    key: value
  tls:
  - hosts: sslexample.foo.com
    secretName: testsecret-tls```

**Comment by devlounge** [comment]
Hi,

When is this ingress feature coming?
I set ui:true but nothing gets created to access it

**Comment by bonifaido** [comment]
Still in the pipe, but currently nobody is working on it, we can schedule it in the a following weeks if nobody is planning to submit a PR for it.

**Comment by bonifaido** [comment]
PR submitted: https://github.com/banzaicloud/bank-vaults/pull/304
