### ISSUE TITLE
rbac error with default deployment

### ISSUE THREAD

**Issue by s0rc3r3r01** [banzaicloud/bank-vaults#211]
**Describe the bug**
A default test deployment on AKS executing the steps below results in a RBAC error on Vault side :

`2018/11/21 17:18:35 Failed to request new Vault token Error making API request.
URL: PUT https://10.0.83.211:8200/v1/auth/kubernetes/login
Code: 500. Errors:
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"tokenreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:default:vault-operator\" cannot create tokenreviews.authentication.k8s.io at the cluster scope","reason":"Forbidden","details":{"group":"authentication.k8s.io","kind":"tokenreviews"},"code":403}`

**To Reproduce**
1. Connect to the cluster as cluster-admin
2. kubectl apply -f deploy/rbac.yaml
3. kubectl apply -f deploy/operator.yaml
4. kubectl apply -f deploy/cr.yaml

**Expected behavior**
It should be just working. 
The operator is working correctly when manually adding the correct clusterrolebinding:
` kubectl create clusterrolebinding add-cluster-role   --clusterrole=system:auth-delegator   --serviceaccount=default:vault-operator
clusterrolebinding.rbac.authorization.k8s.io/add-cluster-role created`
**Additional context**
AKS
`| => kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`

Do you think this is simply a documentation bug and the RBAC of the example needs to be edited or more changes are required ?

**Comment by bonifaido** [comment]
Hi Frederico! You are right, the `auth-delegator` ClusterRole was missing from the example binding, I have pushed a fix in #212 for this?

I have provisioned an AKS cluster (with https://github.com/banzaicloud/pipeline) to make sure I can reproduce the issue and see that the fix works. Out of curiosity, how do you have provisioned the cluster?
