### ISSUE TITLE
Run bank-vaults using existing ETCD

### ISSUE THREAD

**Issue by LinAnt** [banzaicloud/bank-vaults#220]
Hello,

Is it possible to use an existing etcd as backend for the banzai-cloud operator? It seems it is hardcoded to use the coreos operator with no persistent volumes at the moment.

Thank you for open sourcing this awesome operator.

**Comment by bonifaido** [comment]
You're welcome, I hope it worked for you! (https://github.com/banzaicloud/bank-vaults/issues/217)

**Comment by LinAnt** [comment]
> You're welcome, I hope it worked for you! (#217)

Yep, I could not find #217 at first so in my confusion I opened this one :)
