### ISSUE TITLE
Running Vault 1.0.0 breaks Configurer

### ISSUE THREAD

**Issue by rblaine95** [banzaicloud/bank-vaults#222]
**Describe the bug**
When using Vault v1.0.0, the configurer has problems configuring Vault.

**To Reproduce**
1. Deploy Vault Operator
2. Deploy a Vault cluster with a Vault image that's v1.0.0 (for example: `quay.io/zenlab/vault:1.0.0-1`)
3. Get the logs for the configurer
```bash
$ oc logs -f vault-configurer-7d6459fbc9-ht9g4 

time="2018-12-06T09:07:05Z" level=info msg="New config file change \"Initial\": CREATE"
time="2018-12-06T09:07:05Z" level=info msg="checking if vault is sealed..."
time="2018-12-06T09:08:09Z" level=info msg="checking if vault is active..."
time="2018-12-06T09:08:09Z" level=info msg="vault is unsealed and active, configuring..."
time="2018-12-06T09:08:09Z" level=error msg="error configuring vault: error configuring plugins for vault: Failed to retrieve list of plugins: Error making API request.\n\nURL: LIST https://vault.myproject:8200/v1/sys/plugins/catalog\nCode: 405. Errors:\n\n* 1 error occurred:\n\t* unsupported operation\n\n"
```

**Expected behavior**
Configurer should be able to get the list of plugins and continue with the configuration of Vault.

**Desktop:**
 - OS: Arch Linux
 - K8s: OKD v3.11.0

**Additional context**
It looks like in previous versions of Vault (pre-1.0.0) the `LIST` operation on the `/v1/sys/plugins/catalog` was a valid operation, but it looks like now it needs to be changed to `GET`.

This only happens with v1.0.0 of Vault.

**Comment by bonifaido** [comment]
Hi @rblaine95, yes this is handled in the new version of the client in a backward compatible way, so I will update the client dependencies and check if it works!

https://github.com/hashicorp/vault/blob/v1.0.0/api/sys_plugins.go#L36

**Comment by bonifaido** [comment]
I have checked and the backward compatibility mechanism doesn't seem to work for me with 0.11.5. I have submitted a PR to the upstream Vault project to resolve this (I hope I fixed it correctly 🤞)

https://github.com/hashicorp/vault/pull/5913

My only concert is that if someone happens to use bank-vaults with 0.11.5 and don't want to upgrade Vault versions in the near future, he/she will be forced to use the pre-Vault 1.0.0 supporting version of bank-vaults.
