### ISSUE TITLE
Support Vault auto-unseal based deployments

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#228]
See https://github.com/banzaicloud/bank-vaults/pull/224 for the original thread.

**Comment by raoofm** [comment]
+1

**Comment by raoofm** [comment]
https://www.vaultproject.io/docs/configuration/seal/awskms.html

**Comment by bonifaido** [comment]
#429 has fixed this issue partially, but we also have to disable unsealing in the operator (via parsing the Vault config) if we detect that auto-unseal is enabled.

**Comment by primeroz** [comment]
a Few info on things to change when the operator detect that autounseal is enabled

* Setting of `secret_shares` and the `threshold_shares` to the same value of 1 ( see [here](https://www.vaultproject.io/api/system/init.html#secret_threshold) ) and the `stored_shares` set to the same as secret shares ( see [here](https://www.vaultproject.io/api/system/init.html#stored_shares) ) value of 1. This will happen automatically and logged as WARNING if not enforce
`vault-0 vault 2019-04-18T13:49:53.470Z [WARN]  core: stored keys supported on init, forcing shares/threshold to 1`
* when starting with autounseal disable the "bank-vaults unseal" loop to avoid errors like 
`vault-0 bank-vaults time="2019-04-18T13:56:41Z" level=error msg="error unsealing vault: unable to get key 'vault-unseal-0': error getting object for key 'vault-unseal-0': storage: object doesn't exist"`
  * Should we just have a sleep loop ?

**Comment by jhohertz** [comment]
I am trying to figure out what's left to do here... if I can help in any way. I am looking to use the awskms autounseal.

Is it mostly just needed to knock out the sidecar that is currently doing the unseal? IE: https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/controller/vault/vault_controller.go#L999-L1018

Or would it be preferred that the unseal command of bankvaults simply notice that autounseal is being used, and skip much of it's logic, perhaps mostly just doing initialization steps for new vaults?

I'd really like to replace some existing autounseal based vaults with ones managed by the operator, and am happy to jump in to help if I can get some guidance on approach.

**Comment by bonifaido** [comment]
Hi @jhohertz, thank you for your offer, help is always welcomed!

The second option sounds better to me, I think we should support this with another CLI flag which would be sent down by the operator since it knows the Vault config in the first hand.

**Comment by jhohertz** [comment]
I've started on one approach, essentially to create a new unsealConfig type of "vault-autounseal", which would be the clear signal to just let vault handle it. One snarl I am trying to wrap my head around, is every unsealConfig type (or mode) appears to have an underlying KV store associated with it, and I'm not sure what if anything that looks like for auto unseal.

**Comment by ccojocar** [comment]
I extend the vault provisioning to support vault with auto-unsealing.  See the linked PR.

There is still some work left to extend the `configure` container to be able to do post unsealing configuration (e.g. mount the KV secrets engine which in latest vault version is not mounted by default). I will send it in a different PR.

**Comment by bonifaido** [comment]
Can't we just reuse the already existing init method, which stores the root token as well, so configuration part is done as well and we do not need a fully new code path?

**Comment by primeroz** [comment]
@ccojocar @bonifaido see my comments in the PR
