### ISSUE TITLE
vault-operator / vault / vault_cr

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#229]
I'm using vault-operator along with etcd-operator.

Then I created clusterrolebinding, serviceaccount and vault_cr_etcd_ha. I'm not sure if I should go the CR way or just deploy using the vault chart. Is there a guide with deploy steps?

**Comment by bonifaido** [comment]
The Kubernetes manifests in the `operator/deployment` directory are more of an example manifests, however with slight modifications they can be used in any `kubectl apply -f` workflows. If you use Helm the vault-operator Helm charts is the way to go.

**Comment by raoofm** [comment]
ok i'll try to be more clear

I would like to go the helm way. So I used vault-operator and it creates the crd, vault-operator deployment and etcd-operator (No sign of actual vault or etcd cluster yet). Though I see a warning in etcd-operator logs
```
time="2018-12-11T20:22:23Z" level=info msg="etcd-operator Version: 0.9.3"
time="2018-12-11T20:22:23Z" level=info msg="Git SHA: 44f2671c"
time="2018-12-11T20:22:23Z" level=info msg="Go Version: go1.10"
time="2018-12-11T20:22:23Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-12-11T20:22:41Z" level=info msg="Event(v1.ObjectReference{Kind:\"Endpoints\", Namespace:\"default\", Name:\"etcd-operator\", UID:\"014d651b-733d-11e8-a714-02c3eb125000\", APIVersion:\"v1\", ResourceVersion:\"115536810\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' vault-operator-etcd-operator-etcd-operator-56dbb9cbc9-6kb9d became leader"
time="2018-12-11T20:22:41Z" level=warning msg="fail to handle event: ignore failed cluster (vault-etcd). Please delete its CR" pkg=controller
```
vault-operator logs
```
time="2018-12-11T20:22:58Z" level=info msg="Go Version: go1.11.2"
time="2018-12-11T20:22:58Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-12-11T20:22:58Z" level=info msg="operator-sdk Version: 0.0.5+git"
time="2018-12-11T20:22:58Z" level=info msg="operator namespace: "
time="2018-12-11T20:22:58Z" level=info msg="starting vaults controller"
time="2018-12-11T20:22:58Z" level=info msg="Liveness probe listening on: 8080"
```

I think the missing piece here is the kind: Vault which I mentioned here https://github.com/banzaicloud/banzai-charts/issues/574

On the other hand, is there a usecase to use vault chart https://github.com/banzaicloud/banzai-charts/tree/master/vault?

Is it supposed to be used along with vault-operator or just independently?

**Comment by raoofm** [comment]
@bonifaido I also want to add that shouldn't etcd-operator have the responsibility of creating etcd cluster rather than the cluster being created when vault cr is applied?

**Comment by bonifaido** [comment]
you have

**Comment by bonifaido** [comment]
The Vault chart is used by us in production as well (as the operator), in certain situations, it is more straightforward to use the simple chart, it's up to you which one you choose. The operator offers more features of course, for example HA Vault setup

**Comment by bonifaido** [comment]
This error message:

```time="2018-12-11T20:22:41Z" level=warning msg="fail to handle event: ignore failed cluster (vault-etcd). Please delete its CR" pkg=controller
```

Could you please describe how to reproduce this?

**Comment by raoofm** [comment]
@bonifaido I'll get back to you on this

**Comment by bonifaido** [comment]
Any updates on this one @raoofm ?

**Comment by raoofm** [comment]
@bonifaido this can be closed. I can't reproduce it, may be I wasn't using etcd-operator CR the right way.

**Comment by matyix** [comment]
OK, I am closing it now - let us know if you face it again.
