### ISSUE TITLE
Rotation of certs

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#230]
**Is your feature request related to a problem? Please describe.**
Certs are generated as kubernetes secrets by name vault-tls and etcd-cluster-tls automatically and are valid for 1 year. What is the path to replace / renew / auto renew?

**Comment by bonifaido** [comment]
Hi @raoofm, this is a WIP: https://github.com/banzaicloud/bank-vaults/issues/159 so if you don't mind I will close this one.

**Comment by raoofm** [comment]
@bonifaido thanks. sorry i should have checked the issues.
