### ISSUE TITLE
vault-operator doesn't print the watch namespace

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#231]
vault-operator doesn't print the namespace
```
time="2018-12-11T20:22:58Z" level=info msg="Go Version: go1.11.2"
time="2018-12-11T20:22:58Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-12-11T20:22:58Z" level=info msg="operator-sdk Version: 0.0.5+git"
time="2018-12-11T20:22:58Z" level=info msg="operator namespace: "
time="2018-12-11T20:22:58Z" level=info msg="starting vaults controller"
time="2018-12-11T20:22:58Z" level=info msg="Liveness probe listening on: 8080"
```

Also operator-sdk version seems too old v0.0.5 is behind 6 releases.

**Comment by baluchicken** [comment]
Hi @raoofm thanks for the issue. By default Kubernetes apimachinery represents all namespaces with an empty string, that is why you are seeing the copied log message. https://github.com/kubernetes/apimachinery/blob/57dc7e687b5426ecb5df4cabdcdce30fddb74f22/pkg/apis/meta/v1/types.go#L279
If you want to watch a specific namespace with the operator please set the OPERATOR_NAMESPACE env variable. If the operator watches only one namespace the log will print that one for you.

**Comment by raoofm** [comment]
@baluchicken I tried that too earlier and it was still empty. Used helm chart for operator and set watchNamespace: "dev" which is being set as env variable OPERATOR_NAMESPACE in the deployment

Right now I left it blank before reporting. I'll check again if you want but I'm pretty sure.

**Comment by raoofm** [comment]
ok found the issue
here is the pr
https://github.com/banzaicloud/banzai-charts/pull/571

**Comment by raoofm** [comment]
@baluchicken what about the operator version?

**Comment by baluchicken** [comment]
Thanks, and nice catch:)

**Comment by baluchicken** [comment]
> @baluchicken what about the operator version?

https://github.com/banzaicloud/bank-vaults/issues/232
I created a new issue for that we are going to bump the version soon.
