### ISSUE TITLE
bank-vaults should continue with unseal if already initialized but fails

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#235]
**Describe the bug**
bank-vaults should continue with unseal if already initialized but fails with error
```
level=fatal msg="error initializing vault: error before init: keystore value for 'vault-root' already exists"
```

**Comment by bonifaido** [comment]
What was the command and with which parameters that caused this issue?

**Comment by raoofm** [comment]
@bonifaido I'll get back to you on this

**Comment by bzuelke** [comment]
I ran into this testing out this operator. I deleted the vault-0 pod to test how it would recover. I don't have the unseal job working yet, so manually unsealed vault only to find that in the bank-vaults container on vault-0 and the pod not fully coming back. I'm assuming it's going to be the same behavior as if the auto unseal unsealed it as well but wanted to throw that out there. 

`kubectl logs vault-0 -nvault -cbank-vaults
time="2018-12-19T18:03:44Z" level=info msg="initializing vault..."
time="2018-12-19T18:03:44Z" level=info msg="vault metrics exporter enabled: :9091/metrics"
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /metrics                  --> github.com/banzaicloud/bank-vaults/vendor/github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :9091
time="2018-12-19T18:03:44Z" level=info msg="initializing vault"
time="2018-12-19T18:03:44Z" level=fatal msg="error initializing vault: error before init: keystore value for 'vault-root' already exists"
[18:06:40] brandon@ip-10-184-254-69:~/repos/bank-vaults/operator/deploy/vault$ kubectl get pods -nvault
NAME                                READY     STATUS             RESTARTS   AGE
etcd-cluster-gdszcspv4z             1/1       Running            0          1h
etcd-cluster-jkklg5fg4f             1/1       Running            0          1h
etcd-cluster-zh6flv9nnz             1/1       Running            0          1h
etcd-operator-58ccf988f-pqtjh       1/1       Running            0          2h
vault-0                             2/3       CrashLoopBackOff   26         1h
vault-1                             1/3       CrashLoopBackOff   28         1h
vault-configurer-85f58bc876-lzvnk   1/1       Running            0          1h
vault-operator-7494685d7f-gmnws     1/1       Running            0          2h`

**Comment by bzuelke** [comment]
Yea I used that and then deployed the cr-etcd-ha.yaml after initial deployment. I did see that after I murdered the pod I had to reinitialize and then edit the existing secret with the new keys then things started to work.

**Comment by matyix** [comment]
@raoofm @bzuelke fixed in master and a [release](https://github.com/banzaicloud/bank-vaults/tree/0.3.24) is available as well. Thanks for reporting this.

**Comment by raoofm** [comment]
@thanks matyix will try it out

**Comment by bzuelke** [comment]
you guys are crazy fast for turn around. awesome stuff thanks!
