### ISSUE TITLE
banks-vault operator is too verbose

### ISSUE THREAD

**Issue by szymonpk** [banzaicloud/bank-vaults#236]
**Describe the bug**
I have deployed banks-vault on MiniKube (K8s v1.10) with crd.yaml. It starts fine. But it is too verbose and I do not see an option to lower log level. Every minute pretty huge JSON is put into the logs.

**To Reproduce**
1. Deploy banks-vault on MiniKube with default settings using crd.yaml.
2. Check vault-operator container logs:
```
vault-operator-6666c784ff-5kfhc vault-operator time="2018-12-14T09:24:41Z" level=info msg="Deployed:"
vault-operator-6666c784ff-5kfhc vault-operator {
+ 100 lines of json
```

And those logs repeat every minute.

**Expected behavior**
Minimal number of logs.

'Deployed' JSON could be moved to the debug log level or maybe put the JSON in the log only when deployment is changed/created?

**Comment by raoofm** [comment]
Also the vault instance started by the cr is at debug level. Is there a way to lower it as well?

**Comment by bonifaido** [comment]
Hi pushing a fix for this right now.

**Comment by matyix** [comment]
Hello @szymonpk - thanks for reporting it, the fix went into master and [release pushed](https://github.com/banzaicloud/bank-vaults/releases/tag/0.3.22). You can now configure the desired log level.

**Comment by szymonpk** [comment]
Thanks @matyix. That was fast turnaround ;-)

**Comment by matyix** [comment]
@szymonpk we try our best - thanks again for reporting it.

**Comment by raoofm** [comment]
yup @szymonpk thanks
