### ISSUE TITLE
Nodeselectors  support

### ISSUE THREAD

**Issue by sespindola** [banzaicloud/bank-vaults#240]
Hi, 
  We have a globally distributed on-premises k8s cluster and need to deploy a few vault instances in
  specific nodes due to data residency constraints.
 
  Is there any way to specify a nodeSelector in the vault CRD? 
  If not, please let me know and I'll try to add noselector support to the crd and send a PR.

Thanks.

**Comment by bonifaido** [comment]
Hi @sespindola!

Thank you for your submission. I would suggest using the already existing K8S structs for `PodSpec.nodeSelector` and inline those structs into the CRD `type VaultSpec` the same way as environment variables are inlined: https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/apis/vault/v1alpha1/types.go#L64 in your solution, let me know if you need any help with that!

**Comment by szymonpk** [comment]
@sespindola if you k8s supports affinity, you may be interested in https://github.com/banzaicloud/bank-vaults/pull/268.

**Comment by bonifaido** [comment]
Fixed by: #268.
