### ISSUE TITLE
auth-method custom path

### ISSUE THREAD

**Issue by shidoh** [banzaicloud/bank-vaults#241]
Is it possible to specify an alternative method path for kubernetes in webhook annotations?
default is: ```auth/kubernetes/login```
I would like to: ```auth/kube-cluster-a/login```

**Comment by bonifaido** [comment]
Hi @shidoh, this is currently not supported, but I will submit a PR soon to resolve this.

**Comment by bonifaido** [comment]
@shidoh 0.3.23 contains the suggested enhancement, thank you for the report!
