### ISSUE TITLE
Deploy operator fails on k8s 1.11.5 cluster

### ISSUE THREAD

**Issue by JohnHoward9** [banzaicloud/bank-vaults#263]
Deployment of operator reports missing namespace

**To Reproduce**
kubectl apply -f operator/deploy/rbac.yaml

**Expected behavior**
Operator deployed

**Actual behavior**
The ClusterRoleBinding "vault-operator" is invalid: subjects[0].namespace: Required value

**Comment by bonifaido** [comment]
Hi @JohnHoward9, you are absolutely right, this was factored out during last week when we changed to the new operator framework. It will be fixed in https://github.com/banzaicloud/bank-vaults/pull/264

**Comment by matyix** [comment]
Hello @JohnHoward9 - the fix was pushed to `master` - thanks for reporting and please let us know if it works for you as well.

**Comment by JohnHoward9** [comment]
Thanks, working now
