### ISSUE TITLE
Webhook breaks "api-resources" in cluster

### ISSUE THREAD

**Issue by shidoh** [banzaicloud/bank-vaults#265]
**Describe the bug**
after the deployment of the chart does not work request "api-resources"

**To Reproduce**
1. ```helm upgrade --namespace vswh --install vswh banzaicloud-stable/vault-secrets-webhook```
2. ```kubectl api-resources```
```error: unable to retrieve the complete list of server APIs: admission.banzaicloud.com/v1beta1: the server could not find the requested resource```
3. ```helm delete vswh --purge```
4. ```kubectl api-resources``` - works correctly

due to unavailability of api-resources, our deployments (kubectl apply, kubectl rollout) give an error:
```Error loading discovery information: the server could not find the requested resource```

**Comment by bonifaido** [comment]
The APIService resource was extraneous (and broken), so I have removed it, it will be fixed in banzai-charts, see: https://github.com/banzaicloud/banzai-charts/pull/597
