### ISSUE TITLE
Error in exmaple manifests; "config.storage.aws" should be "config.storage.s3", causes an error during startup

### ISSUE THREAD

**Issue by ilyache** [banzaicloud/bank-vaults#269]
**Describe the bug**
The manifests in the ["operator/build"](https://github.com/banzaicloud/bank-vaults/tree/master/operator/deploy) folder that refer to AWS have an error in them, the correct storage type for AWS should be `s3`. It's currently: `config.storage.aws` ([link](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-aws.yaml#L32)).

And when deployed as is, the vault container won't start and will print the following: 
> Unknown storage type aws

After changing it to: `config.storage.s3`, It starts up normally. I'll be happy to open a PR and fix it myself if you guys are open to contributers outside of Banzai Cloud.

**Comment by bonifaido** [comment]
Hi @ilyache, yes indeed we are open. :-) 
You're right, that example is messed up.
We are more than happy to receive the PRs/issues!
