### ISSUE TITLE
kubernetes secret backend using vault plugin

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#271]
**Is your feature request related to a problem? Please describe.**
A kubernetes secret backend using vault plugin.

**Describe the solution you'd like**
https://github.com/jetbrains-infra/vault-plugin-secrets-kubernetes

**Comment by bonifaido** [comment]
This is a very interesting plugin, which I'm currently experimenting withz stay tuned.

**Comment by bonifaido** [comment]
Plugin configuration has been already implemented users are free to use any external plugins.
