### ISSUE TITLE
Resources for containers

### ISSUE THREAD

**Issue by tomaszkiewicz** [banzaicloud/bank-vaults#273]
**Is your feature request related to a problem? Please describe.**
At the moment when operator creates a pod for vault and banks-vault containers it doesn't specify any resources requests or limits, so it's hard to manage and calculate the capacity for the pods.

**Describe the solution you'd like**
I'd like to be able to specify resources in CRD and have some default resources specified in the operator.

**Describe alternatives you've considered**
Provide static resource requests and limits for prometheus-exporter and banks-vault container, this way vault container can get its resource requests and limits form limit ranger (without that every container in the pod gets the same requests/limits from limit ranger).

**Comment by bonifaido** [comment]
Hi @tomaszkiewicz, you are right, this is not implemented currently. We usually follow the pattern of inlining the same Kubernetes Go types here as Kubernetes uses in the original container definitions see environment variables and node affinities in the CRD. If you have any spare cycles to submit a PR for this, we are more than happy to review/help through the implementation process.
