### ISSUE TITLE
Vault Client should wait for initial token with a timeout

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#282]
**Describe the bug**
If the `NewClient` call can't get an initial Vault token it never returns, see:
https://github.com/banzaicloud/bank-vaults/blob/master/pkg/vault/client.go#L188

**Expected behavior**
The waiting for the `<-initialTokenArrived` should timeout after a certain number of seconds, should be configurable.

**Comment by TomaszKlosinski** [comment]
Hi @bonifaido , how can I increase client timeout for the initial token?
