### ISSUE TITLE
Need to create secrets during startup.

### ISSUE THREAD

**Issue by rahmnathan** [banzaicloud/bank-vaults#285]
Is there a way to create secrets with some pre-populated key/values during installation? I found the secrets section of externalConfiguration very useful for creating a kv Secrets engine, but was wondering if there's a way to extend that to actually populate some secrets into the engine in a similar way. We have many services and it would be useful to add boilerplate configuration during install to make it easier to come back and do our manual configuration.

If this is not possible via the CRD, does anyone have any suggestions on how to best manage something like this?

Thanks

**Comment by rahmnathan** [comment]
@bonifaido The use-case I have is SpringBoot applications with a fair amount of configuration, most of it boilerplate. Here's a simple example (smaller than most of our config files):

{
  "hibernate.encryption.password": "<redacted>",
  "logging.level.root": "info",
  "server.port": "8080",
  "server.ssl.enabled": "false",
  "spring.datasource.password": "<redacted>",
  "spring.datasource.url": "jdbc:postgresql://postgres:5432/<redacted>",
  "spring.datasource.username": "<redacted>",
  "spring.jpa.database-platform": "org.hibernate.dialect.PostgreSQLDialect",
  "spring.jpa.hibernate.ddl-auto": "validate"
}

As you can see, much of that is not sensitive data and it would be nice to be able to load that during the installation and someone could come back and fill in the 'redacted' bits later. Not a big deal, but it'd be nice if that was a possibility.

**Comment by bonifaido** [comment]
@rahmnathan, how do you install these applications into your cluster, with Helm charts? Are you using spring-config with Vault backend?

I think some parts are meant to be loaded from Vault but some parts can be just sent in as a value to the chart during installation, for example where the `postgres` database is available.

It is also possible to use Vault with dynamic database credentials and bank-vaults supports configuring that, see: https://github.com/banzaicloud/bank-vaults/blob/master/vault-config.yml#L121

Anyhow, we have an article about Spring Boot application setup on top of Kubernetes, and it talks with Vault, maybe this could help you: https://banzaicloud.com/blog/vault-java-spotguide/
And also have a spring-boot spotguide which can be tried out on our platform: https://github.com/spotguides/spring-boot

**Comment by rahmnathan** [comment]
@bonifaido Yes, we use Helm charts to deploy Spring Boot applications that leverage spring cloud config.

Our desire is to simplify our deployments by having only one central location to manage all of our configuration (secrets and non-secrets). Most of the configuration is boilerplate (non-secret) which is what we would want to automatically populate Vault with. We're trying to automate as much as possible so that a developer doesn't have to login and configure an entire system manually, but rather have that configuration limited to only environment-specific secrets.

Yep, I have seen and exercised  the dynamic database credential management in Vault (which is very useful).

**Comment by bonifaido** [comment]
@rahmnathan I think I bought this idea, I think putting non-secrets to Vault to make it a configuration single source of truth is a good idea, and in that case, this is absolutely viable. We will implement this.

**Comment by rahmnathan** [comment]
Glad to hear @bonifaido. Thank you for considering it.

**Comment by bonifaido** [comment]
HI @rahmnathan, just to let you know this is already a work-in-progress and is under internal testing. It will be released this week (we will post a blog post about all of the new features added in the second part of the week).

**Comment by rahmnathan** [comment]
@bonifaido Thanks for the update! Glad to hear we'll be able to take advantage of this soon.

**Comment by bonifaido** [comment]
@rahmnathan https://github.com/banzaicloud/bank-vaults/pull/317 has been submitted to resolve this, please feel free to review and share your thoughts, and check if it fits your needs.

**Comment by rahmnathan** [comment]
@bonifaido Based on the sample in the ReadMe, it looks like this is going to cover our use-case. Thanks again! 

One last question related to this, we're using the vault-operator Helm chart. Is there an ETA/way I can be notified when that is updated with this change? If not, I can just keep checking in. Thanks.

**Comment by bonifaido** [comment]
Hi @rahmnathan, you're welcome, feel free to come back with suggestions, and thoughts! You can subscribe to Bank-Vaults releases by pressing the `Watch` drop-down on the GitHub project and subscribe to `Releases-only`.

Anyhow, Bank-Vaults 0.4.8 has been released a few hours earlier, and it contains already this feature! :)

**Comment by rahmnathan** [comment]
@bonifaido Do I still need to wait for a new vault-operator Helm chart, or is there a way for me to take advantage of that with an existing operator deployment?

**Comment by bonifaido** [comment]
The current helm chart versuon in this repository contains the feature, however you can update the operator image version also in your current deployment.

**Comment by rahmnathan** [comment]
Thanks @bonifaido I'm hoping to get to this within the next week and will report back with how it goes!
