### ISSUE TITLE
vault image isn't updated on active pod

### ISSUE THREAD

**Issue by szymonpk** [banzaicloud/bank-vaults#287]
**Describe the bug**
Today I was playing with updating vault from 1.0.1 to 1.0.2. I have HA setup with 2 pods, S3 storage and DynamoDB storage. I have changed vault image to 1.0.2, standby pod was redeployed but active is on 1.0.1. After deleting active pod running 1.0.1 image, it is recreated with 1.0.2 image.

**To Reproduce**
1. Setup vault with image 1.0.1 and HA (2 pods)
2. Verify if both pods are running 1.0.1
3. Change image version in CRD to 1.0.2 and deploy
4. Standby pod is redeployed to 1.0.2, active stays on 1.0.1.

**Expected behavior**
Both pods should be running 1.0.2.

**Additional context**
bank-vaults 0.4.4

**Comment by bonifaido** [comment]
HI @szymonpk, could you please check if the following attribute is enabled in your CRD?

```yaml
  # This option gives us the option to workaround current StatefulSet limitations around updates
  # See: https://github.com/kubernetes/kubernetes/issues/67250
  # By default it is false.
  supportUpgrade: true
```

**Comment by szymonpk** [comment]
It isn't, I will enable this. Sorry for redundant issue!

**Comment by szymonpk** [comment]
Maybe you should make it true by default? Are there any drawbacks of this?

**Comment by bonifaido** [comment]
No, currently there aren't any drawback, we can make this default :)

**Comment by szymonpk** [comment]
I think we can close this ticket, since fix is in the place. I haven't tried it yet, but I trust you guys ;-)

**Comment by bonifaido** [comment]
Thanks @szymonpk :)

I have submitted https://github.com/banzaicloud/bank-vaults/issues/288 to make this behavior the default.
