### ISSUE TITLE
Document method for exporting audit logs

### ISSUE THREAD

**Issue by aaron-grewell** [banzaicloud/bank-vaults#290]
**Is your feature request related to a problem? Please describe.**
I've implemented bank-vaults in a test environment and it does most of what I need to run Vault but exporting the audit logs to e.g. S3 is a challenge.  I found a reference to a built-in fluentd sidecar but setting FluentDEnabled: true in the spec didn't seem to have any effect (I didn't find a fluentd container in my pod afterward) nor was it clear how I could configure fluentd.

**Describe the solution you'd like**
I'd like to see audit logging covered as a topic in the documentation including at least one tested method of exporting audit logs from the pod.

**Comment by bonifaido** [comment]
Hi @aaron-grewell, yes there is no documentation about it, we need work out docs for this. I will create a logging setup example and write some docs in the following days.

**Comment by matyix** [comment]
@aaron-grewell please check the docs now and let us know if it's enough for you to export the audit logs. Sorry for the slight delay, we've been busy meeting a release schedule.

**Comment by aaron-grewell** [comment]
Thank you! I will check it out.

**Comment by k4kratik** [comment]
Minor new update : https://github.com/banzaicloud/bank-vaults/pull/1662
