### ISSUE TITLE
hello-secrets example failing with PodInitializing error

### ISSUE THREAD

**Issue by Johnch9** [banzaicloud/bank-vaults#295]
**Describe the bug**
Deployment of example webhook fails in initialization.  

**To Reproduce**
AZ cluster with rbac, operator and cr-azure deployed.  Vault is accessible and running and the example secret was successfully written to the vault
helm upgrade --install wmwh banzaicloud-stable/vault-secrets-webhook

**Expected behavior**
Application to start up with injected secret

**Additional context**
Error from the hello-secrets pod logs is:
Error from server (BadRequest): container "alpine" in pod "hello-secrets-75f85977d8-798j9" is waiting to start: PodInitializing
webhook appears to have an entry relating to the secret, but there are no errors in the webhook log(see attached)
rs output and vswh log entry are attached

Environment Variables:
      AWS_SECRET_ACCESS_KEY:         vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
      KUBERNETES_PORT_443_TCP_ADDR:  vaultazclu-vaultazrg-595bd1-86ee0241.hcp.westeurope.azmk8s.io
      KUBERNETES_PORT:               tcp://vaultazclu-vaultazrg-595bd1-86ee0241.hcp.westeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://vaultazclu-vaultazrg-595bd1-86ee0241.hcp.westeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       vaultazclu-vaultazrg-595bd1-86ee0241.hcp.westeurope.azmk8s.io
      VAULT_ADDR:                    https://vault:8200
      VAULT_SKIP_VERIFY:             true
      VAULT_PATH:                    kubernetes
      VAULT_ROLE:                    default

[vswh-log.txt](https://github.com/banzaicloud/bank-vaults/files/2775511/vswh-log.txt)
[rs-log.txt](https://github.com/banzaicloud/bank-vaults/files/2775513/rs-log.txt)

**Comment by Johnch9** [comment]
Hi @bonifaido,

Secret name was the problem I had secret/accounts/aws, plus I've learnt something new, I didn't know about the init-ubuntu log.  Sorry to waste your time.  

Thanks,

John

BTW Does the tutorial (https://banzaicloud.com/blog/inject-secrets-into-pods-vault/) need updating?  That still has: vault kv put secret/accounts/aws AWS_SECRET_ACCESS_KEY=s3cr3t

**Comment by bonifaido** [comment]
No problem, I'm glad it did work out.

`vault kv put` detects if the KV secret engine is version 2, and inserts the `/data/` part automagically.
