### ISSUE TITLE
AWS secret backend incorrectly requiring name field

### ISSUE THREAD

**Issue by gregdurham** [banzaicloud/bank-vaults#300]
**Describe the bug**
When configuring the AWS secret engine type, bank-vaults is expecting that the secret engine contain a 'name' field. Based on the API docs in vault, this is not necessary for this secret backend.

**To Reproduce**
Configure a secret backend for aws, provide configuration, but do not set a name in the config block, receive error: `error configuring vault: error configuring secret engines for vault: error finding sub config data name for secret engine`

I believe that aws needs to be added to this list: https://github.com/banzaicloud/bank-vaults/blob/3917638e7a719a3eddafe9ff9e9ff68fc08aa47b/pkg/vault/operator_client.go#L41

If that is the case, I am happy to resolve. Thanks!

**Comment by bonifaido** [comment]
I think this should resolve the issue, I'm glad if you would submit a a fix for this! :)

**Comment by bonifaido** [comment]
Any update on this @gregdurham? Is this still causing an issue for you, or you have managed to workaround it?

**Comment by gregdurham** [comment]
Hello @bonifaido I was able to work around it by setting the name to root, here is an example sanitized version of what i am using in my configuration: 
`  - path: aws
    type: aws
    description: aws backend for testing
    configuration:
        config: 
          - name: root
            access_key: ACCESSKEY
            secret_key: SECRETKEY
            region: REGION
        roles: 
          - credential_type: iam_user
            policy_arns: arn of policy
            name: my-aws-role`

I have come across a few more bugs, mainly related to kubernetes authentication, that I will raise as well. would you like another ticket for those?

**Comment by bonifaido** [comment]
Great, yes please open up a new one for those.

**Comment by bonifaido** [comment]
Any updates on this @gregdurham ?

**Comment by gregdurham** [comment]
https://github.com/banzaicloud/bank-vaults/issues/332
