### ISSUE TITLE
vault-secrets-webhook: vault agent based authentication

### ISSUE THREAD

**Issue by devlounge** [banzaicloud/bank-vaults#302]
In the vault-secrets-webhook source code, I can multiple lines triggering more or less actions if "useAgent" is set in the config.

However, these specific lines bellow confuse me a lot because "banzaicloud/vault-secrets-init" image does not exist on dockerhub.

```
if vaultConfig.useAgent {
		containers = append(containers, corev1.Container{
			Name:            "vault-agent",
			Image:           "banzaicloud/vault-secrets-init:latest",


```

Moreover, the tag is hardcoded to latest, which is a bad practice in general.

**Comment by bonifaido** [comment]
Hi @devlounge,

Thanks for reporting this.

sorry for the confusion, this feature is more or less an undocumented (unfinished) and at least unadvertised feature of the webhook, which is still a work in progress, and during the implementation of the webhook some parts of this code just remained in the master codebase. This feature is here for using the vault-agent for acquiring a Vault token for the webhook, so a lot of other auth engines will be supported with the help of this already existing piece of software.

If you don't mind I would hijack this issue to not to forget to implementing this.

**Comment by ivan046** [comment]
Hello! Any news about implementing Vault Agent Auto-Auth for vault-env tool? or There is still kubernetes account way only?
