### ISSUE TITLE
Unsealing KMS region fallback support

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#316]
https://www.reddit.com/r/kubernetes/comments/amdexi/running_vault_on_kubernetes_k8s_operator_cli/eflzc1t/

**Comment by raoofm** [comment]
<img width="645" alt="screen shot 2019-02-27 at 11 33 02 am" src="https://user-images.githubusercontent.com/12846989/53506338-c7e04000-3a83-11e9-8258-a4a2b091f1b6.png">

**Comment by raoofm** [comment]
I think this is a very good use-case. I came across this as I'm planning to start a discussion or write up on making vault ha, across dc, with either replication or other options. I have a few things in mind that I'll document soon and share.

I'll limit the discussion to the title and will open another one if needed.

kms is just one thing and then storageBackend. If we think about federated multi cluster then backend sharing or just crr. Also a use-case of using same bucket for unsealKeys and data.

Also decision has to be made regarding https://github.com/banzaicloud/bank-vaults/issues/228. Whether it would work with kiam|kube2iam?

**Comment by KealanM** [comment]
Ooohhhh I like this
