### ISSUE TITLE
failure with no vault/tls/ca after vault-operator and vault restart

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#318]
**Describe the bug**
failure with no vault/tls/ca after vault-operator and vault restart
```
time="2019-02-06T19:35:13Z" level=fatal msg="error connecting to vault: error encountered setting up default configuration: Error loading CA File: open /vault/tls/ca.crt: no such file or directory"
```

Where is the ca stored? I know it is stored as a secret vault-tls but I mean anywhere else.

What should we do in case it accidently gets deleted?

**Comment by raoofm** [comment]
Shouldn't it be regenerated if not found instead of failure

**Comment by raoofm** [comment]
@bonifaido ?

**Comment by bonifaido** [comment]
It's stored in a secret yes, if you have deleted the secret there is no automatic way to put it back, however it could be implemented. Right now you have to roll a cert manually if you deleted it (I suggest backing up the cluster with something like ark). The second option is to create a new Vault instance of course.

So this happened after the tls secret was edited/deleted?

**Comment by raoofm** [comment]
@bonifaido i added a tls secret for UI and chose a name vault-tls. I wasn't aware that it was already used by vault-operator

**Comment by bonifaido** [comment]
I think we can implement this feature in the operator, if the TLS secret is not present in the place we can create a new one, but if it is there we don't overwrite it (otherwise other things will break, like the UI in this case).

**Comment by bonifaido** [comment]
@raoofm I have pushed https://github.com/banzaicloud/bank-vaults/pull/319 to resolve your issue.

**Comment by raoofm** [comment]
@bonifaido thanks
