### ISSUE TITLE
vault-operator when scaled to 2 then the deployment shows as failed as the second one is not ready yet

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#320]
**Describe the bug**
if vault-operator is scaled to 2 then the deployment shows as failed as the second one is not ready yet.

**To Reproduce**
1. Set replicatSet of vault-operator to 2

**Expected behavior**
Deployment/pod shouldn't be in a failed state based on readiness probe.

**Additional context**
Not sure if this is desired as the service will start using the pod if it is ready. So I'm not sure if traffic should be redirected to the leader. Haven't thought about it yet, just opened the issue for discussion.

**Comment by raoofm** [comment]
'''
{"level":"info","ts":1549566350.3663473,"logger":"cmd","msg":"Go Version: go1.11.5"}
{"level":"info","ts":1549566350.3664887,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1549566350.3665276,"logger":"cmd","msg":"operator-sdk Version: v0.4.0"}
{"level":"info","ts":1549566350.3665655,"logger":"cmd","msg":"Watched namespace: security"}
{"level":"info","ts":1549566350.3671248,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1549566350.6689878,"logger":"leader","msg":"Found existing lock","LockOwner":"vault-operator-6cc8b98c6b-mmm9m"}
{"level":"info","ts":1549566350.678125,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1549566351.8602014,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1549566354.243492,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1549566358.806364,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1549566367.519189,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1549566384.8929217,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1549566403.1168368,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1549566419.340862,"logger":"leader","msg":"Not the leader. Waiting."}
'''

**Comment by bonifaido** [comment]
Thanks @raoofm, this has been fixed in #322.

**Comment by raoofm** [comment]
@bonifaido awesome, works

**Comment by bonifaido** [comment]
Great!
