### ISSUE TITLE
Pass custom certs to vault to enable end to end encryption say for PCI compliance

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#321]
**Is your feature request related to a problem? Please describe.**
Pass custom certs to vault to enable end to end encryption say for PCI compliance

**Comment by bonifaido** [comment]
This is totally possible right now, you have to create your secret with `"the name of the CRD"-tls` (e.g.: `vault-tls`), and put in the certificate the same way as the operator creates.

**Comment by raoofm** [comment]
@bonifaido thanks

**Comment by raoofm** [comment]
@bonifaido seems this isn't working as intended. I used cert-manager to generate a secret vault-tls  but vault complains to start up with logs

```
Using eth0 for VAULT_CLUSTER_ADDR: https://1xx.xxx.xxx.7:8201
telemetry.disable_hostname has been set to false. Recommended setting is true for Prometheus to avoid poorly named metrics.
Error initializing listener of type tcp: error loading TLS cert: open /vault/tls/server.crt: no such file or directory
```

**Comment by raoofm** [comment]
@bonifaido ok figured out that actually I could mount the volumes using the vault CR.

The problem is now that the configurator is looking for ca.crt

```
time="2019-04-01T20:44:42Z" level=fatal msg="error connecting to vault: error encountered setting up default configuration: Error loading CA File: open /vault/tls/ca.crt: no such file or directory"
```

the issue is here 
https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/controller/vault/vault_controller.go#L1042

**Comment by primeroz** [comment]
@raoofm if it helps i am doing the same by using 2 listeners and custom ports as described [here](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-customports.yaml)

I am letting vault operator manage the internal cert , which is useful for the configurator to connect and so on, and am managing an extra listener using cert-manager 

on that listener i have an haproxy ingress with ssl-passthrough

**Comment by raoofm** [comment]
yeah 2 listeners approach works. It worked for @jurgenweber too.

I'm ok if owners of this repo (@bonifaido) thinks its ok to not support that and not reopen this issue.

**Comment by matyix** [comment]
Supporting this as @primeroz kindly described above (2 listeners and custom ports) is the intended way, it’s OK for us, we can keep this closed.

**Comment by raoofm** [comment]
@matyix fair enough, thanks
