### ISSUE TITLE
Disable etcd persistence at install time.

### ISSUE THREAD

**Issue by rahmnathan** [banzaicloud/bank-vaults#324]
In a previous issue I had asked to make etcd persistent so that it could be used without worrying about data loss in the event of an outage in our cluster (thanks for implementing this so quickly, by the way). The problem I have now is not all of our Kube clusters have persistent volume provisioning, so I can't install this there anymore. Is there a way to disable etcd persistence during install? Again, I'm really glad the feature exists, but certain environments we're trying to deploy don't currently support this functionality. 

If this isn't possible, I can try to revert to an older version for the time-being. Thanks

**Comment by bonifaido** [comment]
Hi @rahmnathan, you can specify the size of the volume to 0, so this will be disabled, but a better solution will be coming in #325, so you just don't have to specify the `etcdPVCSpec` at all! :)

**Comment by rahmnathan** [comment]
Thanks @bonifaido! I pulled in the latest 'master' images of vault-operator and bank-vaults and my issue appears to be resolved. As always, I appreciate the quick fix!

**Comment by bonifaido** [comment]
Very welcome @rahmnathan, keep posting! :)
