### ISSUE TITLE
Bank-Vaults configure should support multiple configuration files and directories

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#330]
See https://github.com/banzaicloud/bank-vaults/issues/323 for more details.

**Comment by primeroz** [comment]
Is there an example on how to use this feature when running the operator ?

**Comment by bonifaido** [comment]
Hi @primeroz, sorry there is no specific docs for this, but there is a sample ConfigMap that can be added as an external config: https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/config.yaml
