### ISSUE TITLE
Vault-webhook hooking kube-system apps

### ISSUE THREAD

**Issue by bruhsb** [banzaicloud/bank-vaults#337]
Hi, after one week using vault-secrets-webhook in our cluster, today we face a interesting problem:

We use GKE with some preemptive nodes and today we woke up with some tube-system pods in CrashLoopBack state, example: **kube-dns** and **fluentd**.
Analyzing logs we saw that even these pods are being modified by **MutatorWebhook** and they are trying to access Vault with an **127.0.0.1** URL (because the didn't have the annotation).

Question is: This is planned as this?
Every time I create a new node and ingress it in the cluster some pods who doesn't use the vault web hook are breaking

```(⎈ |staging:kube-system)➜  ~ kubectl logs fluentd-gcp-v3.2.0-pwmnm -c fluentd-gcp
2019/02/21 16:57:15 Failed to request new Vault token Put https://127.0.0.1:8200/v1/auth/kubernetes/login: dial tcp 127.0.0.1:8200: connect: connection refused
2019/02/21 16:57:20 Failed to request new Vault token Put https://127.0.0.1:8200/v1/auth/kubernetes/login: dial tcp 127.0.0.1:8200: connect: connection refused

**Comment by bonifaido** [comment]
Hi @bruhsb, no this is absolutely not planned, could you please describe the version of the mutating-webhook and also how the env block of your pods look like?

**Comment by bruhsb** [comment]
Hey @bonifaido, we're using "vault-secrets-webhook-0.3.4" helm chart

This bellow is the mutated env spec of our fluentd pod (they're managed by GKE) and the original pod doesn't even has vault envs
```
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: VAULT_ADDR
    - name: VAULT_SKIP_VERIFY
    - name: VAULT_PATH
      value: kubernetes
    - name: VAULT_ROLE
      value: default
``

**Comment by bonifaido** [comment]
And what the image version inside the chart deployment?

**Comment by bruhsb** [comment]
@bonifaido we're using the value default of chart, "latest". Now looking in the dockerhub we saw that yesterday was released a 0.4.9 version. We staticly rollbacked to 0.4.8 version from 13 days ago and the problem was solved.

Any crucial modifications in the version from yesterday?

**Comment by bonifaido** [comment]
Yes, this was refactored, please use the previous version than, and let's keep this issue open for the bug fix! Thank you for reporting this!

**Comment by bonifaido** [comment]
https://github.com/banzaicloud/bank-vaults/pull/338 has been pushed to handle this issue!
