### ISSUE TITLE
[vault-env] clean up the environment #feature

### ISSUE THREAD

**Issue by dennybaa** [banzaicloud/bank-vaults#341]
Just tried `vault-env` in a raw mode without Kubernetes, i.e. I set `VAULT_{ADDR,TOKEN}`. What seems strange to me that these guys are not wiped, I do understand that this should be one-time use token with TTL... But is there any consideration why this is not done?

**Comment by bonifaido** [comment]
Hi Denis, no this is not intentional, they are just not cleared. Are you willing to open up a PR for this?

**Comment by dennybaa** [comment]
Well, maybe, since I have got almost no golang experience. Though should be trivial, I'll ping you back later this week if I succeed or don't.

**Comment by bonifaido** [comment]
No worries, happy to help.
