### ISSUE TITLE
Submit bank-vaults to https://www.operatorhub.io ?

### ISSUE THREAD

**Issue by alantang888** [banzaicloud/bank-vaults#344]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Submit bank-vaults to https://www.operatorhub.io ? 

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by matyix** [comment]
We've been looking into this for Bank-Vaults and the other operators we made - are you using any other operators with OLM, or plan to use it with BV? If so, what is your experience of OLM?

**Comment by alantang888** [comment]
Sorry, not understand what is OLM...

**Comment by matyix** [comment]
It's the [Operator Lifecycle Manager](https://github.com/operator-framework/operator-lifecycle-manager). Besides being listed what is the value you are looking to extract from the https://www.operatorhub.io ?

**Comment by alantang888** [comment]
Seriously, I don't have experience of using OLM. But we looking for something like it help use to manage our operators. Sure we have some concern with version upgrade cause broken change.

Since BV also using `operator-sdk`. Then I think BV listed on operator hub maybe a good idea.

**Comment by bonifaido** [comment]
PR submitted: https://github.com/operator-framework/community-operators/pull/161

**Comment by bonifaido** [comment]
Fixed already: https://operatorhub.io/operator/beta/vaultoperator.v0.4.10
