### ISSUE TITLE
[Operator] Support annotations for all operator created resources

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#357]
Currently, only the Etcd Ingress and Pod resources are configurable with annotations. The TLS Secrets and ConfigMaps and Services should be also annotable.

**Comment by primeroz** [comment]
Ideally also the statefulset created , this would have been useful to use "https://github.com/stakater/Reloader" to reload the stateful set on letsencrypt cert change. 

To be honest this will not matter when https://github.com/banzaicloud/bank-vaults/issues/380 is done

**Comment by dbason** [comment]
To add to this it would also be useful set etcd pod annotations (for example using velero/restric for etcd backups) via https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#custom-pod-annotations
