### ISSUE TITLE
Publish a Prometheus Metric for the outcome of bank-vaults configure

### ISSUE THREAD

**Issue by primeroz** [banzaicloud/bank-vaults#362]
**Describe the solution you'd like**
bank-vaults configure will , at the moment, only report an issue in applying the policies to the logs. 
In a GitOps driven scenario where the policies are updated and pulled by the cluster we need to know if the last run of bank-vaults configure was successful and the number of policies that were applied. 

Exposing a prometheus metric would make this information useful for alerting and graphing purposes

Would be great to also report the status in the "vault" object

**Describe alternatives you've considered**
Alerting by parsing logs

**Comment by bonifaido** [comment]
Fixed by: https://github.com/banzaicloud/bank-vaults/pull/379
