### ISSUE TITLE
Discussion: merge vault-configurer/vault-sidecar-unsealer with vault-operator

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#363]
**Is your feature request related to a problem? Please describe.**
Wondering if we really need to have operator/configurer/unsealer as operator can actually do all 3. 

**Describe the solution you'd like**
Operator does what a human operator would do in an automated way. I would think operator can do all the work it doesn't have to be a separate pod/container for each of these tasks. If there is a good reason to keep it that way then it is fine. I just wanted to understand/check on the design

**Comment by bonifaido** [comment]
Hi @raoofm, this is because bank-vaults can be used as a CLI tool and we don't want to repeat the same code in the operator, the other issue is that if all Vault instances would be handled by the same Pod (the operator) it would be hard to give proper access resolution, since in this setup all Vaults would be controlled by one instance (unseal, root token...).

**Comment by dmesser** [comment]
@bonifaido To add to the list of pros: the permission handling for the Vault Operator obtained through https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/vault would be more effective with Operator Lifecycle Manager if there would be a single Operator.
Currently OLM cannot deploy bank vault in a way where it watches all namespaces, as it creates the service account `vault` in the namespace where the operator is deployed, not where the CR is instantiated.

**Comment by raoofm** [comment]
> this is because bank-vaults can be used as a CLI tool and we don't want to repeat the same code in the operator

can be reused not repeated.



> if all Vault instances would be handled by the same Pod (the operator) it would be hard to give proper access resolution, since in this setup all Vaults would be controlled by one instance (unseal, root token...).

May be makes sense as sidecar simplifies for unseal/init (though an operator can still do it) but configurer seems like a fit for operator - no?

**Comment by raoofm** [comment]
@bonifaido feel free to close it if merging configurer to operator doesn't make sense.

**Comment by bonifaido** [comment]
No, currently there are no plans to do that but I would keep this issue open for future reconciliation.
