### ISSUE TITLE
vault-configurator can get stuck with HA Setup 

### ISSUE THREAD

**Issue by primeroz** [banzaicloud/bank-vaults#365]
**Describe the bug**
Vault Configurator is designed to contact the SVC endpoint and check if the node is connected to is the active one before proceeding with the configuration.

```
time="2019-03-20T16:35:28Z" level=info msg="checking if vault is sealed..."
time="2019-03-20T16:35:28Z" level=info msg="checking if vault is active..."
time="2019-03-20T16:35:29Z" level=error msg="error checking if vault is active: error unexpected status code: 429, waiting 5s before trying again..."   
```

In an HA setup the SVC now ( starting with 0.4.13 ) contains all vault nodes so is possible for the vault-configurator to select the Standby node through Kubernetes service loadbalancing and due to conntrack it will keep connecting to that pod every 5 seconds when it retries without ever exiting from this loop

**To Reproduce**
start a vault HA of 2 nodes with operator >= 0.4.13 
you have 50% change that the configurer will hit the standby node. if it does it will get stuck

**Expected behavior**
the configurer should just configure the standby node since , afaik, the configuration will be forwarded to the active vault node 

alternatively it should fetch the active leader from the vault operator object and contact that node directly

**Additional context**
operator version: 0.4.13 
bank_vaults version: 0.4.13

**Comment by bonifaido** [comment]
Submitted https://github.com/banzaicloud/bank-vaults/pull/366 to fix this issue.
