### ISSUE TITLE
Cross Account does not get provisioned by Vault Configurer

### ISSUE THREAD

**Issue by AniGarikipati** [banzaicloud/bank-vaults#371]
**Describe the bug**
Vault Cross Account role does not get configured with error. This feature worked in previous versions of Vault.

**To Reproduce**
Deploy Vault with the Custom Resource including crossaccountrole key. 
Vault configurer erros out and does not provision secret engine.
crossaccountrole:
        - sts_account: {{sts_account}}
          sts_role: {{sts_role}}

**Expected behavior**
Cross Account role should be provisioned

**Logs**
kubectl logs vault-configurer-555956b9bb-h4t6s 
time="2019-03-25T19:12:03Z" level=info msg="New config file change /config/vault-configurer/vault-config.yml"
time="2019-03-25T19:12:03Z" level=info msg="checking if vault is sealed..."
time="2019-03-25T19:12:07Z" level=error msg="error checking if vault is sealed: error checking status: Get https://vault.secrets:8200/v1/sys/seal-status: dial tcp: lookup vault.secrets on 172.20.0.10:53: no such host, waiting 30s before trying again..."
time="2019-03-25T19:12:37Z" level=info msg="checking if vault is sealed..."
time="2019-03-25T19:14:11Z" level=error msg="error checking if vault is sealed: error checking status: Get https://vault.secrets:8200/v1/sys/seal-status: dial tcp 172.20.187.32:8200: i/o timeout, waiting 30s before trying again..."
time="2019-03-25T19:14:41Z" level=info msg="checking if vault is sealed..."
time="2019-03-25T19:14:41Z" level=info msg="vault is unsealed, configuring..."
time="2019-03-25T19:14:42Z" level=error msg="error configuring vault: error configuring auth methods for vault: error configuring aws auth cross account roles for vault: error putting %!s(int=<account_id>) cross account aws role into vault: Error making API request.\n\nURL: PUT https://vault.secrets:8200/v1/auth/aws/config/sts/%21s%!i(MISSING)nt=<account_id>%!\n(MISSING)Code: 404. Errors:\n\n* 1 error occurred:\n\t* unsupported path\n\n"

**Bank Vaults Versions**
Vault Version: 0.11.6
Bank Vaults Version: 0.4.14

PR that enabled this functionality.
#140

**Comment by bonifaido** [comment]
@AniGarikipati I think the issue here is that the `Sprintf` formatting expects a `string` (`"auth/%s/config/sts/%s"`) but your `sts_account` is an `int`, as seen from `%!s(int=<account_id>)`. Could you please make it a `string` by putting it between quotes? I will push a fix for this in the meantime to transform it to a string always in the code.
