### ISSUE TITLE
RBAC permissions of webhook in chart allow access to everything

### ISSUE THREAD

**Issue by annismckenzie** [banzaicloud/bank-vaults#375]
**Describe the bug**
The RBAC permissions that are defined for the webhook in https://github.com/banzaicloud/banzai-charts/blob/master/vault-secrets-webhook/templates/webhook-rbac.yaml use the cluster role `cluster-admin` which I think is dangerous and unnecessary.

**Additional context**
Looking through the code of the mutating webhook all it currently needs is a `get` of secrets and config maps in all namespaces and, optionally if using the vault agent, `create` and `update` of config maps.

What do you think?

**Comment by bonifaido** [comment]
Hi @annismckenzie, I absolutely agree, if it can be made more "lightweight" in terms of permissions let's do it. Do you plan to submit a PR on this? I would be happy to review it.

**Comment by annismckenzie** [comment]
We'll try this in our own cluster and then send a PR – thanks for the quick response. One question though: reading through the docs at https://kubernetes.io/docs/reference/access-authn-authz/rbac/ there's this:
> You cannot modify which Role or ClusterRole a binding object refers to. Attempts to change the roleRef field of a binding object will result in a validation error. To change the roleRef field on an existing binding object, the binding object must be deleted and recreated.
Won't that happen in this case? We haven't used Helm yet (we use kustomize), maybe you know how it deals with these situations?

**Comment by bonifaido** [comment]
Yeah, this is an issue, thanks for the detailed analysis! 👍 
What we can do is to rename the `ClusterRoleBinding` which is currently `{{ template "vault-secrets-webhook.fullname" . }}` we can change it to `{{ template "vault-secrets-webhook.fullname" . }}-something` where something is the name of the role.

**Comment by annismckenzie** [comment]
Yeah, that's one way to do it but that won't clean up the existing one.

**Comment by bonifaido** [comment]
It will. Helm deletes resources that are not present in the current release.

**Comment by annismckenzie** [comment]
My colleague just opened a PR. The webhook is currently happily running using these RBAC rules in one of our clusters.

**Comment by bonifaido** [comment]
Hi @annismckenzie, thanks we have just checked the limited RBAC PR, it seems to be running fine, thank you!
