### ISSUE TITLE
Have the operator watch an externally managed Secret and reload vault when it change

### ISSUE THREAD

**Issue by primeroz** [banzaicloud/bank-vaults#380]
**Is your feature request related to a problem? Please describe.**
Thanks to the multiple listener support , [this config](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-customports.yaml) is now easy to have an external endpoint use letsencrypt certificate for e2e encryption

Those certs are renewed frequently and when that happen Vault need to restarted to pick up the change ( In the future we could signal HUP vault but that will require pid sharing namespace to be widely available )

**Describe the solution you'd like**
Have the operator watch the secret created by "cert-manager" , or any other way really, and trigger a reload of the vault statefulset when it change.

It could even just look for any secret matching a set of labels, similar to how configs are managed.

**Describe alternatives you've considered**
I am gonna try run "https://github.com/stakater/Reloader" to achieve the same behavior

**Comment by primeroz** [comment]
Unfortunately using "Reloader" is not feasible due to the annotations not propagating to the statefulset itself 

see https://github.com/banzaicloud/bank-vaults/issues/357

**Comment by bonifaido** [comment]
This annotation feature is no big deal I think, if this is the only blocker :)

**Comment by bonifaido** [comment]
My only concern is adding another deployment/pod into the mix (the Reloader). I think the operator could manage this. What do we mean by restarting? Deleting the pod? (That would be easy and more secure IMHO). Or exec-ing into the pod to send a signal?

**Comment by primeroz** [comment]
Yeah sorry , i was going to run the "reloader" on my own while waiting for this to be implemented.
The reason why i added the comment is that i mentioned the "reloader" as the alternatives i've considered when opening the bug.

I think the operator should just trigger a roll-restart of the statefulset set . 

Looking at how reloader is doing it ( https://github.com/stakater/Reloader/blob/master/internal/pkg/callbacks/rolling_upgrade.go#L109) with my limited knowledge of go and kubernetes api , it seem they are just hitting an Update on the statefulset resource ? 

If i was going to do it with kubectl and manifests i would just use an annotation with a checksum of the secrets and update that to let kubernetes trigger a roll restart 

Regardless i would just let kubernetes statefulset deal with the roll restart 

I would only do the SIGHUP to vault using a sidecar container  , but since that requires the PID SHARED NAMESPACE which is still Beta in 1.14 i doubt is a good idea right now
