### ISSUE TITLE
vault 1.1.0 no longer required statsd exporter

### ISSUE THREAD

**Issue by jurgenweber** [banzaicloud/bank-vaults#382]
**Is your feature request related to a problem? Please describe.**
in vault 1.1.0 a prometheus scrape endpoint has been introduced.
https://github.com/hashicorp/vault/blob/master/website/source/docs/configuration/telemetry.html.md#prometheus

**Describe the solution you'd like**
Add the ability to disable the side car (to maintain backwards compaitibility) in favour of the native support.

**Comment by matyix** [comment]
We will keep this option as well - makes no harm, someone might still prefer this - but behind a flag.

**Comment by primeroz** [comment]
Let's keep the statsd optional please. 

At least for now is much easier for me to get a monitoring setup out of the box without having to sort out tokens for prometheus.

**Comment by bonifaido** [comment]
I absolutely agree Prometheus setup with the token is harder currently.
