### ISSUE TITLE
Can't Init vault anymore when using Google KMS and GCP starting with 0.4.15-rc.4

### ISSUE THREAD

**Issue by primeroz** [banzaicloud/bank-vaults#400]
**Describe the bug**
Init of a new vault fail when using Google Storage and Google KMS starting with 0.4.15-rc.4

This works flawlessly on rc.3

**To Reproduce**
1. Create a google storage KMS Backed vault from scratch with 0.4.15-rc.5 ( or 4) 
1. Watch it fail

**Expected behavior**
Vault is initalized . vaut-root and unseal keys are encrypted and uploaded

**Screenshots**
```
vault-0 bank-vaults time="2019-04-02T16:01:34Z" level=info msg="initializing vault"
vault-0 vault 2019-04-02T16:01:37.186Z [INFO]  core: security barrier not initialized
vault-0 vault 2019-04-02T16:01:38.114Z [INFO]  core: security barrier initialized: shares=5 threshold=3
vault-1 vault 2019-04-02T16:01:38.648Z [ERROR] core: error checking health: error="core: barrier reports initialized but no seal configuration found"
vault-0 vault 2019-04-02T16:01:39.364Z [INFO]  core: post-unseal setup starting
vault-1 bank-vaults time="2019-04-02T16:01:39Z" level=fatal msg="error initializing vault: error initializing vault: Error making API request.\n\nURL: PUT https:
//127.0.0.1:8200/v1/sys/init\nCode: 400. Errors:\n\n* Vault is already initialized"
vault-0 vault 2019-04-02T16:01:39.924Z [INFO]  core: loaded wrapping token key
vault-0 vault 2019-04-02T16:01:39.924Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
vault-0 vault 2019-04-02T16:01:40.354Z [INFO]  core: no mounts; adding default mount table
vault-0 vault 2019-04-02T16:01:40.983Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
vault-0 vault 2019-04-02T16:01:40.984Z [INFO]  core: successfully mounted backend: type=system path=sys/
vault-0 vault 2019-04-02T16:01:40.984Z [INFO]  core: successfully mounted backend: type=identity path=identity/
vault-0 vault 2019-04-02T16:01:44.770Z [INFO]  core: successfully enabled credential backend: type=token path=token/
vault-0 vault 2019-04-02T16:01:44.771Z [INFO]  core: restoring leases
vault-0 vault 2019-04-02T16:01:44.771Z [INFO]  rollback: starting rollback manager
vault-0 vault 2019-04-02T16:01:44.934Z [INFO]  expiration: lease restore complete
vault-0 vault 2019-04-02T16:01:46.036Z [INFO]  identity: entities restored
vault-0 vault 2019-04-02T16:01:46.217Z [INFO]  identity: groups restored
vault-0 vault 2019-04-02T16:01:46.441Z [INFO]  core: post-unseal setup complete
vault-0 vault 2019-04-02T16:01:47.650Z [INFO]  core: root token generated
vault-0 vault 2019-04-02T16:01:47.650Z [INFO]  core: pre-seal teardown starting
vault-0 vault 2019-04-02T16:01:47.650Z [INFO]  rollback: stopping rollback manager
vault-0 vault 2019-04-02T16:01:47.650Z [INFO]  core: pre-seal teardown complete
vault-0 bank-vaults time="2019-04-02T16:01:47Z" level=fatal msg="error initializing vault: error initializing vault: Error making API request.\n\nURL: PUT https:
//127.0.0.1:8200/v1/sys/init\nCode: 400. Errors:\n\n* Vault is already initialized"
```

after that is just 

`bank-vaultsvault-0 vault-0 time="2019-04-02T16:02:36Z" level=error msg="error unsealing vault: unable to get key 'vault-unseal-0': error getting object for key '`
look like the unseal and root objects were not uploaded to the bucket

**Additional context**
I can see a new file "vault-test" uploaded in the bucket 

this must be related to https://github.com/banzaicloud/bank-vaults/commit/d30007215b57d5d59d27eb50591d01cf67a33cd5 
which it seems implemented that test file in the first place, at least for Google KMS 

I can't see any `error testing keystore before init: %s` though which if that TEST failed would upload

**Comment by bonifaido** [comment]
Hi @primeroz, yes an additional `vault-test` is now placed to the bucket because people had issues initializing Vault without the correct cloud storage privileges, so in this case, if the test fails you won't be ending up with an initialized Vault but with not unseal keys.

I have tried this locally for GCP and also for AWS but I didn't have any issues, so the vault-test object is uploaded but the others don't?

**Comment by primeroz** [comment]
yeah i get the vualt-test object but it stops there. 
I also get the "core" and "sys" directory so it seems that the vault got initialized but then next message i get is "error initializing vault" 

Thing is, with rc3 it works flawlessly so somehow this test is what is causing me issues, but as i said before i am not getting the `error testing keystore before init` message in the logs so the test does not seem to be failing at the set here https://github.com/banzaicloud/bank-vaults/blob/d30007215b57d5d59d27eb50591d01cf67a33cd5/pkg/vault/operator_client.go#L203

the next error i get https://github.com/banzaicloud/bank-vaults/blob/d30007215b57d5d59d27eb50591d01cf67a33cd5/pkg/vault/operator_client.go#L235 "error initializing vault" so something went won in those 30 lines for me 

I will do a bit more testing ...

**Comment by primeroz** [comment]
I can reproduce this 100% of times.

1. scratch my gcp bucket
1. start vault with image bank-vaults:0.4.15-rc.3 
1. It all works , the init from https://github.com/banzaicloud/bank-vaults/blob/d30007215b57d5d59d27eb50591d01cf67a33cd5/pkg/vault/operator_client.go#L228 succeds
1. Vault is running
1. Delete vault resource
1. scratch the gcp bucket
1. start vault with image bankg-vaults:0.4.15-rc.5
1. INIT https://github.com/banzaicloud/bank-vaults/blob/d30007215b57d5d59d27eb50591d01cf67a33cd5/pkg/vault/operator_client.go#L228 Fails with error: `msg="error initializing vault: error initializing vault: Error making API request.\n\nURL: PUT https://127.0.0.1:8200/v1/sys/init\nCode: 400. Errors:\n\n* Vault is already initialized"`

I added some debugs as in : 
```
git diff pkg/vault/operator_client.go
diff --git a/pkg/vault/operator_client.go b/pkg/vault/operator_client.go
index 6e8d4e3..672e3ab 100644
--- a/pkg/vault/operator_client.go
+++ b/pkg/vault/operator_client.go
@@ -225,6 +225,8 @@ func (v *vault) Init() error {
                }
        }
 
+       initializedpre, err := v.cl.Sys().InitStatus()
+       logrus.Infof("INITIALIZED PRE: %s", initializedpre)
        resp, err := v.cl.Sys().Init(&api.InitRequest{
                SecretShares:      v.config.SecretShares,
                SecretThreshold:   v.config.SecretThreshold,
```

And i get that the vault is not initialized before the call to `v.cl.Sys().Init(&api.InitRequest{...` is done 

```
time="2019-04-03T09:29:01Z" level=info msg="initializing vault"
time="2019-04-03T09:29:04Z" level=info msg="INITIALIZED PRE: %!s(bool=false)"
time="2019-04-03T09:29:15Z" level=fatal msg="error initializing vault: error initializing vault: Error making API request.\n\nURL: PUT https://127.0.0.1:8200/v1/sys/init\nCode: 400. Errors:\n\n* Vault is already initialized"
```

**Comment by bonifaido** [comment]
Doesn't look like something that is related to the newly introduced Test method. Are you sure that the Vault storage has been cleaned up before starting this procedure?

Anyhow if you think the test is causing an issue, I'm happy to move it behind a feature flag, because it possibly causes issues to AWS users as well: https://github.com/banzaicloud/bank-vaults/issues/396#issuecomment-479389218

**Comment by bonifaido** [comment]
Is this a HA setup?

**Comment by primeroz** [comment]
Yeah the storage has been cleared. It was an HA setup but since the issue i have been testing with a single VAULT instance to make sure no race conditions were happening.

I have build every single commit as an image between 0.4.15-rc.3 and rc.5 with the following process:

1. git checkout <COMMIT>
1. make docker ( with my own image name and version to the commit hash )
1. gsutil -m rm -rf "gs://vault9eacd36a1c0fec82-vault-storage/*" ( clean up the bucket )
1. update image in vault.yaml ( the crd definition )
1. apply the CRD 
1. Delete the vault resource

It broke at the image from this commit https://github.com/banzaicloud/bank-vaults/commit/092839972b27228da80cf0911ea780d8cb2b07a2

**Comment by primeroz** [comment]
So to answer your question no , i don't think anymore it has to do with the test introduced

**Comment by primeroz** [comment]
For reference a pastebin output of the runs with image from https://github.com/banzaicloud/bank-vaults/commit/d30007215b57d5d59d27eb50591d01cf67a33cd5 and from https://github.com/banzaicloud/bank-vaults/commit/092839972b27228da80cf0911ea780d8cb2b07a2

https://paste.debian.net/hidden/149eb45a/

**Comment by primeroz** [comment]
Thanks @bonifaido for spending time with me troubleshooting the issue 

It turned out to be the wrong timeout on the new Timeout introduced here: https://github.com/banzaicloud/bank-vaults/commit/092839972b27228da80cf0911ea780d8cb2b07a2#diff-58fc9f0ca8516cdaffff6903ac2f7407R244

Causing the Retry to happen while vault was still initializing ( at least in my setup) and breaking it

FIXED in https://github.com/banzaicloud/bank-vaults/commit/1dc24601e3f75b8d9dabf243f8fe2b539e2d35ca

**Comment by bonifaido** [comment]
Thanks for the thorough testing here!

**Comment by abdennour** [comment]
this issue happen to me when I delete/redeploy everything, except the namespace.
After investigation, I found that `vault-unseal-keys` secret has not been deleted when I deleted vault-operator, vault-cluster,... etc. 

So to fix the issue, I just delete the secret manually: 
```sh
k -n vault delete secret vault-unseal-keys
```

**Comment by bonifaido** [comment]
Hi @abdennour, yes because the unseal keys live with the data which is controlled by the Vault itself, so the operator shouldn't control it.
