### ISSUE TITLE
Add consul-template support

### ISSUE THREAD

**Issue by jurgenweber** [banzaicloud/bank-vaults#403]
**Current State:**

The current webhook only supports the KV store and KPI for our use case we would need support for the AWS and database secrets backends.

Doing it using Seth Vargo’s method is a lot of work, taking all that manual config and CnPing it everywhere. I have been looking at the code for the webhook (https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-secrets-webhook/main.go, https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-env/main.go) and I want to explain what I have worked out/reverse engineered so I know we are on the same page and then ask some questions. 

the general workflow:
• you look for pods with the right EnVars/ConfigMaps/Secrets with the correct prefix ‘vault:’ or ‘>>vault:’
• you then inject an init container running vault that gets a vault token and copies it into the /vault/ volume
• you inject another init container that copies `vault-env` into the /vault/ volume
• you then inspect every container in the pod, add the required env vars for `vault-env`
• you then concat the container command and args and turn that into the args and make `/vault/vault-env` the command
• you then run /vault/vault-env <original command> <original args>
• `vault-env` parses the env/configmaps/secrets updates the env/configmaps and secrets per the correct strings (value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY)
• `vault-env` then executes the binary (<original command> <oringinal args>)

KV/KPI are only supported because when you make the request to vault you are only handling the returned data for those backends. To support other backends we need to add smarts to handle the returning of passwords and usernames or a data object for that secrets backend.

`vault-env` is only run once when the container starts, meaning only those env/ secrets/configmaps are only manipulated once. This means it does not handle expiring credentials/a TTL on a returned credential because this would mean manipulating the current running containers or triggering a replica set update.

I would like to suggest a new feature of adding `consul-template` as an additive to `vault-env`, not as a replacement but as something that can be used in conjunction to solve a different problem. The difference are:
`vault-env`:
• limited support for secret backends.
• does not support TTL.
• has cool env/secret/config map updating mechanism.
• takes over the live container.
• does not deal with files.

`consul-template`
• supports all backends out of the box with its templating.
• runs as a side car daemon and handles TTL on secrets.
• writes config to a file system (preferably a memory resident one so it disappears on tear down) for the app to pick up.
• can HUP/run a command to tell the process to take the updated config.
• does not deal with env/secrets/config maps.

**Implementation:**
Configuration per pod would be necessary for `consul-template` which can have a large config file, the user would need to maintain a configmap with this configuration which can be referenced via an annotation.

We would require one more annotation:

* ct-configmap (string) = CT_LOCAL_CONFIG.

This should trigger the addition of the `consul-template` sidecar and related environment variables so the env var CT_LOCAL_CONFIG can be populated for `consul-template`.

Depending on version of k8s and what feature gates are enabled, `shareProcessNamespace: true` should be either enabled or disabled (may want an overriding annotation for this?).

You will need to add a volume that dies with the pods for `consul-template` to write to:

```
     volumes:
	     - name: secrets
	       emptyDir: {}
```

If no EnvVars/ConfigMaps/Secrets are found, the init container `copy-vault-env` should not be triggered and all related volumes and volumes mounts should be handled.

Additional configuration for `consul-template` ‘command’ to run when a change has been made will need to be maintained by the user in their deployment. Sane defaults to HUP the main process can be implemented or omitted.

Open for comments or thoughts on how to make it better!

**Comment by marcoreni** [comment]
@jurgenweber Thanks for this implementation! Two quick questions:
1. if I understand correctly, secrets are not injected via InitContainer but only via Sidecar. Therefore, the main application may start without the secrets having been written on the shared volume yet. Have you considered this race condition?
2. Can I mount the volume containing the secrets in a specific path inside my application or is it injected by the webhook in a predefined path?

**Comment by jurgenweber** [comment]
@marcoreni 
1. You do not really need to concern yourself with the race condition, it is mitigated/handled. If your app is up before consul-template has had the opportunity to write your file, your ready/live probes should not be returning true and when consul-template has the opportunity to do it successfully you can also tell it to HUP or communicate with your application somehow to re-read the config. 

2. The volume mount is /vault/secrets... you can make the filename anything you want but that part of the path is hardcoded... We could make this 'settable' if you need it to be.

**Comment by marcoreni** [comment]
@jurgenweber Thanks for your answer. Having the path configurable would be nice, we would be able to inject the environment file directly into the application folders

**Comment by bonifaido** [comment]
https://github.com/banzaicloud/bank-vaults/pull/669
