### ISSUE TITLE
vault-configurer pod failing to parse config

### ISSUE THREAD

**Issue by dtkachenko** [banzaicloud/bank-vaults#406]
**Describe the bug**

**vault-configurer pod failing to execute with standard config** 

**Error message:**

> time="2019-04-04T22:42:55Z" level=fatal msg="error executing vault config template: template: no template \"/config/vault-configurer/vault-config.yml\" associated with template \"vault-config-file\""

**Config(/config/vault-configurer/vault-config.yml):**

```json
{"auth":[{"roles":[{"bound_service_account_names":"default","bound_service_account_namespaces":"default","name":"default","policies":"allow_secrets","ttl":"1h"}],"type":"kubernetes"}],"policies":[{"name":"allow_secrets","rules":"path \"secret/*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"] }"}]}
```

**vault-oprator installed with helm:**
`vault-operator-0.2.8        	0.4.14`

Reproducible with current latest image
> Image:         **banzaicloud/bank-vaults:latest**
> Image ID:      docker-pullable://banzaicloud/bank-vaults@sha256:ddf8d92653c7bde17c3c49afa93d89203119d400016e8c013a30024eb8ab4f4e

Same config working fine with **banzaicloud/bank-vaults:0.4.14** image

**To Reproduce**
1. Install vault-operator-0.2.8 chart with helm with default values
2. Create vault CR with https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-resource.yaml
3. Watch vault-configurer-.. pod with kubectl  get pods
4. See error in kubectl logs 

**Expected behavior**
Vault instance is launched and configured

**Comment by bonifaido** [comment]
Hi @dtkachenko, can you make sure that you have pulled the latest-latest (i.e.: change the imagePullPolicy to always), because according to my machine the digest `ddf8d92653c7bde17c3c49afa93d89203119d400016e8c013a30024eb8ab4f4e` is an older `"latest"` image

```bash
 docker images --digests | grep ddf8d92653c7bde17c3c49afa93d89203119d400016e8c013a30024eb8ab4f4e    (docker-desktop/default)
banzaicloud/bank-vaults                     <none>                sha256:ddf8d92653c7bde17c3c49afa93d89203119d400016e8c013a30024eb8ab4f4e   76d109353cb3        4 weeks ago         61.7MB
```

**Comment by dtkachenko** [comment]
Hi @bonifaido, I will try to verify today.

**Comment by bonifaido** [comment]
Any update on this @dtkachenko ?

**Comment by dtkachenko** [comment]
Hello @bonifaido 
I'm sorry for long response.

I can't reproduce issue with any version of banzaicloud/bank-vaults image.
Looks like problem was in my setup. 
Could you please close Issue?

**Comment by bonifaido** [comment]
Thanks for @dtkachenko for the follow-up!
