### ISSUE TITLE
vault-env should renew leases of dynamic secrets

### ISSUE THREAD

**Issue by msvticket** [banzaicloud/bank-vaults#420]
**Is your feature request related to a problem? Please describe.**
When using the Mutating Webhook feature to access dynamic secrets (like database passwords) the default_ttl now needs to be set to the anticipated execution time of the pod instead of being able to set default_ttl to a lower value and only set max_ttl to the anticipated execution time.

**Describe the solution you'd like**
vault-env renews the lease at the appropriate times.

**Describe alternatives you've considered**
Maybe this could be solved by integrating with Vault Agent.

**Comment by bonifaido** [comment]
Hi @msvticket! The vault-env binary replaces itself with the actual program it is requesting secrets for, so it is best used for very long living secrets like certificates/ssh keys or KV secrets.

For dynamic secrets there is a PR in the making, actually mutating the pods to inject a consul-template sidecar into them, please follow up on https://github.com/banzaicloud/bank-vaults/pull/410 for more details.

**Comment by msvticket** [comment]
Yeah, I know the current design of vault-env would need to be change to fulfil my suggestion. Thanks for the pointer to the pull request. I'm not surprised that the problem is being worked on.
