### ISSUE TITLE
Cannot compile vault-env

### ISSUE THREAD

**Issue by ut0mt8** [banzaicloud/bank-vaults#431]
**Describe the bug**
Cannot compile vault-env with go-get 

**To Reproduce**
```go get github.com/banzaicloud/bank-vaults/cmd/vault-env```

**Expected behavior**
Having a binary at the end :)

**Screenshots**
```
package github.com/hashicorp/vault/helper/consts: cannot find package "github.com/hashicorp/vault/helper/consts" in any of:
        /usr/local/go/src/github.com/hashicorp/vault/helper/consts (from $GOROOT)
        /home/raf/go/src/github.com/hashicorp/vault/helper/consts (from $GOPATH)
```

The file have changed to "github.com/hashicorp/vault/sdk/helper/consts" I think.
But now I got

```
go/src/github.com/banzaicloud/bank-vaults/pkg/vault/operator_client.go:902:4: cannot use pluginType (type "github.com/hashicorp/vault/sdk/helper/consts".PluginType) as type "github.com/hashicorp/vault/vendor/github.com/hashicorp/vault/sdk/helper/consts".PluginType in field value
```

**Comment by sagikazarmark** [comment]
What version of Go do you use?

We switched to Go Modules recently and require at least Go 1.11.5 to build this project.

I've just tried and with go modules enabled I can build that binary.

**Comment by ut0mt8** [comment]
go version go1.12.3 linux/amd64.

Did I have to enable something for go modules working ?

**Comment by sagikazarmark** [comment]
Can you try to build it with the following command?

`GOPATH=/tmp/gopath-for-bank-vaults GO111MODULE=on go get github.com/banzaicloud/bank-vaults/cmd/vault-env`

**Comment by ut0mt8** [comment]
It works with gomodule 👍

**Comment by sagikazarmark** [comment]
Yeah, that's probably a good idea. We are going to improve the documentation soon!

**Comment by kazaff** [comment]
Hi @sagikazarmark 
Could you help me to fix the same problem with my environment?

```
OS: win10
GO Version: 1.11.2 windows/amd64
```

**Comment by pbalogh-sa** [comment]
Hello @kazaff , as @sagikazarmark mentioned to build this project require at least Go 1.11.5.

**Comment by bonifaido** [comment]
The docs have now clear steps on how to compile the project: https://github.com/banzaicloud/bank-vaults#installing closing.

**Comment by kazaff** [comment]
@pbalogh-sa  Thank you~

**Comment by mbrancato** [comment]
Vault recently moved `vault/helper/consts` to `vault/sdk/helper/consts`. You might try removing modules for `github.com/hashicorp/vault` that are not tied to the specific release needed. I used a local go.mod to specify the included version as I was just including bank-vaults for the client library.

**Comment by bonifaido** [comment]
I think it is not yet released, but will do once it gets a stable tag, thanks @mbrancato !

**Comment by bonifaido** [comment]
@mbrancato FYI https://github.com/banzaicloud/bank-vaults/pull/573
