### ISSUE TITLE
Credential leak on connection failure

### ISSUE THREAD

**Issue by gregdurham** [banzaicloud/bank-vaults#439]
**Describe the bug**
In case of a failure to validate a connection, bank-vaults will print the user name and password in plain text to the standard out. 

**To Reproduce**
1. Provide an invalid ip/dns for a backend, i.e. mysql/rabbitmq
2. let bank-vaults attempt to connect
3. Show logs of bank-vaults, and see creds in the clear

`time="2019-04-30T12:49:59Z" level=error msg="error configuring vault: error configuring secret engines for vault: error putting [map[connection_uri:http://rabbitmq.default.svc.cluster.local name:connection password:plaintextpassword ttl:760h ttl_max:760h username:plaintextadmin verify_connection:true]] -> rabbitmq/config/connection config into vault: Error making API request.\n\nURL: PUT http://vault:8200/v1/rabbitmq/config/connection\nCode: 500. Errors:\n\n* 1 error occurred:\n\t* failed to validate the connection: Get http://rabbitmq.default.svc.cluster.local/api/users/: dial tcp ip.ad.dr.ess:80: i/o timeout\n\n"`

**Expected behavior**
passwords should never be printed to screen.

**Comment by sagikazarmark** [comment]
@gregdurham Thanks for reporting this issue. We are on it.
