### ISSUE TITLE
Okta Auth backend support 

### ISSUE THREAD

**Issue by gkid** [banzaicloud/bank-vaults#454]
**Describe the bug**
I'd like to request support for Okta backend. I understand that it has not been implemented yet.

**To Reproduce**
I've tried the following config:
   auth:
     - type: okta
       config:
         - organization: mycompany
         - base_url: okta.com

When I check in Okta UI - I see that the Okta backend is created, but is not configured with the organization nor the base_url.

There is also an optional 3rd parameter which can be passed "token".

Thanks

**Comment by bonifaido** [comment]
Hi @gkid,

this has been implemented in https://github.com/banzaicloud/bank-vaults/pull/449
Please use the 0.4.16-rc.2 pre-release images to be able to test it.

**Comment by bonifaido** [comment]
Fixed by #449
