### ISSUE TITLE
Add configurer support for cross-cluster k8s auth

### ISSUE THREAD

**Issue by so0k** [banzaicloud/bank-vaults#46]
Would it make sense to extend the configurer yaml allowing it to take in k8s CA and token information from configuration file?

This would be to support scenarios where several clusters share a vault deployed to a single cluster.

**Comment by bonifaido** [comment]
Hi, @so0k, yes that would make sense, we have plans to support that, if you would like to speed it up pull requests are welcome! 
Basically it is not a huge change I thing, the configuration is already parsed, if none of those settings are given, the current default configuration should be applied. Would this be sufficient for you?

**Comment by so0k** [comment]
Yup, I can do a PR for this - I just wasn't sure if this approach would fit the project.

**Comment by bonifaido** [comment]
Absolutely, that was missed out because of time constraints.

**Comment by bonifaido** [comment]
Fixed by #145
