### ISSUE TITLE
vault-secrets-webhook: Support re-authentication with Consul-Template

### ISSUE THREAD

**Issue by marcoreni** [banzaicloud/bank-vaults#464]
**Is your feature request related to a problem? Please describe.**
Right now the vault-token is set via vault-agent during init phase. Consul-Template will use the token and renew it if the token is near the expiration time.
AFAIU, two different use-cases are not handled right now:

1. kubernetes auth role is configured with a max_ttl of N hours. When max_ttl is reached, the token is not renewable anymore but CT is not able to retrieve a new token and will eventually fail. After restart, CT will use the same expired token, thus not being able to self recover unless a new deployment is triggered.
2. The token is manually revoked via Vault. The result is similar to the previous use case.

**Describe the solution you'd like**
Somehow the system should be able to self-recover. We may use vault-agent as a sidecar in order to have it handle the token re-creation (this way, we may be also able to use consul-template 0.20.0 since the renewal of the token would be handled by vault-agent).

**Describe alternatives you've considered**
Create a custom CT image that includes vault-agent as a daemon. This may be lighter, but is against the one-process-per-container rule.

**Comment by matyix** [comment]
Hey @jurgenweber - you mind adding your thoughts on this?

**Comment by jurgenweber** [comment]
consul-template will renew the token. Are you actually experiencing this or theory crafting? 

https://github.com/hashicorp/consul-template#configuration-file-format

```
  # This option tells Consul Template to automatically renew the Vault token
  # given. If you are unfamiliar with Vault's architecture, Vault requires
  # tokens be renewed at some regular interval or they will be revoked. Consul
  # Template will automatically renew the token at half the lease duration of
  # the token. The default value is true, but this option can be disabled if
  # you want to renew the Vault token using an out-of-band process.
  #
  # Note that secrets specified in a template (using {{secret}} for example)
  # are always renewed, even if this option is set to false. This option only
  # applies to the top-level Vault token itself.
  renew_token = true
```

But there is also a known issue with later versions of consul-template. It is broken in one edge case:

https://github.com/hashicorp/consul-template/issues/1189

**Comment by jurgenweber** [comment]
I just re-read and I see you are saying 'max_ttl' or token revocation. 

A few things, don't set a max_ttl. Is it really that necessary? In an agile environment with elastic capacity management pods do not live long. I know mine don't, I have not even considered a max_ttl. It almost feels like an anti-pattern.

In the case of emergency and you revoke all of your tokens, ok. I feel your live/ready probes should fail and the pod should restart. 

I am pretty against yet another side car, the idea was to keep it lite and simple and it is heavy enough as it is.

**Comment by marcoreni** [comment]
As per the max_ttl, I'd rather be sure that my tokens are recreated after a maximum amount of time (or after a maximum number of uses, since we have also num_uses attribute available) rather than relying on the fact that all my services will restart often. I may have a long running pod that does not scale nor restarts often, and the token associated to that pod would never expire and will keep on being renewed.

As per revoking, the issue that I see is that, since initContainer is only run on the start/restart of pod, I would need to cause a full pod crash upon CT/app crashing to make this work.

One way of doing this may be to have `restartPolicy` set to `Never`, but then I'd have to "crash my pod" on every application error.
AWS ECS has an "essential" attribute on containers inside a service that makes a service fully restart if one of those containers fail, but AFAIK it is not possible to do this on K8s right now.

I agree that creating a new sidecar further complicates things, but right now I see no other solution

**Comment by jurgenweber** [comment]
Yeah, you can also just HUP `consul-template`. This can force a renew on revocation, maybe the probes can do that.

 I think I just realised where I have been confused with your comments, you are using the term `renew` in place of `getting a new token`.

You don't want a renew do you (https://www.vaultproject.io/docs/commands/token/renew.html#token-renew) you just want a new token?

**Comment by marcoreni** [comment]
I double checked all my comments, and I confirm what I wrote. I'm using the term "renew" to indicate the vault operation `token renew` (extend the current validity; token stays the same), and "recreate"/"retrieve a new token" to indicate a new authentication flow (obtain a new token).

If max_ttl is > 0, the token is renewable for that maximum time. For example, a token with TTL 1h, MAX_TTL 5h released at 00:00 can be renewed until 05:00. After that it won't be renewable anymore  and will expire. A new token must then be obtained with a new authentication operation. The same goes for a token with `num_uses` options set and for a revoked token.

Consul-Template handles the renewal, not the authentication (otherwise we wouldn't need vault-agent in the first place).

**Comment by jurgenweber** [comment]
Yeah, I get it.

Long running work loads sounds like a pet. :) 

In the end it is an outlier that is not answered, even by the people that invented the pattern. I just implemented it in the webhook (google Seth Vargo from Vault/Google).

To me/us/my project, I don't need to answer this and consider it scope creep, we are happy with no max_ttl and new deployments and pod restarts.

**Comment by devlounge** [comment]
It looks like there is a "period" option which can be provided when creating a role.
As per the official documentation:

> Period (string: "") - Duration in either an integer number of seconds (3600) or an integer time unit (60m). If set, the token generated using this AppRole is a periodic token; so long as it is renewed it never expires, but the TTL set on the token at each renewal is fixed to the value specified here. If this value is modified, the token will pick up the new value at its next renewal.

Wouldn't this solve the issue? As long as consul-template renews the token...

**Comment by marcoreni** [comment]
@devlounge by using "period" the token will never expire. This is actually similar to the TTL: until the token is renewed (within the TTL) it will not expire. 

max_ttl is used to force the clients (consul-template, in this case) to obtain a new token because the old one will expire no matter what.

**Comment by devlounge** [comment]
For long running pods I cannot have a token ever expiring so would it be this option?

**Comment by marcoreni** [comment]
If you create the Kubernetes Role without specifying max_ttl  (or setting it to 0), your long-running pod will work without issues, since Consul-Template is capable of automatically extending the token-lease. There is no need to set "period".

As per specific credentials (eg. mysql dynamic credentials), Consul-Template handles ttl and max_ttl correctly (renewing leases when possible and generating new credentials when the old ones are near expiration).

This issue is related to the error you will encounter *when* you set max_ttl. If you are experiencing other problems, they should probably be discussed in a different issue.
