### ISSUE TITLE
vault-env not requiring a command definition to inject secrets

### ISSUE THREAD

**Issue by timduhenchanter** [banzaicloud/bank-vaults#475]
```2019/05/23 23:22:14 Received new Vault token
2019/05/23 23:22:14 Initial Vault token arrived
no command is given, currently vault-env can't determine the entrypoint (command), please specify it explicitly
```

Allow for vault-env to inject secrets without the need for an explicit declaration of a command/entrypoint in the resource definition

My particular use case is the heavy utilization of public Helm charts with no templating for command definitions and the desire to not fork from the maintained charts.

**Comment by bonifaido** [comment]
Hi @timduhenchanter yes, this is a valid use case, work is being done here, and is a work in progress just now: https://github.com/banzaicloud/bank-vaults/pull/472
