### ISSUE TITLE
Split repo/project for vault-secrets-webhook and vault-env

### ISSUE THREAD

**Issue by arturo-c** [banzaicloud/bank-vaults#480]
**Is your feature request related to a problem? Please describe.**
I would like clear division between separate components that can be used outside the main `bank-vaults` project, we use the `vault-secrets-webhook` and `vault-env` docker image but we have our own install of vault

**Describe the solution you'd like**
Separate github repos for components

**Describe alternatives you've considered**
Continue using `bank-vaults` github repo

**Comment by bonifaido** [comment]
Hi @arturo-c, interesting idea, but what would be the benefit if this?

We currently find it really handy that all the 3 projects are in the same repository (the webhook, and vault-env are one project actually, they are not really usable without each other.) The operator uses the bank-vaults binary heavily. All three projects share common code parts, which we don't have to maintain in a 4th repository if we would split the project and include all of them.

**Comment by bonifaido** [comment]
So not splitting this time, but we can revisit this anytime in the future once the project grows a bit bigger or anything would force us to do so. Thanks for the suggestion!
