### ISSUE TITLE
no vendor

### ISSUE THREAD

**Issue by JoshuaAndrew** [banzaicloud/bank-vaults#481]
**Describe the bug**

# GO111MODULE=on go mod vendor -v
go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/joshua/workspace/bank-vaults/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': gnutls_handshake() failed: Error in the pull function.
go: error loading module requirements

**Comment by bonifaido** [comment]
Hi @JoshuaAndrew, this is an intermittent issue with the apache.org servers (or your connection), I couldn't reproduce right now. Please try again.

```
fatal: unable to access 'https://git.apache.org/thrift.git/': gnutls_handshake() failed: Error in the pull function.
```
