### ISSUE TITLE
operator: ingress on GKE doesn't work

### ISSUE THREAD

**Issue by bonifaido** [banzaicloud/bank-vaults#482]
**Describe the bug**
```
» kubectl describe ingresses.extensions vault                                                         (bonifaidobk6a/default)
Name:             vault
Namespace:        default
Address:          35.241.21.200
Default backend:  vault:8200 (10.32.0.8:8200)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     *     vault:8200 (10.32.0.8:8200)
Annotations:
  nginx.ingress.kubernetes.io/backend-protocol:  HTTPS
  ingress.kubernetes.io/backends:                {"k8s-be-30882--bcb59d1076ba8df3":"Unknown"}
  ingress.kubernetes.io/forwarding-rule:         k8s-fw-default-vault--bcb59d1076ba8df3
  ingress.kubernetes.io/protocol:                https
  ingress.kubernetes.io/secure-backends:         true
  ingress.kubernetes.io/target-proxy:            k8s-tp-default-vault--bcb59d1076ba8df3
  ingress.kubernetes.io/url-map:                 k8s-um-default-vault--bcb59d1076ba8df3
Events:
  Type     Reason  Age    From                     Message
  ----     ------  ----   ----                     -------
  Normal   ADD     38m    loadbalancer-controller  default/vault
  Warning  Sync    37m    loadbalancer-controller  Error during sync: error running backend syncing routine: unable to find nodeport {default/vault/8200 31568 8200 HTTP 8200 false <nil>} in any service
  Normal   CREATE  37m    loadbalancer-controller  ip: 35.241.21.200
  Warning  Sync    19m    loadbalancer-controller  Error during sync: error running backend syncing routine: unable to find nodeport {default/vault/8200 31312 8200 HTTP 8200 false <nil>} in any service
```

**To Reproduce**
1. Get a GKE cluster with HTTP load balancing enabled
2. `kubectl apply -f kubectl apply -f operator/deploy/operator-rbac.yaml`
3. `kubectl apply -f kubectl apply -f operator/deploy/operator.yaml`
4. `kubectl apply -f kubectl apply -f operator/deploy/rbac.yaml`
5. `kubectl apply -f kubectl apply -f operator/deploy/cr.yaml`

**Comment by david-dc-chen** [comment]
Hi @bonifaido ,  that's a quick fix. I've pulled the latest changes and tried it again on my cluster but still I'm seeing the same error. I deleted all existing ones, changed serviceType to NodePort and deployed those four resources files on my cluster. 
Any suggestion?

**Comment by bonifaido** [comment]
Thie change is only available currently on the master branch, so please try to change the operator image to master.

**Comment by david-dc-chen** [comment]
I am certain that I'm on git master branch and I can see the changes from the PR as I did the git pull.

**Comment by bonifaido** [comment]
Please run `kubectl describe` on the operator deployment and attach the Vault CR.

**Comment by david-dc-chen** [comment]
$ kubectl describe deployment  vault-operator
Name:               vault-operator
Namespace:          default
CreationTimestamp:  Thu, 30 May 2019 12:54:56 -0400
Labels:             <none>
Annotations:        deployment.kubernetes.io/revision: 1
                    kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"prometheus.io/port":"8383","prometheus.io/scrape":"true"},"name":"...
                    prometheus.io/port: 8383
                    prometheus.io/scrape: true
Selector:           name=vault-operator
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           name=vault-operator
  Service Account:  vault-operator
  Containers:
   vault-operator:
    Image:      banzaicloud/vault-operator:latest
    Port:       8383/TCP
    Host Port:  0/TCP
    Command:
      vault-operator
    Liveness:   http-get http://:8080/ delay=4s timeout=1s period=10s #success=1 #failure=1
    Readiness:  http-get http://:8080/ready delay=4s timeout=1s period=10s #success=1 #failure=1
    Environment:
      WATCH_NAMESPACE:   (v1:metadata.namespace)
      POD_NAME:          (v1:metadata.name)
      OPERATOR_NAME:    vault-operator
    Mounts:             <none>
  Volumes:              <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   vault-operator-b8c5c566c (1/1 replicas created)
Events:          <none>

**Comment by bonifaido** [comment]
Okay, so the operator is still using latest (which is the latest release), please change the tag to master.

**Comment by david-dc-chen** [comment]
Great. It is working.
