### ISSUE TITLE
feature request: vault-env option to ignore missing secrets

### ISSUE THREAD

**Issue by stephenmuss** [banzaicloud/bank-vaults#490]
I have a use case for vault-env where I need to ignore errors when a specific secret is not present in Vault.

It would be nice to be able to tweak the vault-env command to skip over missing secrets. Perhaps this could be enabled by providing an annotation.

E.g.
```yaml
vault.security.banzaicloud.io/vault-ignore-missing-secrets: "true"
```

When this is enabled vault-env could then use `logger.Warn` instead of `logger.Fatal` for missing secrets.

**Comment by stephenmuss** [comment]
I'd be happy to have a crack at this but would need to know how you want to handle the integration between the webhook and vault-env.

**Comment by bonifaido** [comment]
Hi @stephenmuss, this sounds just fine, we usually control the webhook through annotations and those options are provided as env variables to the vault-env binary. So this should work in this case as well. Sounds like a useful feature!
