### ISSUE TITLE
Support for /database/rotate-root/

### ISSUE THREAD

**Issue by msvticket** [banzaicloud/bank-vaults#503]
As described in https://learn.hashicorp.com/vault/secrets-management/db-root-rotation it is desirable to let Vault rotate the credentials it uses for handling database users. But using this causes problem in conjuction with bank-vaults since if you change a vault CRD with a database config: vault-configurer would then put the config again, but with an obsolete password and thus essentially break the configuration.

I would suggest introducing a boolean field called `rotate-root` on database configs. When set vault-configurer would call [`/database/rotate-root/`](https://www.vaultproject.io/api/secret/databases/index.html#rotate-root-credentials) for a config after it has been created. But before creating a config vault-configurer should check if the config already exists and in that case do nothing.

If I want to use bank-vaults together with the rotate-root functionality I would now need to manually remove a database config that has already been applied to vault from a Vault CRD  before doing any changes. This is cumbersome and error prone.

This functionality could be built upon a more general functionality of applying parts a of a vault CRD just once. So one idea is to introduce a field `once` that makes vault-configurer check if a config exists and only applies it if it is missing. `rotate-root: true` would then imply `once: true`.

**Comment by bonifaido** [comment]
Original discussion at: https://community-banzaicloud.slack.com/archives/CFJJW9L94/p1560158976020100
