### ISSUE TITLE
operator/deploy/config-jwt-groups.yaml example does not correctly configure JWT backend

### ISSUE THREAD

**Issue by robertgates55** [banzaicloud/bank-vaults#504]
**Describe the bug**
operator/deploy/config-jwt-groups.yaml example does not correctly configure JWT backend

**To Reproduce**
1. Install the `banzaicloud/vault-operator` helm chart (eg latest `0.2.15`)
2. Deploy a working vault
3. Add a `- type: jwt` section to `spec.externalConfig.auth` to add the example from `operator/deploy/config-jwt-groups.yaml` yaml

**Expected behavior**
This should create a `jwt` auth method, populated with the provided config options

**Actual behaviour**
Installs a `jwt` auth method, but with entirely empty config (see screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/7437497/59199366-aa943500-8b8d-11e9-9f74-ecebf892526a.png)

**Comment by primeroz** [comment]
Hi

It probably means that bank-vaults is failing to configure the backend.

Can you post the vault-configurer logs and the configuration snippet you are applying ?

I use it myself on a daily basis and it works :)

**Comment by robertgates55** [comment]
So I'm actually using the oidc provider, but copying the same pattern from the `jwt` provider. I've also tried jwt with the same result.

To test again, I've just detroyed the vault instance and re-applied from scratch. The auth section here looks like:

**Comment by primeroz** [comment]
Yeah oidc and jwt should be same. 

I think you missed the config actually. Also the logs would be great.

**Comment by robertgates55** [comment]
(sorry - pressed send too soon!)

**Comment by primeroz** [comment]
Ok. So the problem , at least from my phone debug skill, is that I don't think oidc is implemented as Auth backend in bank vaults.

 I only did implement jwt ( that's all I needed ) which is consistent with the issue you are having.
Auth backend get mounted but not configured.

We can do it pretty easily. I will give it a shot tomorrow or feel free to submit a pr if you feel like it.

**Comment by robertgates55** [comment]
Ah yeah. Looks fairly likely.

Presume this is all we're after? (I've not raised a PR direct to here as I'm not sure on the normal flow)

https://github.com/robertgates55/bank-vaults/commit/3b1d1e26c1596540ee5c9745e61ce5d40744245d

**Comment by bonifaido** [comment]
Looks cool, please submit it to this repository @robertgates55! Thanks

**Comment by primeroz** [comment]
Yeah pretty much but I am on my phone so can't really double check. 

You can open a pr , sing the CLA (you will get a link in your pr) and that's it. 
Ci will run and everything else will happen

If you want to test it on your own just run "make docker" and push to a registry you can manage

**Comment by primeroz** [comment]
@robertgates55  once a new master image is available at **https://hub.docker.com/r/banzaicloud/bank-vaults/builds** can you make sure this is fixed an close this issue ?

**Comment by robertgates55** [comment]
Should it be there by now? (it isn't)

How long should I wait?!

**Comment by bonifaido** [comment]
The images are already built by now.

**Comment by robertgates55** [comment]
Apologies - presume it's a UI quirk of docker hub - was waiting for the 'last updated' to be today!
![image](https://user-images.githubusercontent.com/7437497/59291306-7777a180-8c72-11e9-8e37-4659927790a8.png)

ANYWAY - Tested my side using the 'master' branch, and excellently, OIDC has been correctly applied!

**Comment by bonifaido** [comment]
Great stuff, thanks for testing out! :+1:
