### ISSUE TITLE
bank-vault + operator unseal azure with consul backend for HA

### ISSUE THREAD

**Issue by Kannabir** [banzaicloud/bank-vaults#506]
**Describe the bug**
We have been trying to use the Vault Operator + Unseal using Azure key vault along with a Consul Backend on a Kubernetes cluster deployed using the AKS Engine generator.
Unable to talk to Consul backend when using 127.0.0.1:8500 ( I'm guessing because the Bank-Vault image used by the CRD does not have a consul agent as a container?)

When I specify a specific Consul pod for its IP, i'm able to register with Consul and I get HA, but vault does not interact with Azure Key vault for auto unseal.

I have no problem using Azure Unseal + File.

**To Reproduce**
1. Deploy Consul 
2. Deploy Vault Operator + Vault using Consul backend + Azure Unseal

**Expected behavior**

Vault uses Consul as its backend ensuring HA while using Azure keyvault for auto unseal

**Comment by pbalogh-sa** [comment]
@Kannabir Thank you for reporting this. We will look after the bug.

**Comment by bonifaido** [comment]
@Kannabir could you please post your CR as an example, so we can try to reproduce the issue?

**Comment by Kannabir** [comment]
Sure

The CR used is  

```apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: {{ template "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  size: 1
  image: vault:1.0.0
  bankVaultsImage: banzaicloud/bank-vaults:latest
  unsealConfig:
    azure:
      keyVaultName: "{{ .Values.azure.vaultName }}"
  serviceAccount: {{ template "vault.fullname" . }}
  ingress:
    annotations:
      certmanager.k8s.io/cluster-issuer:  {{ .Values.issuer}}
      kubernetes.io/ingress.class: traefik
    spec:
      rules:
        - host: vault.{{ .Values.domain }}
          http:
            paths:
              - backend:
                  serviceName: {{ template "vault.fullname" . }}
                  servicePort: api-port
      tls:
        - hosts:
          - vault.{{ .Values.domain }}
          secretName: vault.{{ .Values.domain }}
  config:
    storage:
      consul:
        address: 127.0.0.1:8500
        path: "vault/"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://{{ template "vault.fullname" . }}.{{ .Release.Namespace }}.cluster.local:8200
    ui: true
  externalConfig:
    policies:
      - name: admin
        rules: path "*" { capabilities = ["create", "read", "update", "delete", "list"] }
      - name: write_secret
        rules: path "secret/*" { capabilities = ["create", "read", "update", "delete", "list"] }
      - name: read_secret
        rules: path "secret/*" { capabilities = ["read", "list"] }
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: "*"
            policies: read_secret
            ttl: 1h
          - name: local_read
            bound_service_account_names: {{ template "vault.fullname" . }}
            bound_service_account_namespaces: {{ .Release.Namespace }}
            policies: read_secret
            ttl: 1h
          - name: cluster-admin
            bound_service_account_names: {{ template "vault.fullname" . }}-admin
            bound_service_account_namespaces: {{ .Release.Namespace }}
            policies: admin
            ttl: 1h
  credentialsConfig:
    env: AZURE_AUTH_LOCATION
    path: /etc/azure/credentials
    secretName: {{ template "vault.fullname" . }}
```

I get a  
> [WARN]  storage migration check error: error="Get http://127.0.0.1:8500/v1/kv/vault/core/migration: dial tcp 127.0.0.1:8500: connect: connection refused"

If i switch up the consul address to a local pod, it does not use azurekey vault to unseal the keys/even store them there

**Comment by bonifaido** [comment]
No, it doesn't have a consul-agent, so 127.0.0.1:8500 won't work, I suggest to put the address of the Consul Kubernetes Service there. Clear the Vault data before doing this from Consul. After that please try to rerun this and if it doesn't work send the logs from all containers of the vault Pod.

**Comment by Kannabir** [comment]
I got it working!
It was a mix between clearing the key vault, using hashicorp's consul and putting the Consul k8s service address there!

Thank you :)

**Comment by bonifaido** [comment]
You're welcome! Feel free to open a new issue, or reopen this one in case.
