### ISSUE TITLE
Will bank-vaults work with Istio already running on k8s?

### ISSUE THREAD

**Issue by nippip** [banzaicloud/bank-vaults#514]
I am asking to see if running bank-vaults with Istio on k8s would be a problem.

**Additional context**
We will be running Istio with full mTLS between pods so just seeing if this would work in a setup with FULL Istio deployed.

**Comment by matyix** [comment]
Hey @nippip - it should not be a problem. Do you have a particular scenario in mind which you think might not work? We semi use them together (with our [Istio operator](https://github.com/banzaicloud/istio-operator) - the BV operator/Vault is running in the control plane and webhook/vault-env in the cluster) and it's fine. 

Usually, with Istio, you will have to set up/choose the namespaces where the sidecar injection work and those are different ones anyway. 

Please let us know how it goes for you. Btw, how are you deploying/managing Istio, are you using the operator?

**Comment by bonifaido** [comment]
Hi @nippip, some users are successfully running BV with Istio enabled clusters as well, please see the following Slack messaging: https://community-banzaicloud.slack.com/archives/DJCC1GQBB/p1557750927001800

**Comment by nippip** [comment]
@matyix @bonifaido Thank you both for the quick responses and good info / links!  I'll use the slack channel going forward and close this "issue".
