### ISSUE TITLE
vault_cr.spec.caNamespaces: dupplicate only the ca.crt key

### ISSUE THREAD

**Issue by devlounge** [banzaicloud/bank-vaults#519]
**Describe the bug**
I was wondering if it wouldn't be better to ONLY dupplicate the ca.crt key in the namespaces listed in vault-cd.spec.caNamespaces

I wonder if makes any sens to also put the 2 other keys (server.cert and server.key) in the target namespaces, as these only need the CA cert to talk to the vault.

version: 0.17-rc.4

**Comment by bonifaido** [comment]
Actually, we delete the server.crt and server.key from the Secret here: https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/controller/vault/vault_controller.go#L1700 maybe it stopped working after the refactoring.

NOTE: we should also remove the ca.key from the keys.
