### ISSUE TITLE
Mutating webhook doesn't mount TLS certificates to the "main" container

### ISSUE THREAD

**Issue by Oded-B** [banzaicloud/bank-vaults#526]
**Describe the bug**
When using the vault.security.banzaicloud.io/vault-tls-secret annotation the vault-agent init container is configured to mount the TLS secret and receive a VAULT_CACERT env variable.
The "main" container doesn't get the mount and the VAULT_CACERT var so the vault-env binary fails to connect to Vault.

**To Reproduce**
1) Setup bank-vaults with mutating webhook and TLS
2) run a pod with these annotations:
vault.security.banzaicloud.io/vault-tls-secret: SECRET_NAME
 vault.security.banzaicloud.io/vault-skip-verify: "false" (default)
vault.security.banzaicloud.io/vault-agent: "true" (default)
3) See "certificate signed by unknown authority" on the main container log. 

 
**Expected behavior**
Both the vault-agent init container and the main container should have the TLS secrets mounted and they should use them to successfully connect to the Vault server

**Comment by gkid** [comment]
It looks like the certificate is still missing in the main container...
Using banzaicloud/bank-vaults:0.4.18 with TLS enabled.
I still receive the following error in my deploy:

2019/07/21 14:40:56 Failed to request new Vault token Put https://vault-staging.vault-test:8200/v1/auth/kubernetes/login: x509: certificate signed by unknown authority
2019/07/21 14:41:00 Failed to request new Vault token Put https://vault-staging.vault-test:8200/v1/auth/kubernetes/login: x509: certificate signed by unknown authority
{"level":"fatal","ts":1563720062.5686953,"caller":"vault-env/main.go:78","msg":"Failed to create vault client","error":"timeout [10s] during waiting for Vault token","stacktrace":"main.main\n\t/build/cmd/vault-env/main.go:78\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}

As a workaround, I have added something like below to my spec, but this should be taken care of by the :
       env:
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        volumeMounts:
        - mountPath: /vault/tls
          name: vault-tls2
      volumes:
      - name: vault-tls2
        secret:
          defaultMode: 420
          secretName: vault-staging-tls

**Comment by bonifaido** [comment]
@gkid how your pod spec looks like?

**Comment by bonifaido** [comment]
If I specify the annotation `vault.security.banzaicloud.io/vault-tls-secret: vault-staging-tls` I can't reproduce.

**Comment by gkid** [comment]
Complete Spec:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-env-var-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-env-var-test
  template:
    metadata:
      labels:
        app: vault-env-var-test
      annotations:
        # vault.security.banzaicloud.io/vault-addr: "https://vault-staging.vault-test.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-addr: "https://vault-staging.vault-test:8200"
        vault.security.banzaicloud.io/vault-role: "vault-test"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-staging-tls"
        # vault.security.banzaicloud.io/vault-skip-verify: "true"
        # vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      serviceAccountName: vault-env-var-test
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $WEBHOOK_TEST_SECRET && echo going to sleep... && sleep 10000"]
        env:
        - name: WEBHOOK_TEST_SECRET
          value: vault:secret/data/riski-services/vault-test/vault-env-var-test#WEBHOOK_TEST_SECRET
      #all below should probably be created automatically by the mutating webhook
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        volumeMounts:
        - mountPath: /vault/tls
          name: vault-tls2
      volumes:
      - name: vault-tls2
        secret:
          defaultMode: 420
          secretName: vault-staging-tls
