### ISSUE TITLE
[Operator] Vault CRD does not support priorityClassName

### ISSUE THREAD

**Issue by ryandbump** [banzaicloud/bank-vaults#530]
**Is your feature request related to a problem? Please describe.**
Vault pods are being preempted in when cluster resource pressure is high. 

**Describe the solution you'd like**
I would like to set `priorityClassName` on the vault pods to prevent unwanted preemption. Ideally, I would be able to specify a different `priorityClassName` for the pods created by each controller. 

I think the best way to achieve this, and to enable more features in the future, is to add attributes like `vaultPodSpec`, `configurererPodSpec`, and `etcdPodSpec` to the CRD. The values in these attribute would be merged with the pod specs created in `vault_controller.go`. 

**Describe alternatives you've considered**
Currently the only way to add `priorityClassName` to pods is to edit the pods after they have been created. This is not sustainable.

**Comment by matyix** [comment]
Hey @ryandbump - thanks for submitting the issue! Would you be interested to work on/contribute to this feature? In our usage pattern, we separated Vault (namespace or cluster) from the workload and we did not add `riorityClassName`, though I agree with you, it's a totally valued requirement.

**Comment by ryandbump** [comment]
Yeah I could take stab at it.

**Comment by baluchicken** [comment]
Fixed by #531 
thanks @ryandbump

**Comment by matyix** [comment]
@ryandbump thanks for opening the issue and contributing it. @pbalogh-sa added some usage example as well in #536.
