### ISSUE TITLE
[vault-secrets-webhook] Receiving Get /v2/: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by nesl247** [banzaicloud/bank-vaults#534]
**Describe the bug**
When using the vault-secrets-webhook with a pod running container `docker.whatsapp.biz/coreapp:v2.23.4`, I am getting `cannot create client for registry: Get /v2/: unsupported protocol scheme \"\""`.

In the logs, I am getting: `I'm using registry ` (with the space) and also `registry.ping url=/v2/`.

This is leading me to believe that the logic for determining the registry URL does not like the image that I am providing. In this case, the container is not explicitly defining the entrypoint and command (it's defined in the Dockerfile).

The Istio sidecar is enabled, so it may be conflicting with that, not sure.

**To Reproduce**

**Expected behavior**
It should determine the registry URL properly, which I would imagine would be `https://docker.whatsapp.biz`.

**Comment by bonifaido** [comment]
Hi @nesl247, which version of the webhook are you using? This has been fixed in https://github.com/banzaicloud/bank-vaults/commit/eeaf41d3aed33ac6f858fb3fe9da6d8912b5458c

**Comment by nesl247** [comment]
I was running the latest helm chart at the time, which for some reason was still on rc4 even though `helm search` showed the released version. I'll close this out and reopen if necessary.

**Comment by bonifaido** [comment]
Yes I just released it with the latest version a few hours ago. Thanks for reporting!
