### ISSUE TITLE
vault-secrets-webhook: Cannot omit container command when image is only in local registry

### ISSUE THREAD

**Issue by douglaswth** [banzaicloud/bank-vaults#570]
**Describe the bug**:
The vault secrets webhook fails when a pod container definition does not include the `command` field and the image is only available in the local registry and not the upstream registry. This use case comes up in local development with minikube.

**Expected behaviour**:
The vault secrets webhook should inspect the image in the local registry if it cannot be found upstream, especially if the `imagePullPolicy` is `Never`.

**Steps to reproduce the bug**:
1. Bring up a kubernetes cluster using minikube
2. Start a vault deployment in the cluster
3. Install the vault-secrets-webhook helm chart
4. Build a docker image using minikube as the docker daemon/registry
5. Apply a Kubernetes deployment using the docker image in a pod without specifying the `command`

**Additional context**:
This issue may only come up when a matching image hasn't been pushed up to the upstream registry, but I see potential for a mismatch if the development docker image has a different `ENTRYPOINT` specified from what is upstream.

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.13.8
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): minikube
- bank-vaults version (e.g. 0.4.17): 0.4.18
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
  ```
  time="2019-07-30T22:47:16Z" level=error msg="admission webhook error: cannot download manifest for image: Get https://1234567890.dkr.ecr.us-east-1.amazonaws.com/v2/hello/world/manifests/latest: http: non-successful response (status=404 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"MANIFEST_UNKNOWN\\\",\\\"message\\\":\\\"Requested image not found\\\"}]}\\n\")"
  ```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by bonifaido** [comment]
This is not a bug but a missing feature, which is not going to be implemented at least not now. (Hypothesis incoming, please feel free to correct me) I think we are not talking about registries here but the images on the disk next to the local container daemon, since registry access should work. To access those images you need to talk to the Docker/ContainerD/CRI-O daemon, and to be able to do that you would need to mount the Docker/ContainerD/CRI-O UNIX socket to the container which is a really bad practice.

I suggest to push those images into the Docker registry of Minikube (you can enable the registry addon with the Minikube CLI) and access them from that, if that doesn't work, please file an issue.

**Comment by SantiEich** [comment]
Same issue here
```
time="2021-09-03T13:33:09Z" level=error msg="admission webhook error: cannot fetch image descriptor: GET https://00000000000.dkr.ecr.us-east-1.amazonaws.com/v2/locations-service/manifests/0.21.1: MANIFEST_UNKNOWN: Requested image not found" app=vault-secrets-webhook
time="2021-09-03T13:33:10Z" level=error msg="admission webhook error: cannot fetch image descriptor: GET https://00000000000.dkr.ecr.us-east-1.amazonaws.com/v2/locations-service/manifests/0.21.1: MANIFEST_UNKNOWN: Requested image not found" app=vault-secrets-webhook
```

**Comment by bonifaido** [comment]
Not sure how this relates to the original issue, which already has been resolved since we can query registry metadata for container commands and ENTRYPOINT. Please open up a new issue if you have errors with that.
