### ISSUE TITLE
Operator diagram is inaccurate

### ISSUE THREAD

**Issue by paigr** [banzaicloud/bank-vaults#577]
Hello, I was reviewing the documentation for the operator, and have noticed that the diagram located at [`docs/operator/images/vaultoperator.png`](https://github.com/banzaicloud/bank-vaults/blob/master/docs/operator/images/vaultoperator.png?raw=true) has inaccurate information. Close to the bottom right, the `bank-vaults` and `vault` containers are shown to be in separate Pods, `Pod-1` and `Pod-2`; however, in reality, they share the same Pod. While the difference is subtle, I think it's worth fixing.

Thanks for working on this great project!

**Comment by bonifaido** [comment]
Thank you @paigr, we are going to fix this!
