### ISSUE TITLE
Error accessing vault webhook

### ISSUE THREAD

**Issue by robertdudusbjss** [banzaicloud/bank-vaults#583]
I'm receiving this error when I run:
k describe -n kube-system replicaset.apps/tunnelfront-86c59997f

"Warning  FailedCreate  54s   replicaset-controller  Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.banzaicloud.com": Post https://wmwh-vault-secrets-webhook.wmwh.svc:443/pods?timeout=30s: dial tcp 10.41.1.24:443: i/o timeout"

Currently I can't run "kubectl logs ..." for anything as I get this response:
"Error from server: Get https://aks-default-60639119-2:10250/containerLogs/wmwh/wmwh-vault-secrets-webhook-586fb699d7-2hnf7/vault-secrets-webhook: dial tcp 10.40.0.66:10250: i/o timeout:

How should I investigate it? Can I send you something to help?

Thanks

**Comment by bonifaido** [comment]
The issue got moved here.

How did you installed the webhook @robertdudusbjss ? What was the exact helm command and parameters? Versions?

**Comment by bdashrad** [comment]
we're running into this issue if we attempt to kill/restart the pod for the webhook. it depends on the webhook to start and we end up having to remove it and redeploy.

**Comment by bonifaido** [comment]
The install method of the webhook is highly important here, it's own namespace has to be excluded from the mutation scope.

https://github.com/banzaicloud/bank-vaults/tree/master/charts/vault-secrets-webhook#creating-the-namespace

**Comment by bdashrad** [comment]
@bonifaido thanks for the fast response, that will fix it for us i think

**Comment by robertdudusbjss** [comment]
@bonifaido This is what I get by running a few kubectl commands:
➜  ~ k describe namespace wmwh
Name:         wmwh
Labels:       name=wmwh
Annotations:  <none>
Status:       Active

➜  ~ k get all -n wmwh
NAME                                              READY   STATUS    RESTARTS   AGE
pod/wmwh-vault-secrets-webhook-586fb699d7-2hnf7   1/1     Running   0          173m


NAME                                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/wmwh-vault-secrets-webhook   ClusterIP   10.41.1.24   <none>        443/TCP   49d


NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/wmwh-vault-secrets-webhook   1/1     1            1           49d

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/wmwh-vault-secrets-webhook-586fb699d7   1         1         1       49d

➜  ~ k logs wmwh-vault-secrets-webhook-586fb699d7-2hnf7 -n wmwh
Error from server: Get https://aks-default-60639119-2:10250/containerLogs/wmwh/wmwh-vault-secrets-webhook-586fb699d7-2hnf7/vault-secrets-webhook: dial tcp 10.40.0.66:10250: i/o timeout

➜  ~ k describe pod wmwh-vault-secrets-webhook-586fb699d7-2hnf7 -n wmwh
Name:           wmwh-vault-secrets-webhook-586fb699d7-2hnf7
Namespace:      wmwh
Priority:       0
Node:           aks-default-60639119-2/10.40.0.66
Start Time:     Tue, 06 Aug 2019 13:49:32 +0100
Labels:         app=vault-secrets-webhook
                pod-template-hash=586fb699d7
                release=wmwh
Annotations:    checksum/config: 469807e1c91ac7d389e5dddd4fe86a82d8b7ad4738a20a29d92aca193989ac0b
Status:         Running
IP:             10.40.0.77
Controlled By:  ReplicaSet/wmwh-vault-secrets-webhook-586fb699d7
Containers:
  vault-secrets-webhook:
    Container ID:   docker://3edc155f56bd0cb1a8498d3df619fc1f76b636a91840d2fd14a40698245c518d
    Image:          banzaicloud/vault-secrets-webhook:0.4.17-rc.4
    Image ID:       docker-pullable://banzaicloud/vault-secrets-webhook@sha256:b4a2243c097f9353ba357d610d2ddfd398cf74d612ce73c359102c3dc2574bb9
    Port:           8443/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 06 Aug 2019 13:49:41 +0100
    Ready:          True
    Restart Count:  0
    Environment:
      TLS_CERT_FILE:         /var/serving-cert/servingCert
      TLS_PRIVATE_KEY_FILE:  /var/serving-cert/servingKey
      DEBUG:                 false
      VAULT_ENV_IMAGE:       banzaicloud/vault-env:latest
      VAULT_IMAGE:           vault:latest
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from wmwh-vault-secrets-webhook-token-p8952 (ro)
      /var/serving-cert from serving-cert (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  serving-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  wmwh-vault-secrets-webhook
    Optional:    false
  wmwh-vault-secrets-webhook-token-p8952:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  wmwh-vault-secrets-webhook-token-p8952
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

Could any of the labels be incorrect?

**Comment by bonifaido** [comment]
How ApiService for the webhook looks like?

**Comment by robertdudusbjss** [comment]
> How ApiService for the webhook looks like?

➜  ~ k describe service wmwh-vault-secrets-webhook -n wmwh
Name:              wmwh-vault-secrets-webhook
Namespace:         wmwh
Labels:            app=wmwh-vault-secrets-webhook
                   chart=vault-secrets-webhook-0.3.15
                   component=mutating-webhook
                   heritage=Tiller
                   release=wmwh
Annotations:       <none>
Selector:          app=vault-secrets-webhook,release=wmwh
Type:              ClusterIP
IP:                10.41.1.24
Port:              vault-secrets-webhook  443/TCP
TargetPort:        8443/TCP
Endpoints:         10.40.0.77:8443
Session Affinity:  None
Events:            <none>

**Comment by bonifaido** [comment]
This one rather please
https://github.com/banzaicloud/bank-vaults/blob/328a15ea8cbc416d626be23b6aa4116b3de2bf22/charts/vault-secrets-webhook/templates/apiservice-webhook.yaml#L22

**Comment by robertdudusbjss** [comment]
> This one rather please
> https://github.com/banzaicloud/bank-vaults/blob/328a15ea8cbc416d626be23b6aa4116b3de2bf22/charts/vault-secrets-webhook/templates/apiservice-webhook.yaml#L22

➜  ~ k get MutatingWebhookConfiguration -n wmwh
NAME                         CREATED AT
istio-sidecar-injector       2019-06-18T11:40:08Z
wmwh-vault-secrets-webhook   2019-06-18T10:52:14Z

➜  ~ k describe MutatingWebhookConfiguration wmwh-vault-secrets-webhook -n wmwh
Name:         wmwh-vault-secrets-webhook
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  admissionregistration.k8s.io/v1beta1
Kind:         MutatingWebhookConfiguration
Metadata:
  Creation Timestamp:  2019-06-18T10:52:14Z
  Generation:          1
  Resource Version:    1070
  Self Link:           /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/wmwh-vault-secrets-webhook
  UID:                 21da156f-91b7-11e9-a0a0-ee8f5bdec0e5
Webhooks:
  Client Config:
    Ca Bundle:  secret secret secret
    Service:
      Name:        wmwh-vault-secrets-webhook
      Namespace:   wmwh
      Path:        /pods
  Failure Policy:  Fail
  Name:            pods.vault-secrets-webhook.admission.banzaicloud.com
  Namespace Selector:
    Match Expressions:
      Key:       name
      Operator:  NotIn
      Values:
        wmwh
  Rules:
    API Groups:
      *
    API Versions:
      *
    Operations:
      CREATE
    Resources:
      pods
  Side Effects:  Unknown
  Client Config:
    Ca Bundle:  secret secret secret
    Service:
      Name:        wmwh-vault-secrets-webhook
      Namespace:   wmwh
      Path:        /secrets
  Failure Policy:  Fail
  Name:            secrets.vault-secrets-webhook.admission.banzaicloud.com
  Namespace Selector:
    Match Expressions:
      Key:       name
      Operator:  NotIn
      Values:
        wmwh
  Rules:
    API Groups:
      *
    API Versions:
      *
    Operations:
      CREATE
      UPDATE
    Resources:
      secrets
  Side Effects:  Unknown
  Client Config:
    Ca Bundle:  secret secret secret
    Service:
      Name:        wmwh-vault-secrets-webhook
      Namespace:   wmwh
      Path:        /configmaps
  Failure Policy:  Fail
  Name:            configmaps.vault-secrets-webhook.admission.banzaicloud.com
  Namespace Selector:
    Match Expressions:
      Key:       name
      Operator:  NotIn
      Values:
        wmwh
  Rules:
    API Groups:
      *
    API Versions:
      *
    Operations:
      CREATE
      UPDATE
    Resources:
      configmaps
  Side Effects:  Unknown
Events:          <none>

I've replaced sensitive parts with "secret secret secret".

**Comment by bonifaido** [comment]
I think the ConfigMap mutation brokes this (which we have disabled by default a few days ago). Please try to update the chart version to `0.4.0`, and let's check again!

**Comment by robertdudusbjss** [comment]
Hi. We are investigating it further. Please don't close the ticket just yet.

**Comment by bonifaido** [comment]
Any update on this @robertdudusbjss ?
