### ISSUE TITLE
[vault-secrets-webhook] Failure to deploy when pod is re-created on another node

### ISSUE THREAD

**Issue by jshrack-ssi** [banzaicloud/bank-vaults#584]
Twice now I have observed that after installing the vault-secrets-webhook helm chart into its own namespace, that it fails to deploy again when moved to another worker node. This then fails all other deployments as they cannot reach the admission controller. I don't see anything wrong with the initial deployment or any settings to modify. It has been placed into an isolated namespace per the installation guidance. Any thoughts? We are running on EKS (Kubernetes v1.10).

**Comment by jshrack-ssi** [comment]
@bonifaido Since re-deploying with the updated guidance everything now looks good. I've been running the webhook for several days without any of the aforementioned issues.

**Comment by bonifaido** [comment]
Great @jshrack-ssi , I will close this down then, feel free to open/reopen if you encounter any issues again.
