### ISSUE TITLE
[vault-secrets-webhook] Can't get token due to invalid character

### ISSUE THREAD

**Issue by VFourneau** [banzaicloud/bank-vaults#588]
Running on Google cloud public cluster
Kubernetes version: 1.13.7-gke.8 

Logs
```2019/08/07 14:23:13 Failed to request new Vault token Error making API request.

URL: PUT https://<VALID_URL>/v1/auth/kubernetes/login
Code: 500. Errors:

* parse https://<IP>/apis/authentication.k8s.io/v1/tokenreviews: net/url: invalid control character in URL
2019/08/07 14:23:18 Failed to request new Vault token Error making API request.

URL: PUT https://<VALID_URL>/v1/auth/kubernetes/login
Code: 500. Errors:

* parse https://<IP>/apis/authentication.k8s.io/v1/tokenreviews: net/url: invalid control character in URL
time="2019-08-07T14:23:19Z" level=fatal msg="failed to create vault clienttimeout [10s] during waiting for Vault token"
```

I'm running a fresh out of the box cluster, with nginx-ingress and jetstack/cert-manager.
I spawned a vault backed by consul following hashcorp guide.
I followed the process described here [https://github.com/banzaicloud/bank-vaults/tree/master/charts/vault-secrets-webhook](url) to install the webhook.

I'm using the following deployment to test the webhook:
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://<VALID_URL>"
        vault.security.banzaicloud.io/vault-role: "cluster"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      restartPolicy: Always
      containers:
        - name: testing
          image: alpine
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          command: ["echo"]
          args:
            - "$SECRET"
          env:
            - name: SECRET
              value: "vault:cluster/data/test/toto#foo"
```

I tried to find out more about this error but I wasn't able to find anything useful.
Any help would be appreciated.

**Comment by bonifaido** [comment]
Hi @VFourneau 

`vault.security.banzaicloud.io/vault-addr: "https://<VALID_URL>"` doesn't look good to me! :)

**Comment by VFourneau** [comment]
Hi @bonifaido I tried with multiple url, either the one using an ingress or the internal one, neither works.
I can give you one if you want: `http://vault.default.svc.cluster.local:8200`

**Comment by bonifaido** [comment]
I see, and how did you configure the Kubernetes auth backend? Maybe URL is wrong there.

**Comment by VFourneau** [comment]
Sure thing, here you go:
```
kubectl apply --filename ./vault/vault-auth-service-account.yml
vault policy write cluster ./vault/policy/cluster.hcl
export VAULT_SA_NAME=$(kubectl get sa default -o jsonpath="{.secrets[*]['name']}")
export SA_JWT_TOKEN=$(kubectl get secret $VAULT_SA_NAME -o jsonpath="{.data.token}" | base64 --decode; echo)
export SA_CA_CRT=$(kubectl get secret $VAULT_SA_NAME -o jsonpath="{.data['ca\.crt']}" | base64 --decode; echo)
export K8S_HOST=`kubectl cluster-info | grep "Kubernetes" | awk '{print $6}'`
vault auth enable kubernetes
vault write auth/kubernetes/config token_reviewer_jwt="$SA_JWT_TOKEN" kubernetes_host="$K8S_HOST" kubernetes_ca_cert="$SA_CA_CRT"
vault write auth/kubernetes/role/cluster bound_service_account_names=default bound_service_account_namespaces=default policies=cluster ttl=24h
```

**Comment by bonifaido** [comment]
can you make sure that `kubernetes_host="$K8S_HOST"` is correct? Or just use the operator to configure Vault.

**Comment by VFourneau** [comment]
That's why kubectl is giving me.

I might have to switch if it works with the operator.

**Comment by bonifaido** [comment]
Please try https://github.com/banzaicloud/bank-vaults/tree/master/operator#quick-start-deployment

**Comment by VFourneau** [comment]
Ok, I followed the instructions, how does it work now ?

**Comment by VFourneau** [comment]
@bonifaido 
For what it's worth. consul-template worked following this guide : [https://learn.hashicorp.com/vault/identity-access-management/vault-agent-k8s](url)
But using those configuration and what's mentioned above, the webhooks give that error

**Comment by VFourneau** [comment]
Ok, so I found why...

Turns out, it copied the colored output instead of plain text, so the invalid character is an escape code.

That's a new one for me.

Sorry for the noise.
