### ISSUE TITLE
[vault-secret-webhook] vault-agent container with runAsUser 100 fails to spawn on OpenShift

### ISSUE THREAD

**Issue by aidun** [banzaicloud/bank-vaults#599]
**Describe the bug**:
In OpenShift the vault-secret-webhook injects the init-container vault-agent with the securityContext "runAsUser: 100".

This is by default not allowed and you have to set the scc (security context contraint) anyuid to the service account which runs the pod.

**Expected behaviour**:
The webhook should respect the uid range of the namespace or the security context "runAsUser" should be removed.

**Steps to reproduce the bug**:
- Install the Webhook
- Deploy the sample application from documentation

**Additional context**:
The runAsUser part is hard-coded in file "cmd/vault-secrets-webhook/main.go" at line 120.

**Environment details**:
- OpenShift 3.11
- helm template ... | oc apply -f -
- Logs from the misbehaving component (and any other relevant logs):

/kind bug

**Comment by pbalogh-sa** [comment]
fixed by #698
