### ISSUE TITLE
Create a PDB for the webhook

### ISSUE THREAD

**Issue by nesl247** [banzaicloud/bank-vaults#628]
**Is your feature request related to a problem? Please describe.**
With the current helm charts, when the cluster is being upgraded, the webhook will go down, therefore it will cause pods to fail to be created as it can't reach the controller.

**Describe the solution you'd like**
By setting the replicas to 2, and creating a PDB with a `minAvailable` of 1, this will ensure that the webhook never goes down.

**Comment by bonifaido** [comment]
Please feel free to send a PR for this @nesl247 , I guess you have the right solution! :)
