### ISSUE TITLE
Use recommended K8s labels rather than custom

### ISSUE THREAD

**Issue by nesl247** [banzaicloud/bank-vaults#631]
**Is your feature request related to a problem? Please describe.**
Kubernetes has a recommended set of labels for applications. At minimum, the vault webhook helm cart is not using them.

See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Describe the solution you'd like**
Use the recommended labels as is being adopted by many helm charts.

**Comment by nesl247** [comment]
See https://github.com/helm/helm/pull/4448 for more information as well.

**Comment by bonifaido** [comment]
These charts were generated with an older version of helm so we got these labels (tbh we haven't had any issues with them), but following the current best practices shouldn't cause any harm. Thanks for looking into this.
