### ISSUE TITLE
Postgres isn't supported as an HA backend

### ISSUE THREAD

**Issue by fraenkel** [banzaicloud/bank-vaults#639]
If I add a storage stanza for `postgres` and include `ha_enabled: "true"`, the operator complains when the stateful set is > 1.

The current list of HA backends does not include `postgres`.

Since I wasn't sure how the list is managed, I wanted to verify that a PR to include `postgres` is acceptable.

My current workaround is to also provide `ha_storage` which gets around the issue right now.

/kind bug

**Comment by bonifaido** [comment]
Yes, Vault introduced Postgres as HA backend just recently, but we haven't introduced it yet, please go ahead!
