### ISSUE TITLE
configMap secrets and templating

### ISSUE THREAD

**Issue by lukasmrtvy** [banzaicloud/bank-vaults#655]
**Is your feature request related to a problem? Please describe.**
I must relly on some 3rd party apps, which can not be configured from env variables. (needs config file..) Usually I am using configMaps, but when comes to secrets in configMaps, its really bad idea to create secret from whole config. Some kind of templating and resolving from secrets would be superb.

**Describe the solution you'd like**
It would be super usefull, if something like this:
https://github.com/Soluto/kamus/tree/master/init-container#custom-templating-support
will be supported. There is cleary visible config and secrets that must be templated.

**Describe alternatives you've considered**
I guess its possible to use consul template, but its another application to keep alive..

**Comment by bonifaido** [comment]
Hi @lukasmrtvy, this is definitely on the roadmap to support templating without consul-template (which is supported by the webhook as well, by the way, I'm not sure if you know that). We plan to use Golang templating. Have you tried the consul template part from bank-vaults?

**Comment by oba11** [comment]
would be great if we can do something like this in the secret/configmap

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    vault.security.banzaicloud.io/agent-inject-secret-helloworld: "secret/helloworld"
    vault.security.banzaicloud.io/agent-inject-template-helloworld: |
    {{ with secret "secret/helloworld" }}
      {{ range $k, $v := .Data }}
        {{ $k }}: {{ $v }}
      {{ end }}
    {{ end }}
```

where 
```
vault read secret/helloworld
Key                       Value
---                       -----
refresh_interval          768h
FOO                   Alice
BAR                   Bob

```

**Comment by bonifaido** [comment]
We use a different style of templating @oba11 , but I think you can achieve the same results with that one as well!

**Comment by oba11** [comment]
Thank you @bonifaido , please is it possible to share an example of how this can be achieved as well?
