### ISSUE TITLE
copy-vault-env initContainer do not overwrite securityContext

### ISSUE THREAD

**Issue by devlounge** [banzaicloud/bank-vaults#663]
**Describe the bug**:
copy-vault-env initContainer always try to run as root as its securityContext gets set by the mutating webhook.

**Expected behaviour**:
It should run as the same user than the non-mutated pod main container.

**Additional context**:
With a podSecurityPolicy setting
```
runAsUser:
    rule: MustRunAsNonRoot

```
the pod cannot be scheduled.

**Environment details**:
- Kubernetes version 1.13.5:
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): On premises
- bank-vaults version (e.g. 0.4.17): 0.5.3

/kind bug

**Comment by devlounge** [comment]
#664

**Comment by pbalogh-sa** [comment]
@devlounge , did you set up the user in PodSecurityContext for a whole Pod? In container level, `RunAsUser` overrides the defined in pod level.

**Comment by pbalogh-sa** [comment]
If the user isn't defined in `SecuritContext` of the injected container, the container will run as user that is defined in `PodSecurityContext` I think.

**Comment by devlounge** [comment]
Yes, we set it at the top level securityContext

**Comment by devlounge** [comment]
Any chance this get merged soon?

**Comment by pbalogh-sa** [comment]
@devlounge 
https://github.com/banzaicloud/bank-vaults/pull/664#discussion_r324637026
