### ISSUE TITLE
Automatically restart pods when value changes in vault secret

### ISSUE THREAD

**Issue by nesl247** [banzaicloud/bank-vaults#668]
**Is your feature request related to a problem? Please describe.**
When changing a value in the vault, we currently have to kill the pods manually.

**Describe the solution you'd like**
It would be great if the webhook would automatically restart the pods so it doesn't have to be manually restarted.

**Comment by bonifaido** [comment]
For this use, I would suggest using the consul-template way: https://github.com/banzaicloud/bank-vaults/tree/master/docs/mutating-webhook

**Comment by nesl247** [comment]
Does this mean that with the consul template method, it will automatically restart the pods already, or that this feature would be dependent upon that?

**Comment by bonifaido** [comment]
No, it doesn't restart but you are allowed to ask consul-template to signals the other process in the pod: https://github.com/banzaicloud/bank-vaults/blob/master/docs/mutating-webhook/consul-template.md#consul-template
