### ISSUE TITLE
deploymentForConfigurer should annotate with external config hashes

### ISSUE THREAD

**Issue by thejmazz** [banzaicloud/bank-vaults#682]
**Is your feature request related to a problem? Please describe.**

Since `deploymentForConfigurer` maps ConfigMaps and Secrets with same labels as vault-configurator to volumes for the vault-configurator Deployment, but does not keep track of their contents, when CM/Secret contents are updated, these updated `vault-config.yml`s are not applied.

**Describe the solution you'd like**

Keep track of each CM/secrets contents via hash, annotate/label this on the vault-configurator Deployment, so that when they change, a new pod is launched.

Or perhaps just restart `vault-configurator` whenever any external configs are updated.

**Describe alternatives you've considered**

Manually delete vault-configurator Deployment so that it is recreated with updated CM/Secrets by the reconciler.

Manually delete Deployment's Pod so it is recreated.

My current workaround is ArgoCD Application has a synchronize post hook to delete the vault-configurator Pod via `kubectl delete pod -l app=vault-configurator`.

**Additional context**

Using 0.5.3.

**Comment by bonifaido** [comment]
Hi @thejmazz, I just tried to reproduce this with images built from the latest master, but I can't.

The process is the following:
- the operator creates a Vault cluster and a configurer for this cluster, it mounts the `externalConfig` block from the CR as a yaml file to the configurer
- also it checks for ConfigMaps and Secrets with the following labelSelector in the same namespaces (example): `{"labels": {"app.kubernetes.io/name":"vault-configurator","vault_cr":"vault"}}`.
- the configurer watches those mounted directories via `fsnotify`, so the if files are changing there, it re-reads them, and applies them again.

The only pod restart happens when the list of selected configmap/secret got changed (since the deployment is changed, the pod has new volume mounts). From that point fsnotify watches for changes.

**Comment by bonifaido** [comment]
Ah, probably the issue is 0.5.3 (I just noticed it in your message), please try with the master version of the operator (or 0.6.0-rc.1)!

**Comment by thejmazz** [comment]
This is what I did:

- Update vault-operator image to 0.6.0-rc.1
- Create a new Vault "vault"
- Update my external config ConfigMaps to have `app.kubernetes.io/name: vault-configurator` label
- Check that config was properly being applied

Now, edit the content of one of these ConfigMaps - all ConfigMap names stay the same, and none are added or removed. What I have been doing to test is in LDAP auth config change between

```yaml
users:
  julian:
    policies: default
```

and

```yaml
users:
  julian:
    policies: admin
```

Then log out and back in to the UI, checking if I can access policies pages (possible with admin policy).

On 0.6.0-rc.1, same issue persists - I need to delete vault-configurer Pod in order for it to relaunch and mount new version of existing ConfigMaps and apply new changes. Hence my suggestion for the operator to annotate the vault-configurer deployment with hashes of external config data within [deploymentForConfigurer](https://github.com/banzaicloud/bank-vaults/blob/2a8eeaca55461af0d822eaa408967413a2cbdd37/operator/pkg/controller/vault/vault_controller.go#L867) function.

**Comment by primeroz** [comment]
When a configmap is edited / changed kubernetes will take care of updating the content of the file that CM is mounted to , at that point the configurer should "notice" the file change and reload that specific config file and reapply all the configs in that file

In you logs for the configurer do you see the message about watching the directories where your configmaps are mounted ? 

Also, when your configmap change, could you double check the content of it inside of the configurer pod ?

Lastly, do you get any message in the logs to tell you that the configurer noticed a change and is going to reapply the configs of that file ?

**Comment by thejmazz** [comment]
> When a configmap is edited / changed kubernetes will take care of updating the content of the file that CM is mounted to , at that point the configurer should "notice" the file change and reload that specific config file and reapply all the configs in that file

Ah, I didn't know this! I remember reading the Helm trick to include CM hashes in Deployments so they get redeployed, and assumed the CMs/Secrets were static - instead that trick must just be for applications which don't handle watching files for changes.

> In you logs for the configurer do you see the message about watching the directories where your configmaps are mounted ?

Yes

> Also, when your configmap change, could you double check the content of it inside of the configurer pod ?

Yes

> Lastly, do you get any message in the logs to tell you that the configurer noticed a change and is going to reapply the configs of that file ?

Yes

Seems as though I was mistaken, since it is working now for adding a new policy. And its working now for my LDAP auth example of changing user polices. I probably did not wait long enough first time, or for whatever reason did not notice that change.
