### ISSUE TITLE
Add the ability to configure Azure Auth method 

### ISSUE THREAD

**Issue by KealanM** [banzaicloud/bank-vaults#686]
**Is your feature request related to a problem? Please describe.**
This is a feature request to allow for bank-vaults to be able to configure the Azure Auth (https://www.vaultproject.io/docs/auth/azure.html) method within Vault. This would complement the ability to use other Azure services already offered by bank-vaults consider it one more utility in the swiss army knife.

**Describe the solution you'd like**
It would be great to have the ability to configure Azure Auth as is possible today for other methods such as aws and okta. This should come in the form of being able to specific the different configuration elements require for Azure Auth in the yaml be the in the CR if using the Operator or as part of the values passed to the vault-configurer container if using the just the vault helm chart.

**Describe alternatives you've considered**
Work arounds right now would include manual configuration or creating custom shell scripts to setup Azure Auth by the CLI. While both are possible they do not fit the automated configuration ethos that bank-vaults offers today.

**Comment by bzuelke** [comment]
+1 for this to be a thing moving forward. Would be a huge benefit to have this in place.
