### ISSUE TITLE
Add HA support for Postgresql backend

### ISSUE THREAD

**Issue by rahmnathan** [banzaicloud/bank-vaults#693]
According to the Vault documentation (https://www.vaultproject.io/docs/configuration/storage/postgresql.html), Vault now supports HA with a postgresql back-end. However when attempting to deploy the latest version of Vault via the Vault operator, I get the following error message "failed to fabricate StatefulSet: more than 1 replicas are not supported without HA storage backend". 

Is this something that needs to be updated in the operator?

**Comment by bonifaido** [comment]
Hi @rahmnathan, this was added in https://github.com/banzaicloud/bank-vaults/pull/641/commits/b212a899bff75503a1c1a18fa6e3af2b26263d61 and is available in the 0.6.0-rc.1 release.

**Comment by rahmnathan** [comment]
Thanks @bonifaido !

**Comment by bonifaido** [comment]
You're welcome!
