### ISSUE TITLE
vault.security.banzaicloud.io/vault-tls-secret: should trust public CAs

### ISSUE THREAD

**Issue by neoakris** [banzaicloud/bank-vaults#700]
**Is your feature request related to a problem? Please describe.**
**Here is my setup:** 
I have 2 clusters: management cluster + workload cluster: 

management cluster runs 3 node consul cluster from helm stable + 2 node consul backed ha vault from helm incubator + some .sh files for config as code. 
nginx-ingress-controller helm stable chart was used to expose the vault server, it allowed me to expose the vault server with a public IP address while protecting it with a Network ACL that only whitelists the corporate office, a VPN, and a workload cluster.
I'm running kops on AWS, the ingress LB uses LB annotations to allow AWS Cert Manager to get a TLS cert with auto certificate rotation to work on the Classic Elastic LB.
The public LB terminates HTTPS, then on the LAN side it goes clear text to vault server. (I trust the LAN/not perfect security, but KISS/auto handles TLS rotation / I know this isn't the best way to do it, but that's for another iteration.)

workload cluster runs banzaicloud's vault-secrets-webhook using helm chart
I got everything working correctly: were a pod was able to echo a secret retrieved from vault to pod logs. It worked with these annotations: 

```
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.mycompany.com:443"
        vault.security.banzaicloud.io/vault-path: "myworkloadcluster" #poorly named annotation, this is the kubernetes auth mount path, from Bash# vault auth list 
        vault.security.banzaicloud.io/vault-role: "vault-secret-test_test_read-only" #this is a ACL policy that exists in vault. Bash# vault read auth/myworkloadcluster/role/vault-secret-test_test_read-only
        vault.security.banzaicloud.io/vault-skip-verify: "true" 
```

I didn't like the skip HTTPS certificate validation, so I set it to false, but then instead of my pod's log output ing the test secret, it'd give this error: 
"x509: certificate signed by unknown authority"

Why not trust Root CAs of the public internet by default? (It'd also get rid of the need to have a secret in every namespace, which is super annoying. All you'd have to do is use cert-manager to provision a LEF HTTPS cert for vault server, and trust LEF Public Certs by default.)

To fix it I made this: 
```
#It's sad that a Public CA isn't trusted / sad that I had to import this...
#Where this file came from: 
#Windows 10 machine connected to the VPN --> Internet Explorer --> https://vault.mycompany.com
#Click the HTTPS Lock and view certificate --> Certification Path --> Says: 
#"Starfield Class 2 Certification Authority" is a Root CA on the public internet that signed 
#the *.mycompany.com wildcard cert.
#CMD:\> certmgr
#Certificates - Current User\Trusted Root Certification Authorities\Certificates
#Right Click "Starfield Class 2 Certification Authority" --> All Tasks --> Export --> Next
#Export to format Base-64 encoded X.509 (.CER), but the rename the file ca.crt, below is the file you'll get
#Note: This Certificate is Valid from 6/29/2004 to 6/29/2034, so this is the perm ca.crt to validate vault's TLS server from/will never need to redo this
apiVersion: v1
kind: Secret
type: Opaque
metadata: 
  name: public-ca-to-verify-vault-servers-https
  namespace: vault-secret-test
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEDzCCAvegAwIBAgIBADANBgkqhkiG9w0BAQUFADBoMQswCQYDVQQGEwJVUzEl
    MCMGA1UEChMcU3RhcmZpZWxkIFRlY2hub2xvZ2llcywgSW5jLjEyMDAGA1UECxMp
    U3RhcmZpZWxkIENsYXNzIDIgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMDQw
    NjI5MTczOTE2WhcNMzQwNjI5MTczOTE2WjBoMQswCQYDVQQGEwJVUzElMCMGA1UE
    ChMcU3RhcmZpZWxkIFRlY2hub2xvZ2llcywgSW5jLjEyMDAGA1UECxMpU3RhcmZp
    ZWxkIENsYXNzIDIgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwggEgMA0GCSqGSIb3
    DQEBAQUAA4IBDQAwggEIAoIBAQC3Msj+6XGmBIWtDBFk385N78gDGIc/oav7PKaf
    8MOh2tTYbitTkPskpD6E8J7oX+zlJ0T1KKY/e97gKvDIr1MvnsoFAZMej2YcOadN
    +lq2cwQlZut3f+dZxkqZJRRU6ybH838Z1TBwj6+wRir/resp7defqgSHo9T5iaU0
    X9tDkYI22WY8sbi5gv2cOj4QyDvvBmVmepsZGD3/cVE8MC5fvj13c7JdBmzDI1aa
    K4UmkhynArPkPw2vCHmCuDY96pzTNbO8acr1zJ3o/WSNF4Azbl5KXZnJHoe0nRrA
    1W4TNSNe35tfPe/W93bC6j67eA0cQmdrBNj41tpvi/JEoAGrAgEDo4HFMIHCMB0G
    A1UdDgQWBBS/X7fRzt0fhvRbVazc1xDCDqmI5zCBkgYDVR0jBIGKMIGHgBS/X7fR
    zt0fhvRbVazc1xDCDqmI56FspGowaDELMAkGA1UEBhMCVVMxJTAjBgNVBAoTHFN0
    YXJmaWVsZCBUZWNobm9sb2dpZXMsIEluYy4xMjAwBgNVBAsTKVN0YXJmaWVsZCBD
    bGFzcyAyIENlcnRpZmljYXRpb24gQXV0aG9yaXR5ggEAMAwGA1UdEwQFMAMBAf8w
    DQYJKoZIhvcNAQEFBQADggEBAAWdP4id0ckaVaGsafPzWdqbAYcaT1epoXkJKtv3
    L7IezMdeatiDh6GX70k1PncGQVhiv45YuApnP+yz3SFmH8lU+nLMPUxA2IGvd56D
    eruix/U0F47ZEUD0/CwqTRV/p2JdLiXTAAsgGh1o+Re49L2L7ShZ3U0WixeDyLJl
    xy16paq8U4Zt3VekyvggQQto8PT7dL5WXXp59fkdheMtlb71cZBDzI0fmgAKhynp
    VSJYACPq4xJDKVtHCN2MQWplBqjlIapBtJUhlbl90TSrE9atvNziPTnNvT51cKEY
    WQPJIrSPnNVeKtelttQKbfi3QBFGmh95DmK/D5fs4C8fF5Q=
    -----END CERTIFICATE-----
---
```
Then updated the annotations to have this:
        vault.security.banzaicloud.io/vault-skip-verify: "false" #skip false means it will verify Vault Server's TLS
        vault.security.banzaicloud.io/vault-tls-secret: "public-ca-to-verify-vault-servers-https" #verify Vault Server's TLS using a secret in this namespace

**Describe the solution you'd like**
Uhh just trust public internet root CA's by default? Would make things a lot simpler.

**Describe alternatives you've considered**
I've read other people who ran into this did some weird workarounds.

**Additional context**

**Comment by bonifaido** [comment]
Root CAs are shipped by your operating systems (your app container's) package manager and hosted in the following locations where the Go can pick them up (in which vault-env is written): https://golang.org/src/crypto/x509/root_linux.go

```go
	"/etc/ssl/certs/ca-certificates.crt",                // Debian/Ubuntu/Gentoo etc.
	"/etc/pki/tls/certs/ca-bundle.crt",                  // Fedora/RHEL 6
	"/etc/ssl/ca-bundle.pem",                            // OpenSUSE
	"/etc/pki/tls/cacert.pem",                           // OpenELEC
	"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", // CentOS/RHEL 7
	"/etc/ssl/cert.pem",                                 // Alpine Linux
```

If your container image doesn't have the proper root CAs in the above locations no application can find them and trust the certs signed by them (in this case your AWS Cert Manager one). So you have to install your operating systems `ca-certificates` package, for example, https://pkgs.alpinelinux.org/package/v3.10/main/x86/ca-certificates in case of an Alpine container.
In the case of a `scratch` Docker container application, people usually install the package in a multi-stage build and copy the cert to the final app container based on `scratch`. After that, all the great cert provider certs will work.
