### ISSUE TITLE
VAULT_ADDR getting reset when running a Job

### ISSUE THREAD

**Issue by audrey-brightloom** [banzaicloud/bank-vaults#709]
I've got a db migrate job that needs to run as a pre-install hook - however VAULT_ADDR is getting set twice:

    - name: VAULT_ADDR
      value: https://vault.default:8200
    - name: VAULT_ADDR
      value: https://vault:8200
    - name: VAULT_SKIP_VERIFY
      value: "false"
    - name: VAULT_PATH
      value: kubernetes
    - name: VAULT_ROLE
      value: default

the first one is coming from the annotation and is correct. i'm not sure where the second one is coming from. the interesting thing is this doesn't happen with the Deployment only in the Job. 

i passed the same command to both Job and Deployment: 

command:  ["/bin/sh", "-c", "bin/python migrate.py migrate --run-syncdb"]

**Comment by bonifaido** [comment]
Interesting, I'm double-checking the code now. Could you please check the Job and the Deployment have the same annotations on the Pod level?

**Comment by audrey-brightloom** [comment]
Both are setting:

    vault.security.banzaicloud.io/vault-addr: 'https://vault.default:8200'
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls

**Comment by bonifaido** [comment]
Could you please provide the full manifest for both cases? I try to reproduce.

**Comment by audrey-brightloom** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app.kubernetes.io/instance: auth
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: auth
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: auth-0.1.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
      app.kubernetes.io/instance: auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth
        app.kubernetes.io/instance: auth
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
        vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    spec:
      containers:
        - name: auth
          image: "repo-path"
          imagePullPolicy: Always
          command: ["sh", "-c", ". bin/activate && bin/uwsgi uwsgi.ini"]
          ports:
            - name: auth
              containerPort: 3060
          env:
            - name: SECRET_KEY
              value: vault:secret/data/service/auth/stage/secret_key#key
            - name: DATABASE_URL
              value: vault:secret/data/accounts/aws/stage/rds#db_url
            - name: DEFAULT_FROM_EMAIL
              value: no-reply@foo.com
            - name: REDIS_URL
              value: redis-url
            - name: DJANGO_SETTINGS_MODULE
              value: django.settings`

`apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "vault.security.banzaicloud.io/vault-addr": "https://vault.default:8200"
    "vault.security.banzaicloud.io/vault-tls-secret": vault-tls
spec:
  activeDeadlineSeconds: 120
  template:
    name: db-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: "repo-path"
          command: ["/bin/sh", "-c", "bin/python manage.py migrate --run-syncdb"]
          env:
            - name: SECRET_KEY
               value: vault:secret/data/service/auth/stage/secret_key#key
            - name: DATABASE_URL
              value: vault:secret/data/accounts/aws/stage/rds#db_url
            - name: DJANGO_SETTINGS_MODULE
              value: django.settings`

sanitized a bit

**Comment by bonifaido** [comment]
Not able to reproduce this with the latest version. Could you please check it against that one as well (0.6.2)?
