### ISSUE TITLE
Same instancename not possible across different namespaces

### ISSUE THREAD

**Issue by dk89** [banzaicloud/bank-vaults#713]
**Describe the bug**:
Vault instances cannot have the same name in two different namespaces. The vault-operator ist crashing trying to create the vault-configurer in the second namespace.

**Expected behaviour**:
As discussed in the Slackchannel Instancenaming shouldn't be unique in the cluster.

**Steps to reproduce the bug**:
- Create two namespaces (i.e. vault-dev and vault-prod)
- Deploy a cr.yaml with the same metadata.name in each namespace

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.14.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): PKE
- bank-vaults version (e.g. 0.4.17):  0.53
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):

`{"level":"error","ts":1571400763.884637,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"vault-controller","request":"vault-prod/vault","error":"failed to create/update configurer deployment: Deployment.apps \"vault-configurer\" is invalid: [spec.template.spec.volumes[1].name: Duplicate value: \"vault-configurer\", spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value: \"/config/vault-configurer\": must be unique]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88"}`

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
metadata:
 name: "vault"

/kind bug

**Comment by bonifaido** [comment]
Fixed via https://github.com/banzaicloud/bank-vaults/pull/710, thanks @dk89 for reporting this!
