### ISSUE TITLE
Update the charts app versions and image tags to use the 0.6.0 release

### ISSUE THREAD

**Issue by KealanM** [banzaicloud/bank-vaults#741]
**Is your feature request related to a problem? Please describe.**
With 0.6.0 released it would be good to have the vault, operator and webhook charts use this release.

**Describe the solution you'd like**
Latest version of the charts pull version 0.6.0 of the bank-vaults, operator and web-hook containers.

**Describe alternatives you've considered**
Updating my local values, but this would be down each consumer.

**Comment by bonifaido** [comment]
FYI: https://github.com/banzaicloud/bank-vaults/pull/740

**Comment by KealanM** [comment]
You beat me too it so :)
