### ISSUE TITLE
Question / feature request: bypass webhook on selected deployments

### ISSUE THREAD

**Issue by maciejqantas** [banzaicloud/bank-vaults#742]
Not sure if that feature exists already and I'm not aware of it, or if it's something that could be added.

I'd like to be able to annotate my deployments in a way that makes the webhook ignore them. 

My namespace is properly configured with a namespace selector and the webhook tries to inject secrets into all deployments. In my case, a few deployments do not have secrets and I'd like to bypass the webook, with something like `vault.security.banzaicloud.io/skip=true`.

Is that currently possible? If not, can it be added?

**Comment by pbalogh-sa** [comment]
@maciejqantas The webhook only mutate the pods which are annotated with `vault.security.banzaicloud.io/...`. If you don't annotate the pod templates, the webhook won't mutate it.

**Comment by maciejqantas** [comment]
Thanks @pbalogh-sa.

Just to make sure I follow - the webhook kicks in if the pod spec has environment variables whose values use the `vault:path/to/secret#attribute` value, correct?

if that's the case, I would still like to disable the webhook for a given pod. I have an unusual use case where I still have env vars pointing to secrets in my pod, but I do not wish to read them from vault.

**Comment by pbalogh-sa** [comment]
@maciejqantas TThis makes sense. We will figure out how we can implement it. I think the best way would be using the `objectSelector` in the `mutatingWebhookConfiguration`, but this [feature](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector) is only reachable above version 1.15 of kubernetes.

**Comment by pbalogh-sa** [comment]
If we use the `objectSelector`, we will just set a proper label in the pod we don't want to mutate.

You can edit the deployed `mutatingWebhookConfiguration` and put the `objectSelector` to the `webhook` section in the case of version 1.15 of kubernetes. And after it, you can label your pods and the webhook won't trigger.

**Comment by pbalogh-sa** [comment]
We will definitely implement this feature.

**Comment by maciejqantas** [comment]
thanks a lot @pbalogh-sa!

is there any option for an implementation working on 1.14? I'm running k8s on EKS and 1.15 is not available there yet.

**Comment by pbalogh-sa** [comment]
@maciejqantas You can use `namespaceSelector` in `mutatingwebhookConfiguration` but maybe it doesn't fit your current needs. There isn't a quick fix for a more sophisticated selection.

**Comment by maciejqantas** [comment]
@pbalogh-sa it does not, sadly. It needs to be a deployment within an otherwise vault-enabled namespace.

I've worked around it for now. Looking forward to the target solution :)

**Comment by pbalogh-sa** [comment]
We considered solutions in the case of k8s version below 1.14 and we didn't find a good one.  If we use annotations in pod templates, the mutatingWebhookConfiguration will send the `podSpec` to the webhook in this case as well, so the real skipping won't happen. The only proper way in our opinion to use `namespaceSelector` for skipping mutation in this case.
