### ISSUE TITLE
Secrets webhook is not run on container with custom docker image and no command

### ISSUE THREAD

**Issue by joseph-kimberley** [banzaicloud/bank-vaults#746]
**Describe the bug**:
When I use the secrets-webhook on a pod with a custom image/private docker registry and no command, the copy-vault-env container is not run.

Using a public docker image like alpine works.
Using a custom image/private docker registry but with a command to print the ENV variable, also works.

Also having one bad container will not run copy-vault-env for any containers in the file.

**Expected behaviour**:
The secrets-webhook to run copy-vault-env on any docker image, with or without a command.

**Steps to reproduce the bug**:
Make a Kubernetes deployment YAML file (see below)

Create using the command `kubectl create -f test.yaml`. Uncomment the other container definitions to see how it doesn't work properly with a custom image/private docker registry and no command.

**Environment details**:
- Kubernetes version: Client=v1.14.1, Server=v1.15.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Bare-metal deployment
- bank-vaults version (e.g. 0.4.17): v0.5.1
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): -
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

      apiVersion: apps/v1beta1
      kind: Deployment
      metadata:
        name: test
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              app: test
            annotations:
              vault.security.banzaicloud.io/vault-role: "<vault-role>"
          spec:
            serviceAccountName: <vault-service-account>
            imagePullSecrets:
              - name: <docker-secret>

            ## DOESN'T WORK
            containers:
              - name: test
                image: <private-registry>/<custom-image>
                env:
                  - name: TEST_ENV
                    value: "<vault-secret-path>"

            ## WORKS
            # containers:
            #   - name: test
            #     image: alpine
            #     env:
            #       - name: TEST_ENV
            #         value: "<vault-secret-path>"

            ## WORKS
            # containers:
            #   - name: test
            #     image: <private-registry>/<custom-image>
            #     command: ["sh", "-c", "echo $TEST_ENV"]
            #     env:
            #       - name: TEST_ENV
            #         value: "<vault-secret-path>"

/kind bug

**Comment by bonifaido** [comment]
Could you provide any logs from the webhook itself, so we can see what was the issue when accessing the registry?

**Comment by joseph-kimberley** [comment]
This appears to be the logs that occur when I create the pod:

    time="2019-11-15T14:30:24Z" level=info msg="found credentials for registry <my-registry> in pod imagePullSecret: <my-secret>"
    time="2019-11-15T14:30:24Z" level=info msg="I'm using registry <my-registry>"
    2019/11/15 14:30:24 registry.ping url=<my-registry>/v2/
    time="2019-11-15T14:30:24Z" level=error msg="admission webhook error: cannot create client for registry: Get <my-registry>/v2/: http: non-successful response (status=403 body=\"{\\n \\\"errors\\\" : [ {\\n \\\"status\\\" : 403,\\n \\\"message\\\" : \\\"Forbidden\\\"\\n } ]\\n}\")

The docker secret is fine, and no logs appear when running a pod that works.

**Comment by bonifaido** [comment]
Can you ping <my-registry>/v2 registry with the credentials inside my-secret?

**Comment by joseph-kimberley** [comment]
Yeah that works

**Comment by bonifaido** [comment]
What kind of registry are you using? Harbour maybe?

**Comment by joseph-kimberley** [comment]
It's an Artifactory Docker registry

**Comment by bonifaido** [comment]
What was your ping command? Because the standard docker registry ping is `GET /v2/` ([API Version Check](https://docs.docker.com/registry/spec/api/#api-version-check)) but it seems that Artifactory doesn't support that, at least I tried it now, and I got a 403 as well.

**Comment by bonifaido** [comment]
Yes, my intention was correct, `/v2/` gives 401/403 for any kind of requests, either with or without credentials, so this is not a bank-vaults, but an Artifactory issue **because this (/v2/) endpoint is not implemented correctly** (according to Docker registry specs), see: https://www.jfrog.com/jira/browse/RTFACT-9232 and here https://www.jfrog.com/jira/browse/RTFACT-16173

I don't see the point waiting on JFrog to fix this and rollout to all possible JFrog and bank-vaults users, so I will fork the Go docker client we are using, and patch this there.
We had issues with Harbor as well since it is also not standard registry specs conformant, see: https://github.com/banzaicloud/bank-vaults/issues/712.

I see people talking about Nginx configuration (I'm no artifactory expert here), can't you just add a handler to this endpoint in Nginx and return HTTP 200 there to overcome this issue?
