### ISSUE TITLE
vault-secrets-webhook: issue parsing imagePullSecrets

### ISSUE THREAD

**Issue by chap-dr** [banzaicloud/bank-vaults#761]
**Describe the bug**:
vault-secret-webhook fails to pase imagePullSecrets when docker server is set to https://index.docker.io/v1 

There is no visable error printed in the logs, all that is written is `found no credentials for registry index.docker.io, assuming it is public`

setting DEFAUL_IMAGE_PULL_SECRET and DEFAULT_IMAGE_PULL_SECRET_NAMESPACE env vars does not have any effect either. 

Running:`kubectl create secret docker-registry dockerhub --docker-username=${DOCKER_USERNAME} --docker-password=$DOCKER_PASSWORD`

Results in a .dockerconfigjson with a values of: 
```
{
    "auths": {
        "https://index.docker.io/v1/": {
            "username": "redacted",
            "password": "redacted",
            "auth": "redacted"
        }
    }
}
```

The issue appears to be with the if statement here: https://github.com/banzaicloud/bank-vaults/blob/f36b088dec75fd71f6cd860318ca3250bee72819/cmd/vault-secrets-webhook/registry/registry.go#L203

k.Image have a value of: `index.docker.io/ORG/IMAGE_NAME:TAG`, and registryName is: index.docker.io/v1” it seems that the if statement fails as `index.docker.io` does not match `index.docker.io/v1` 

Later on a message is printed using k.registryName saying `"found no credentials for registry index.docker.io, assuming it is public"` so somewhere along the way it gets set correct.

When appending `--docker-server` to the dockerhub kubectlcreate command:`kubectl create secret docker-registry dockerhub --docker-username=${DOCKER_USERNAME} --docker-password=$DOCKER_PASSWORD --docker-server=https://index.docker.io` imagePullSecrets is read and used correctly and the webhook work as expected. 

**Expected behaviour**:`kubectl create secret docker-registry dockerhub --docker-username=${DOCKER_USERNAME} --docker-password=$DOCKER_PASSWORD` should be enough to make the webhook recognize the imagePullSecrets and use.

**Steps to reproduce the bug**:
Add a dockerhub secret and let kubectl fill out the docker-server value with its defaults to an application that has a webhook annotation, Logs of the webhook will show `found no credentials for registry index.docker.io, assuming it is public"`

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.14.8
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): GKE
- bank-vaults version (e.g. 0.4.17): Only using the webhook, Started out with version 0.5.3, bumped it to 0.6.1, latests and master during debugging, error persists throughout.
- Install method (e.g. helm or static manifests): helm template. 
- Logs from the misbehaving component (and any other relevant logs): No logs of note is printed, even with debug=true. 
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
.dockerconfigjson JSON that does **not** work:
```
{
    "auths": {
        "https://index.docker.io/v1/": {
            "username": "redacted",
            "password": "redacted",
            "auth": "redacted"
        }
    }
}
```

.dockerconfigjson JSON that **works**:
```
{
    "auths": {
        "https://index.docker.io/": {
            "username": "redacted",
            "password": "redacted",
            "auth": "redacted"
        }
    }
}
```

/kind bug

**Comment by bonifaido** [comment]
Fix in https://github.com/banzaicloud/bank-vaults/pull/779
