### ISSUE TITLE
secrets webhook doesn't work without command

### ISSUE THREAD

**Issue by hacktron95** [banzaicloud/bank-vaults#764]
**Describe the bug**:
i've a simple deployment 
`
        vault.security.banzaicloud.io/vault-addr: "http://vault:8200"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
` 
 file (with the above annotations), that will retrieve some values from vault, it works fine and the webhook-container injects the secret fine and turn it's own status to be `complete`,  if i passed -container-command value
`containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: "vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY"`
but once i remove this container-command and just pass envs to the container
 `
containers:
      - name: alpine
        image: my-company/another-container-that-expects-AWS_KEY-env
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: "vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY"`
the webhook-container doesn't even start or inject any secrets, and i get the value as a string.
**Expected behaviour**:
i expected vault-webhook to inject the secrets in my container,

**Steps to reproduce the bug**:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-secrets
  template:
    metadata:
      labels:
        app: hello-secrets
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://vault:8200"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        # vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    spec:
      serviceAccountName: default
      containers:
        - name: image
          image: image-that-expects-an-env
          env:
            - name: ENV_STRING
              value: "vault:secret/data/HELLO/SECRET#KEY"
      imagePullSecrets:
        - name: regcred`

**Environment details**:
- Kubernetes version: v1.15.3
- on prem cluster
- vault-secrets-webhook	chart-v: 0.5.5        	app-v:0.5.1 
- Install method (static yaml files (operator-rbac, operator, rbac, cr)):
- Logs from the misbehaving component (and any other relevant logs):
/kind bug

**Comment by pbalogh-sa** [comment]
@hacktron95  Could you provide us logs of the vault-secrets-webhook pod?

**Comment by hacktron95** [comment]
hello @pbalogh-sa , sorry for missing that
--
`vault-secrets-webhook time="2019-11-26T08:00:01Z" level=info msg="found no credentials for registry index.docker.io, assuming it is public"                                                                                                                                   
vault-secrets-webhook time="2019-11-26T08:00:01Z" level=info msg="I'm using registry https://index.docker.io"                                                                                                                                                                 
vault-secrets-webhook 2019/11/26 08:00:01 registry.ping url=https://index.docker.io/v2/                                                                                                                                                                                       
vault-secrets-webhook 2019/11/26 08:00:04 registry.manifest.get url=https://index.docker.io/v2/owner/repo/manifests/production repository=owner/repo reference=production                                                                                                   
vault-secrets-webhook time="2019-11-26T08:00:06Z" level=error msg="admission webhook error: cannot download manifest for image: Get https://index.docker.io/v2/owner/repo/manifests/production: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\
\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":[{\\\"Type\\\":\\\"repository\\\",\\\"Class\\\":\\\"\\\",\\\"Name\\\":\\\"owner/repo\\\",\\\"Action\\\":\\\"pull\\\"}]}]}\\n\")"`
this is what it keeps printing, nothing else
despite the fact that the cluster has the docker creds and it already pulled the image and ran it.

**Comment by pbalogh-sa** [comment]
@hacktron95 The problem is the webhook hasn't any permission to the registry due to the `imagePullsecret` `regcred` doesn't contain proper docker credentials. In this case, the webhook cannot get the command defined in the image from the registry. If you define the command explicitly, the webhook won't try to get the command from the registry. 

Is the docker API version and credentials properly defined in your `regcred` secret?

**Comment by hacktron95** [comment]
@pbalogh-sa thanks for your reply, at first i was passing my docker hub creds as a token
then i passed it as a normal secrets `kubectl create secret`
in both cases, i can pull the image, and runs it fine
so if it was auth issue or creds issue, i should not be able to pull the image in the first place,
anyways i tried to pass 
`{"auths":{"https://index.docker.io/v2/":{"username":"me","password":"pass","auth":"TOKEN"}}}`
and also tried to change the api version to `v1` , still gives me the same output on the secrets webhook, and still able to pull without any issues

**Comment by pbalogh-sa** [comment]
@hacktron95 Thanks for your answer. We will investigate it because it seems a bug in the webhook.

**Comment by bonifaido** [comment]
I just found the bug, PR with incoming.

**Comment by bonifaido** [comment]
Duplicate of https://github.com/banzaicloud/bank-vaults/issues/761

**Comment by bonifaido** [comment]
Fix in https://github.com/banzaicloud/bank-vaults/pull/779

**Comment by wiltonfelix** [comment]
Hello that is the problem to me.

**Describe the bug:**
my deployment config 

```apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault:8200" # optional, the address of the Vault service, default values is https://vault:8200
        vault.security.banzaicloud.io/vault-role: "apps_prod_roles" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true" # optional, skip TLS verification of the Vault server certificate
        vault.security.banzaicloud.io/vault-path: "kubernetes" # optional, the Kubernetes Auth mount path in Vault the default value is "kubernetes"
    spec:
      serviceAccountName: apps-prod
      containers:
      - name: alpine
        image: alpine
        command: ["sh", "-c", "echo $AWS_SECRET_ACCESS_KEY && echo going to sleep... && sleep 10000"]
        env:
        - name: AWS_SECRET_ACCESS_KEY
          value: vault:secret/data/valami/aws#AWS_SECRET_ACCESS_KEY```

**Env in conteiner**

``` vault-test-565fbfbfc-gc9lr                                        1/1     Running       0          15s
[will@unknown test-projet]$ kubectl logs vault-test-565fbfbfc-gc9lr -n prod 
time="2020-02-10T16:40:37Z" level=info msg="Received new Vault token"
time="2020-02-10T16:40:37Z" level=info msg="Initial Vault token arrived"
s3cr3t
going to sleep...
[will@unknown test-projet]$ kubectl exec -ti vault-test-565fbfbfc-gc9lr sh -n prod 
/ # env |grep aws
AWS_SECRET_ACCESS_KEY=vault:secret/data/valami/aws#AWS_SECRET_ACCESS_KEY
/ # 
```
OBS: With the command echo return the correct value to env, but inside the pod that value is a string.

**Expected behaviour:**
i expected vault-webhook to inject the secrets in my container.


**Logs webhook**

```
time="2020-02-10T14:43:29Z" level=info msg="found image nginx:stable in cache"
time="2020-02-10T14:50:56Z" level=info msg="found no credentials for registry https://index.docker.io, assuming it is public"
time="2020-02-10T14:50:56Z" level=info msg="I'm using registry https://index.docker.io"
2020/02/10 14:50:56 registry.manifest.get url=https://index.docker.io/v2/library/alpine/manifests/latest repository=library/alpine reference=latest
2020/02/10 14:50:56 registry.blob.download url=https://index.docker.io/v2/library/alpine/blobs/sha256:e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a repository=library/alpine digest=sha256:e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a
time="2020-02-10T14:53:41Z" level=info msg="found no credentials for registry https://index.docker.io, assuming it is public"
time="2020-02-10T14:53:41Z" level=info msg="I'm using registry https://index.docker.io"
2020/02/10 14:53:41 registry.manifest.get url=https://index.docker.io/v2/library/alpine/manifests/latest repository=library/alpine reference=latest
2020/02/10 14:53:41 registry.blob.download url=https://index.docker.io/v2/library/alpine/blobs/sha256:e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a repository=library/alpine digest=sha256:e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a
```

**Environment details:**

Kubernetes version: v1.14.8-gke.33
on prem cluster
vault-secrets-webhook chart- v0.8.0
/kind bug
