### ISSUE TITLE
Support etcd backend

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#78]
Not a bug, but a feature request.

bank-vaults support the default cloud storage, like s3 for aws. It is a good idea to package backend operators based on config. For example if vault config contains backend as etcd then an etcd-operator and etcd cluster should be deployed along with vault.

**Comment by bonifaido** [comment]
@raoofm please see https://github.com/banzaicloud/bank-vaults/pull/79 for the current implementation we have drafted.
