### ISSUE TITLE
Hacked

### ISSUE THREAD

**Issue by xavier007bb** [banzaicloud/bank-vaults#801]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:

**Expected behaviour**:
A concise description of what you expected to happen.

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- bank-vaults version (e.g. 0.4.17):
- Install method (e.g. helm or static manifests):
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by bonifaido** [comment]
Seems like spam.
