### ISSUE TITLE
[webhook] OwnerReferences for vault-agent ConfigMap missing if pod has a name

### ISSUE THREAD

**Issue by marcoreni** [banzaicloud/bank-vaults#804]
**Describe the bug**:
I'm creating a standalone pod with a CtConfigMap annotation. After the pod deletion, the "vault-agent-config" configmap does not get deleted.

**Expected behaviour**:
The ConfigMap should be garbage collected.

**Steps to reproduce the bug**:
1. Create a pod with a Consul-Template configMap configuration
2. Delete the pod

**Additional context**:
It seems that in the vault-agent-config configmap created by the webhook for the pod the `ownerReferences` object is missing, therefore there's no link for the K8s garbage collector.

According to https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-secrets-webhook/main.go#L479 the OwnerReferences object is retrieved from the pod only if the name is not set (I assume this is for when the pod is part of a [replica|daemon]Set). In my case, the pod name is set, hence the vault-agent-config map name is taken from there, but the OwnerReferences object is missing.

I think the handling of OwnerReferences object should be separate from the name handling. If pod does not have an OwnerReferences object, one should be created and it should reference the pod, so that the configmap will be removed once the pod is deleted.

/kind bug

**Comment by bonifaido** [comment]
Hi @marcoreni, does your Pod instance have any ownerReferences set? If not, we can't really help here, otherwise, this is a bug, which can be solved if the Pod has ownerReferences, but if not, we don't know the UID of the Pod in this phase so it would be hard to get it and update the configMap later on (adds too much state to the current code).

**Comment by marcoreni** [comment]
I totally missed the uid while sweeping the ownerReferences docs, sorry for that. 

I assume there's no way to work around this, unless we find a way to remove the need of this configmap.. 

Has anyone considered the possibility to migrate from Consul Template to Vault Agent 1.3 (that introduced the capability of parsing Templates)? AFAIU, this would remove the need of Vault Agent init-container (at the cost of probably defining all configuration values inside the consul-template configmap object) so the additional vault-agent-configmap wouldn't be required anymore.. [ it would also probably solve https://github.com/banzaicloud/bank-vaults/issues/464, but that's a different story :) ]

**Comment by bonifaido** [comment]
Yes we definitely need to evaluate the new vault-agent feature! :-)

i have found a possible bug in the setting of the owner reference in the meantime which doesn't solve this issue entirely but tries to get the reference in all situations.
