### ISSUE TITLE
Using secrets in another namespace

### ISSUE THREAD

**Issue by TomaszKlosinski** [banzaicloud/bank-vaults#807]
Hello,

I've followed your example from your blog post of injecting secrets into pods:
https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/

And it works like a charm in the same namespace where vault lives (i.e. default). However, I'd like to deploy vault in one namespace and use the secrets in other namespaces: my-app-dev, my-app-stage, prom-monitoring, etc. Is it possible? Is there documentation how I can achieve this? 

I've tried to test this scenario by deploying your `deploy/test-deployment.yaml` in another namespace, but then my pod is hanging in `Init` state:
```
test-vault       hello-secrets-775c7c755c-9cmg2                                0/1     Init:0/2    0          2m58s
```

The issue seems to be that it can't mount `vault-tls`:
```
Warning  FailedMount  15s (x7 over 47s)  kubelet, worker-03.kube.local  MountVolume.SetUp failed for volume "vault-tls" : secret "vault-tls" not found
```

Thanks in advance for any help!

**Comment by pbalogh-sa** [comment]
@TomaszKlosinski  How did you deploy your vault instance? Did you use the operator?

**Comment by TomaszKlosinski** [comment]
Thanks, I've just realised that the namespaces are whitelisted. I've used the "vswh" namespace for test and then it worked. Thanks for the help!

**Comment by TomaszKlosinski** [comment]
Ok, I've finally made it work. 

I've set `caNamespaces: ["*"]` and `bound_service_account_namespaces: ["*"]` in `cr.yaml`, and then vault-operator was throwing an error:
```
E1218 12:33:20.869887       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:default:vault-operator" cannot list resource "namespaces" in API group "" at the cluster scope
```

So, I've modified this list of vault-operator's RBAC rules:
https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/operator-rbac.yaml#L26
to contain: 
```
    verbs:
      - list
      - get
      - watch
```

And then it started working for all namespaces.

**Comment by pbalogh-sa** [comment]
@TomaszKlosinski  Thanks! Any contribution is welcome. You can submit a PR with your fix.
