### ISSUE TITLE
Question: How to prevent secret env variables from leaking?

### ISSUE THREAD

**Issue by povils** [banzaicloud/bank-vaults#810]
First of all I love the solution!

My question is do you have any suggestions of how to keep these secret env variables from exposure. Some examples:
 - applications accidentally prints all environment variables with debug mode
 - applications passing all environments to child processes
 - some libraries prints all envs when crashes
 
Probably there are more. I know that one simple solution is to make applications responsible for dealing with this(dont run in debug mode, sanitizing etc). But then it becomes a tribal knowledge which is very hard to maintain. Thus I am asking are there any alternatives?

One way I can see is to pass secrets in file using beloved tmpfs that way all accidents would be solved. It could be up to a user to choose if they want to use a file or envars.

Any other ideas? :)

Cheers,
Povilas

**Comment by povils** [comment]
Hi again,
I can see that this solution is kind of solving my concerns :)
https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/

**Comment by bonifaido** [comment]
We have solved this a long time ago (with consul-template): https://github.com/banzaicloud/bank-vaults/blob/master/docs/mutating-webhook/consul-template.md
