### ISSUE TITLE
Injecting consul-template via webhook stalls on initcontainer when Istio mTLS is employed

### ISSUE THREAD

**Issue by funkypenguin** [banzaicloud/bank-vaults#822]
**Describe the bug**:

When using Istio mTLS, and following https://github.com/banzaicloud/bank-vaults/blob/master/docs/mutating-webhook/consul-template.md, by using the `vault.security.banzaicloud.io/vault-ct-configmap` annotation, a pod can't run beyond the InitContainer stage.

Why? Because Istio's CNI causes all outbound traffic to be redirected to the port of the istio-proxy sidecar, even if that sidecar is not running _yet_. Effectively, unless worked around with excludeOutboundIPs or excludeOutboundPorts, an initcontainer will have no egress network connectivity when mTLS is enforced.

Note that this is similar to the issue raised in #773 

**Expected behaviour**:

InitContainers should be avoided due to the complications with Istio mTLS.

**Steps to reproduce the bug**:

1. Create Istio-enabled namespace, deploy vault with Istio mTLS enabled
2. Deploy pod with `vault.security.banzaicloud.io/vault-ct-configmap` set to valid configmap, per 
https://github.com/banzaicloud/bank-vaults/blob/master/docs/mutating-webhook/consul-template.md
3. Pod will fail at the vault-agent init container, logging "connection refused" when attempting to connect to Vault
4. Optionally, add `traffic.sidecar.istio.io/excludeOutboundPorts: "8200"` annotation to pod to permit egress connection to Vault, to validate (this is my current workaround, thanks @waynz0r )

**Additional context**:

A solution was discussed in https://community-banzaicloud.slack.com/archives/CFJJW9L94/p1578513527045200

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.16.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Bare metal
- bank-vaults version (e.g. 0.4.17): latest
- Install method (e.g. helm or static manifests): helm

/kind bug

**Comment by bonifaido** [comment]
Fixed in #823 with vault-agent support.
