### ISSUE TITLE
Make etcd configurable

### ISSUE THREAD

**Issue by raoofm** [banzaicloud/bank-vaults#83]
Below etcd version is hard coded 
https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/stub/handler.go#L430

in general other etcd config should be configurable.

**Comment by bonifaido** [comment]
I agree. This doesn't sound like a huge (at least for the version). Would you mind opening a PR with the  proposed changes?

**Comment by matyix** [comment]
Fixed by #164
