### ISSUE TITLE
Renew dynamic secrets (env vars)

### ISSUE THREAD

**Issue by dklesev** [banzaicloud/bank-vaults#836]
**Is your feature request related to a problem? Please describe.**
Yes.
As of now to be able to renew the lease of dynamic secrets one needs to use consul templates. However, it seems not to be possible to renew a lease of an environment variable.

**Describe the solution you'd like**
1. Add ability to vault-env to retrieve the `lease_id`, `lease_duration`, `lease_renewable`.
2. Save it to a shared directory (empty-dir).
3. Start sidecar container watching the shared directory and renew all leases within it.
4. If no dynamic secrets are used, steps above are not needed.

**Describe alternatives you've considered**
Parts of this:
https://medium.com/@gmaliar/dynamic-secrets-on-kubernetes-pods-using-vault-35d9094d169

**Additional context**
RabbitMQ:
```
$ vault read rabbitmq/creds/my-role
Key                Value
---                -----
lease_id           rabbitmq/creds/my-role/XEl5Chkthg2xiGgMgfs7CFbT
lease_duration     336h
lease_renewable    true
password           e98ea98d-c6fe-7b1a-fe75-d1f166542494
username           root-cc0f6899-8c68-9173-904b-c4d479cd1c68
```

**Comment by bonifaido** [comment]
Hi @dklesev, this is something that we are currently working on actively, it will come in the following weeks, stay tuned! 🤓

**Comment by bonifaido** [comment]
FYI: https://github.com/banzaicloud/bank-vaults/pull/856

**Comment by cablespaghetti** [comment]
@bonifaido Good work! However can you explain how this would work, i can't quite work it out from the code? I don't see any code to restart the application to pick up the updated environment variable.

**Comment by bonifaido** [comment]
Hi @cablespaghetti, I think we don't need to restart the application in this case, since the environment variables won't change, for example, you have a dynamic database credentials engine enabled, with credential lease time of 10minutes, the job of vault env would be to call vault within 10m to renew the lease and the credential will not change in this case.

**Comment by bonifaido** [comment]
Yeah I guess I know what you mean, so what happens after max_ttl expires. :)

**Comment by bonifaido** [comment]
That should be added to the implementation as well! :)

**Comment by cablespaghetti** [comment]
I'm very new to Vault and haven't really explored dynamic secrets so I didn't know about renewing the secret without actually changing the value. Glad I helped though! 😁

**Comment by rgaoistheone** [comment]
Sorry , just bump into this similar requests .
My question is ,what should I to to "Tell vault-env to renew the lease" . Through annotations or any configs? I can't find any relevant documentations , any tips will be appreciated !
