### ISSUE TITLE
security@banzaicloud.com email bounced

### ISSUE THREAD

**Issue by BryanDollery** [banzaicloud/bank-vaults#841]
I emailed a vulnerability to your security@banzaicloud.com as per your instructions in the github security tab, but it bounced.

**Comment by bonifaido** [comment]
Hi Bryan,

could you please draft it here https://github.com/banzaicloud/bank-vaults/security/advisories?

Thank you

**Comment by bonifaido** [comment]
If not please send it to info@banzaicloud.com

**Comment by BryanDollery** [comment]
Done, thx.
