### ISSUE TITLE
Ability to dynamically fetch keys from secret path

### ISSUE THREAD

**Issue by oba11** [banzaicloud/bank-vaults#845]
**Is your feature request related to a problem? Please describe.**
I could be wrong but I think current implementation requires that the key is specified e.g `vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY`. I want to ask if it's possible to dynamically fetch the keys from path as supported by Hashicorp [vault agent sidecar injector](https://www.vaultproject.io/docs/platform/k8s/injector/).

**Describe the solution you'd like**
I will like to be able to do something like

```
spec:
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.default.svc.cluster.local:8200"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/agent-inject-secret-helloworld: "secret/helloworld"
        vault.hashicorp.com/agent-inject-template-helloworld: |
	  {{ with secret "secret/helloworld" }}
	    {{ range $k, $v := .Data }}
	      {{ $k }}: {{ $v }}
	    {{ end }}
	  {{ end }}
        vault.hashicorp.com/role: "myapp"
```

Ref:
https://www.vaultproject.io/docs/platform/k8s/injector/
https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/

**Describe alternatives you've considered**
I've considered deploying Hashicorp [vault agent sidecar injector](https://www.vaultproject.io/docs/platform/k8s/injector/) but doesn't support standalone agent sidecar injector deployment with the [helm chart](https://github.com/hashicorp/vault-helm).

**Comment by bonifaido** [comment]
Hi @oba11,

I'm not sure if I understand the context fully, but the bank-vaults webhook provides two ways for injecting secrets into Pods:

- **injecting via environment variables and Kubernetes Secrets (without any sidecar):**
   the example, that you have provided for example:
   ```yaml
    env:
    - name: AWS_SECRET_ACCESS_KEY
      value: "vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY"
   ```
- **injecting via volume sharing (the sidecar way):**
  for this way we previously used consul-template sidecar (for a year or so) but now vault-agent is supported as well, this sidecar works the same way as the Hashicorp version which got released in December.

What would be your exact use case here, could you provide an example what you need? Knowing that we might help further.

**Comment by oba11** [comment]
Hi @bonifaido apologies for replying late...
What I meant was to be able to use dynamic template rendering implemented by Hashicorp. Will give it a spin to see how if it works.

Thanks so much and I will close this issue and reopen if I get stuck

**Comment by abdennour** [comment]
@oba11  I wonder why you close the issue !
Vault injection using annotations is the official way provided by Hashicorp.

This is powered by a new tool called [vault-k8s](https://www.vaultproject.io/docs/platform/k8s/injector/index.html), which leverages the Kubernetes [Mutating Admission Webhook ](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/)to intercept and augment specifically annotated pod configuration for secrets injection using Init and Sidecar containers. (Demo [here](https://youtu.be/xUuJhgDbUJQ))

If we get it supported by Banzai operator, it will be great.

**Comment by bonifaido** [comment]
Just for the record, @abdennour the Banzai vault-secrets-webhook is capable of the same thing for a very long time.

With the Vault-Agent sidecar: https://github.com/banzaicloud/bank-vaults/blob/master/deploy/test-deploy-va.yaml

Bonus, without sidecar: https://github.com/banzaicloud/bank-vaults/blob/master/deploy/test-dynamic-env-vars.yaml

**Comment by abdennour** [comment]
Thank you @bonifaido  for letting me know that. 
I would go with  Banzai vault-secrets-webhook  definitely.

**Comment by laukaichung** [comment]
> Vault-Agent sidecar

Hello,
I've just deployed https://github.com/banzaicloud/bank-vaults/blob/master/deploy/test-deploy-va.yaml on Minikube without changing anything.

Here is the output:

````
chown: /vault/config/config.hcl: Read-only file system
Could not chown /vault/config (may not have appropriate permissions)
==> Vault agent started! Log data will stream in below:
==> Vault agent configuration:
                     Cgo: disabled
               Log Level: info
                 Version: Vault v1.6.2
             Version Sha: be65a227ef2e80f8588b3b13584b5c0d9238c1d7
2021-04-28T09:31:57.700Z [INFO]  sink.file: creating file sink
2021-04-28T09:31:57.700Z [INFO]  sink.file: file sink configured: path=/vault/.vault-token mode=-rw-r-----
2021-04-28T09:31:57.700Z [INFO]  template.server: starting template server
2021/04/28 09:31:57.700578 [INFO] (runner) creating new runner (dry: false, once: false)
2021-04-28T09:31:57.791Z [INFO]  sink.server: starting sink server
2021-04-28T09:31:57.791Z [INFO]  auth.handler: starting auth handler
2021-04-28T09:31:57.791Z [INFO]  auth.handler: authenticating
2021/04/28 09:31:57.892618 [WARN] (clients) disabling vault SSL verification
2021/04/28 09:31:57.893691 [INFO] (runner) creating watcher
2021-04-28T09:31:57.953Z [INFO]  auth.handler: authentication successful, sending token to sinks
2021-04-28T09:31:57.953Z [INFO]  auth.handler: starting renewal process
2021-04-28T09:31:57.953Z [INFO]  sink.file: token written: path=/vault/.vault-token
2021-04-28T09:31:57.953Z [INFO]  template.server: template server received new token
2021/04/28 09:31:57.953512 [INFO] (runner) stopping
2021/04/28 09:31:57.953555 [INFO] (runner) creating new runner (dry: false, once: false)
2021/04/28 09:31:57.954249 [WARN] (clients) disabling vault SSL verification
2021/04/28 09:31:57.991802 [INFO] (runner) creating watcher
2021/04/28 09:31:57.992237 [INFO] (runner) starting
2021-04-28T09:31:58.009Z [INFO]  auth.handler: renewed auth token
2021/04/28 09:31:58.313388 [INFO] (runner) rendered "(dynamic)" => "/vault/secrets/my-server.crt"
````
Is it normal?
The pod seems to get stuck and never starts the alpine container echoing the cert (openssl x509 -text -noout -in /vault/secrets/my-server.crt)?
