### ISSUE TITLE
Automate the pulling of Raft leader address

### ISSUE THREAD

**Issue by mazzy89** [banzaicloud/bank-vaults#871]
**Is your feature request related to a problem? Please describe.**

Automate the process and avoid to pass as input the Raft leader address.

**Describe the solution you'd like**

Other nodes joining the cluster would pull the Raft Leader cluster before joining.

**Describe alternatives you've considered**
Having the logic of retrieving Raft leader address external to `bank-vaults`. 

**Additional context**

I've spoken already with @bonifaido and we agreed that this feature is nice to have.

The idea is to retrieve the leader address using `/sys/leader` and then store it in the unsealed KV backend.

Question: what should happen when the leader address change?

**Comment by bonifaido** [comment]
> Question: what should happen when the leader address change?

Basically I think we don't need to care about it since Vault just needs to use it once when joining only.

**Comment by mazzy89** [comment]
It makes sense. nice

**Comment by mazzy89** [comment]
@bonifaido so to be clear about the flow:

- if `raft-leader-address` flag is not passed in then retrieve the raft leader automatically

- call `/sys/leader` and get the leader address

talking about store the value. why do we want to store it? do we want to use it for later usage? can't we consume it immediately bypassing to the `RaftJoin()` function?

**Comment by bonifaido** [comment]
I think that unseal KV backend and Cloud KMS are the same here in this context.

**Comment by mazzy89** [comment]
Right because all are built as an abstraction of KV service. thank you. all clear now.

**Comment by bonifaido** [comment]
Closing this for now, as the original PR because closed as well, and the problem got resolved on the user side.
