### ISSUE TITLE
Our Labels & selectors replaced by vault-operator is breaking our Vault services

### ISSUE THREAD

**Issue by cjcos1903** [banzaicloud/bank-vaults#884]
**Describe the bug**:
If the vault-operator has restarted/redeployed, the controller itself will replace our Vault service's labels & selectors from `app: name` to `app.kubernetes.io/name: vault`. 
This breaks the Vault service (and we have three that are production)

**Expected behaviour**:
I expect the service to stay up, but instead get a 503 every time the vault-operator overwrites the labels and selectors.
We can disable the vault-operator to prevent these labels and selectors from being updated.

**Steps to reproduce the bug**:
Unable to reproduce, but I can provide our vault instance yaml, (or anything else for that matter on request)

**Additional context**:
We have been aware of this issue for about a month now. I believe the issue is that the code is not backwards compatible with the Vault setup we have running.

There could be two possibilities where to fix this in the code, but I wouldn't know where is best.

We could either add the following line `withVaultLabels(v, selectorLs)`, to the selectors value here: https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/controller/vault/vault_controller.go#L712, which would match line 708
so that we can control any additional labels/selectors that we want in the vault instance

Or for entire backwards compatibility, we could add `app: vault` into here: https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/apis/vault/v1alpha1/vault_types.go#L663

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.16.2
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS
- bank-vaults version (e.g. 0.4.17): 0.5.1
- Install method (e.g. helm or static manifests): static manifests
- Logs from the misbehaving component (and any other relevant logs): n/a
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

vault.yaml:
```
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"vault.banzaicloud.com/v1alpha1","kind":"Vault","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"vault-build"},"name":"vault","namespace":"default"},"spec":{"annotations":{"iam.amazonaws.com/role":"k8s-vault"},"bankVaultsImage":"banzaicloud/bank-vaults:0.5.1","config":{"api_addr":"https://vault.build.ifdsfs.com","default_lease_ttl":"12h","listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}},"max_lease_ttl":"720h","storage":{"dynamodb":{"ha_enabled":"true","read_capacity":5,"region":"eu-west-1","table":"vault","write_capacity":5}},"telemetry":{"statsd_address":"localhost:9125"},"ui":true},"externalConfig":{"auth":[{"type":"userpass"}],"policies":[{"name":"admin","rules":"path \"*\" {\n  capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\", \"sudo\"]\n}\n"}],"secrets":[{"description":"General secrets.","options":{"version":1},"path":"secret","type":"kv"}]},"image":"vault:1.0.1","serviceAccount":"vault","serviceType":"ClusterIP","size":1,"unsealConfig":{"kubernetes":{"secretNamespace":"default"}}}}
  creationTimestamp: "2019-10-22T11:04:08Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: vault-build
  name: vault
  namespace: default
  resourceVersion: "126215781"
  selfLink: /apis/vault.banzaicloud.com/v1alpha1/namespaces/default/vaults/vault
  uid: ab9412d3-f4bb-11e9-8e19-0ab559d736b4
spec:
  annotations:
    iam.amazonaws.com/role: k8s-vault
  bankVaultsImage: banzaicloud/bank-vaults:0.5.1
  config:
    api_addr: https://vault.example.com
    default_lease_ttl: 12h
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_disable: true
    max_lease_ttl: 720h
    storage:
      dynamodb:
        ha_enabled: "true"
        read_capacity: 5
        region: eu-west-1
        table: vault
        write_capacity: 5
    telemetry:
      statsd_address: localhost:9125
    ui: true
  credentialsConfig:
    env: ""
    path: ""
    secretName: ""
  envsConfig: null
  etcdSize: 0
  etcdVersion: ""
  externalConfig:
    auth:
    - type: userpass
    policies:
    - name: admin
      rules: |
        path "*" {
          capabilities = ["create", "read", "update", "delete", "list", "sudo"]
        }
    secrets:
    - description: General secrets.
      options:
        version: 1
      path: secret
      type: kv
  fluentdConfig: ""
  fluentdEnabled: false
  fluentdImage: ""
  image: vault:1.0.1
  nodeAffinity: {}
  nodeSelector: null
  podAntiAffinity: ""
  securityContext: {}
  serviceAccount: vault
  servicePorts: null
  serviceType: ClusterIP
  size: 1
  statsdDisabled: false
  statsdImage: ""
  tolerations: null
  unsealConfig:
    kubernetes:
      secretName: ""
      secretNamespace: default
    options: {}
  vaultAnnotations: null
  vaultConfigurerAnnotations: null
  vaultConfigurerLabels: null
  vaultConfigurerPodSpec:
    containers: null
  vaultEnvsConfig: null
  vaultPodSpec:
    containers: null
  watchedSecretsAnnotations: null
  watchedSecretsLabels: null
status:
  leader: vault-0
  nodes:
  - vault-0
```

/kind bug

**Comment by primeroz** [comment]
This is a breaking change documented in the 0.6 release notes ( if I removed correctly).

You will need a couple of manual steps to perform this with zero downtime. I recently went from 0.5.4 to 0.9.0

I can get you some commands when I get back to my desk later on today

**Comment by cjcos1903** [comment]
@primeroz thank you so much, that would be great :)

**Comment by primeroz** [comment]
@cjcos1903 

for context i was upgrading from `0.5.4` to `0.9.0` and vault from `1.2.3` to `1.3.2`, there are some changes to the probe check that will not work using vault 1.3.2 with operator 0.5.4 

Also note that since i use `flux` as gitops operator and don't push manifests directly some of steps might be different but i hope you will get an idea how to get this and test it works in your setup 

1. First patch all resources to add the new required labels
```
kubectl patch -n vault pod vault-0 -p '{"metadata":{"labels":{"app.kubernetes.io/name":"vault"}}}'
kubectl patch -n vault pod vault-1 -p '{"metadata":{"labels":{"app.kubernetes.io/name":"vault"}}}'
kubectl patch -n vault secret vault-tls -p '{"metadata":{"labels":{"app.kubernetes.io/name":"vault"}}}'
```

2. Make sure that your `vault-configurator` configmaps and secrets have the right label applied to them as well `app.kubernetes.io/name: vault-configurator` 

3. Make sure that any network policy / pod distruption policy has the right labels both for old and new labels , so both for `app` and `app.kubernetes.io/name` set to vault, i ended up having 2 of them , one with old label and one with new ones for transition period 

4. There is another change that you need to apply due to operator upgrade ( depending on which version of the operator you will run, i just assume the latest) , add `cluster_addr: https://${.Env.POD_NAME}:8201` to your vault config. This used to happen automatically before ( although in a different way )

5. delete the vault-operator deployment on the cluster  
6. Apply the new operator manifests 
7. the operator will start to error out because of trying to update immutable settings on the vault statefulset and vault-configurator but **it should not affect/break your running workload*
8. address the issues  , delete the statefulset with `cascade=false` and delete the configurator
```
kubectl delete -n vault statefulset vault --cascade=false
kubectl delete -n vault deployment vault-configurer
```

**Comment by cjcos1903** [comment]
Thank you for sharing @primeroz, I'll be scheduling this upgrade shortly. 
I'll close this issue for the meantime

**Comment by bonifaido** [comment]
Really great write-up, thank you @primeroz !
