### ISSUE TITLE
Etcd Pod Antiaffinity

### ISSUE THREAD

**Issue by dbason** [banzaicloud/bank-vaults#885]
**Describe the solution you'd like**
The ability to set nodeSelector and pod affinity rules for the vault containers is great.  It would also be nice to be able to set the same for the etcd pods automatically created

**Comment by bonifaido** [comment]
I absolutely agree, just checked the etcd-operator supports this, so if someone wants to give a stab at this we would be happy to receive a PR for that.

https://github.com/coreos/etcd-operator/blob/8347d27afa18b6c76d4a8bb85ad56a2e60927018/pkg/apis/etcd/v1beta2/cluster.go#L118

Should be added here: https://github.com/banzaicloud/bank-vaults/blob/26dada9f1c268d4abb49fd2cf3b96b1aee6468b6/operator/pkg/controller/vault/vault_controller.go#L651

**Comment by dbason** [comment]
@bonifaido can you confirm the logic in https://github.com/dbason/bank-vaults/commit/266e74de5788c7858c5079810a19951932e26439 is acceptable?  I still need to test this (will do tomorrow) and then I will open a PR.

**Comment by Born2Bake** [comment]
I wonder if it was implemented cause I could not find anything related to etcd affinity in the values of vault-operator.

**Comment by dbason** [comment]
@Born2Bake this was implemented, You can include spec.etcdAffinity in your Vault object to use it, or it will automatically use the spec.podAntiAffinity values.

I believe that the etcd stuff may have been deprecated though as the raft filesystem option build in to Vault is probably the better option.  The etcd operator was largely abandoned.

**Comment by Born2Bake** [comment]
> @Born2Bake this was implemented, You can include spec.etcdAffinity in your Vault object to use it, or it will automatically use the spec.podAntiAffinity values.
> 
> I believe that the etcd stuff may have been deprecated though as the raft filesystem option build in to Vault is probably the better option. The etcd operator was largely abandoned.

Thank you!

Raft filesystem is better option? Is it true? O_O 

I have been told that it's better to use etcd instead of any other storage options (except consul of course)? Isn't it?

**Comment by dbason** [comment]
As of Vault 1.4 I think the integrated storage is the way to go.

**Comment by bonifaido** [comment]
Yes, please use Vault Raft storage instead of etcd.
