### ISSUE TITLE
Run Vault in unprivileged SCC group

### ISSUE THREAD

**Issue by yaroslavkasatikov** [banzaicloud/bank-vaults#889]
We are unable start Vault in unprivileged group.

If we  start Vault with disable_mlock and SKIP_SETCAP=true, we will face to the necessarity of  running Vault under SCC with "allowedCapabilities: - IPC_LOCK" becaue it capability is included into securitycontext of statefulset. 
I found that it is hardcoded into code of opearotor and it will be added in any case:
https://github.com/banzaicloud/bank-vaults/blob/3908ad73b09670131f921cc580b8fe743299ecf4/operator/pkg/controller/vault/vault_controller.go#L1218-L1221

Could you please add the opportunity to create vault statesfulset without IPC_LOCK in cases if we disable it?

**Comment by aelbarkani** [comment]
I totally support this proposal. there is no reason to start Vault with IPC_LOCK if "disable_mlock: true". Vault recommend to not disable mlock unless swap is disabled:
https://www.vaultproject.io/docs/configuration/
In Openshift clusters swap is disabled by default, so we should be able to choose this option.
