### ISSUE TITLE
Make Vault-Operator chart Helm 3 compliant

### ISSUE THREAD

**Issue by sparqueur** [banzaicloud/bank-vaults#908]
**Is your feature request related to a problem? Please describe.**
We've packaged Vault integration based on BanzaiCloud. It deploys the opertor, the webhook and one Vault instance.
Therefore we use vault-operator chart as a subchart.
Problem is that there is a breaking change between Helm V2 and Helm V3.
It was previously possible to add a specific Helm annotation on the CustomResourceDefinition ("vaults.vault.banzaicloud.com") to ask Helm to create it first.
This annotation has been replaced by a CRD dedicated folder in Helm V3.
Do you have any plan the Chart Helm3 complient ?
Warning : In Helm V3 it is not possible to use go template in CRD anymore !

At least, may it be possible to make crd.yaml exclusion possible (using an "if" arround it ?)

Thank's in advance,

**Comment by bonifaido** [comment]
The chart is Helm 3 compliant, but it is not using the `crds` directory currently. A PR is incoming to resolve this, thanks for reporting!
