### ISSUE TITLE
operator.yaml missing in master

### ISSUE THREAD

**Issue by pashafirdous** [banzaicloud/bank-vaults#915]
operator.yaml missing in master as explained in https://banzaicloud.com/blog/vault-operator/
however, we can find it in 0.5.x branch.

**Comment by bonifaido** [comment]
Hi @pashafirdous, thanks for the follow-up. Yeah, we have removed the custom manifests, and offer the Helm chart as the official way to install the operator, I will update the blog post accordingly!

Cheers!
