### ISSUE TITLE
Webhook PSP manifest references old APIVersion

### ISSUE THREAD

**Issue by cten** [banzaicloud/bank-vaults#919]
**Describe the bug**:
When deploying webhooks to Kubernetes 1.16, it fails due to the API deprecations.

**Expected behaviour**:
That manifests support newer APIVersions because the older ones are being deprecated, as is the case with "extensions/v1beta1" which should is now "policy/v1beta1"

**Steps to reproduce the bug**:
Try to do a helm install of the webhook to Kubernetes cluster 1.16

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 1.16.7
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): kops/AWS
- bank-vaults version (e.g. 0.4.17): 0.9.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
`failed to upgrade chart for release [webhook]: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1"`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by pbalogh-sa** [comment]
@cten Thanks for reporting this. We will fix it.
