### ISSUE TITLE
Custom TLS certificate for vault doesn't accept kubernetes.io/tls secret type

### ISSUE THREAD

**Issue by johnny-burak** [banzaicloud/bank-vaults#926]
**Describe the bug**:
In docs in TLS section there is note when using existingTlsSecretName, that accepted secret type is kubernetes.io/tls.
https://banzaicloud.com/docs/bank-vaults/tls/#operator-custom-tls-settings
This secret type (kubernetes.io/tls) consist of two data files: tls.crt (for ca.crt and service cert) and tls.key.

When I try to use kubernetes.io/tls secret by specifying existingTlsSecretName in vault CR it doesn't work.
I founds out, that the vault-configurer pod doesn't come up because when trying to mount kubernetes.io/tls secret it still tries to mount 3 files ca.crt , tls.crt and tls.key, but ca.crt doesn't exists in tls type of secret, so it fails to mount that secret.

**Expected behaviour**:
Expected to mount secret of kubernetes.io/tls type (as described in the docs) and use tls.crt and tls.key files.

**Steps to reproduce the bug**:
- create kubernetes.io/tls type secret
- add existingTlsSecretName to vault CR definition
- create vault CR

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): 
```
  openshift v3.11.141
  kubernetes v1.11.0+d4cacc0
```
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): No, on-premise
- bank-vaults version (e.g. 0.4.17): 1.0.0
- Install method (e.g. helm or static manifests): static manifests
- Logs from the misbehaving component (and any other relevant logs): Event:
`58s  2m  8  vault-configurer-5b5b976f96-l4wlk.15fd0be247e20173   Pod   Warning   FailedMount kubelet, ocpwg01ad2.rb.cz   MountVolume.SetUp failed for volume "vault-tls" : references non-existent secret key`
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
snippet of vault CR yaml config:
`existingTlsSecretName: "vault-tls"`

secret yaml:
```
apiVersion: v1
data:
  tls.crt:
  tls.key:
kind: Secret
metadata:
  annotations:
  service.alpha.openshift.io/expiry: 2022-03-17T09:43:37Z
  service.alpha.openshift.io/originating-service-name: vault-tls
  service.alpha.openshift.io/originating-service-uid: c6a43095-6833-11ea-b06b-005056bfecde
creationTimestamp: 2020-03-17T09:43:37Z
name: vault-tls
namespace: vault-tenant
ownerReferences:
  - apiVersion: v1
    kind: Service
    name: vault-tls
    uid: c6a43095-6833-11ea-b06b-005056bfecde
resourceVersion: "37988054"
selfLink: /api/v1/namespaces/vault-tenant/secrets/vault-tls
uid: c6b944cf-6833-11ea-8a0f-005056bf76da
type: kubernetes.io/tls
```

/kind bug

**Comment by bonifaido** [comment]
The `ca.crt` has to be always present in the Secret otherwise the Bank-Vaults components can't talk with the Vault API, since this is not a publicly trusted certificate. `ca.crt` can be part of TLS type of Kubernetes Secrets as well (I know it is not standard), for example, this is how cert-manager creates the certificate Secrets. The CA has to be sourced to the client otherwise certificate-based server validation can't happen, which required by us and the [standard Vault security model as well](https://www.vaultproject.io/docs/commands/#vault_skip_verify).

**Comment by bonifaido** [comment]
I will update the docs accordingly.

**Comment by johnny-burak** [comment]
Ok, understand that.
But CA certificate can be also included in tls.crt file as in Serving service certificate which is generated by Openshift, if you annotate the service.
Also the way that aut-generated secret has names of files server.crt and server.key and custom TLS certifcate secret is expected to have names as tls.crt and tls.key is little bit confusing.
If there is space to unite this to have same names in secrets for TLS cert an key, it would be more clear.
