### ISSUE TITLE
Settings like imagePullSecret are not configurable via the vault spec

### ISSUE THREAD

**Issue by gregdurham** [banzaicloud/bank-vaults#932]
**Is your feature request related to a problem? Please describe.**
Looking at the vault spec for the CRD, it appears that there is no way to specify some settings that make it impossible to run containers that are hosted internally, i.e. there is no way in the current config to specify the `imagePullSecret` is there a known workaround, as we would like to use an internal container which has some custom plugins included and we do not want to make this container public

**Describe the solution you'd like**
Make it possible to extend the pod spec for the container

**Comment by bonifaido** [comment]
Hi @gregdurham, currently this can be easily fixed by using ServiceAccount scoped imagePullSecrets: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#service-account-admission-controller so if you add the Secret to the ServiceAccount of the Pods created by the operator this can be mitigated.

> If the pod does not contain any ImagePullSecrets, then ImagePullSecrets of the ServiceAccount are added to the pod.

Also, there are two PodSpec attributes in the CRD:
```go
    // VaultPodSpec is a Kubernetes Pod specification snippet (`spec:` block) that will be merged into the operator generated
    // Vault Pod specification.
    // default:
    VaultPodSpec v1.PodSpec `json:"vaultPodSpec"`

// ....

    // VaultConfigurerPodSpec is a Kubernetes Pod specification snippet (`spec:` block) that will be merged into
    // the operator generated Vault Configurer Pod specification.
    // default:
    VaultConfigurerPodSpec v1.PodSpec `json:"vaultConfigurerPodSpec"`
```

**Comment by gregdurham** [comment]
Oh, interesting, didn't see the podspec piece, yeah i worked around it with the serviceaccount method, was just a bit of a pain :) thank you!

**Comment by bonifaido** [comment]
I hope it helps, feel free to reopen in if it doesn't!
