### ISSUE TITLE
Being able to set resource limits on injected "copy-vault-env"

### ISSUE THREAD

**Issue by fmotrifork** [banzaicloud/bank-vaults#940]
We see that the "copy-vault-env" is CPU thorttled by kubernetes. This results in slow startup of our pods.

We see the same problem with  "vault-agent", tthis does however not result in slow startup, but in alerts in our monitoring stack.

I would like to be able to configure the resource limits for these containers. At the moment this is hard coded here:

 - https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-secrets-webhook/pod.go#L417
 - https://github.com/banzaicloud/bank-vaults/blob/master/cmd/vault-secrets-webhook/pod.go#L394

**Comment by bonifaido** [comment]
Also, we probably have to increase those defaults right @fmotrifork ? What values do you suggest here as defaults?

**Comment by fmotrifork** [comment]
Yes, that would be a good idea. Without having looked too much at the two applications resource usage, I would suggest e.g. setting cpu limit=250m and request=50m for both.

**Comment by f84anton** [comment]
https://github.com/banzaicloud/bank-vaults/blob/23ab583b97cbddc3701d05311a55fc6231f582b9/cmd/vault-secrets-webhook/pod.go#L600
"50m" for cpu limit is really low. The copy process sometimes hangs for minutes on heavy loaded hosts.

**Comment by bonifaido** [comment]
Yes, I have observed the same, we should increase it to a proper value, which can be the same as the vault resource value I think. Would you mind fixing this?

**Comment by bonifaido** [comment]
just pushed https://github.com/banzaicloud/bank-vaults/pull/1124 to address this

**Comment by f84anton** [comment]
@bonifaido thank you! I have builded own image with hotfix to mitigate the issue and just forgot about it.
