### ISSUE TITLE
[Operator] Source bootstrap secrets from sources other than environment variables

### ISSUE THREAD

**Issue by patoarvizu** [banzaicloud/bank-vaults#945]
**Is your feature request related to a problem? Please describe.**
I'm trying to bootstrap a database dynamic secrets configuration but I don't want to keep the secret in plain text in source control. Instead, I want to be able to store an encrypted string (in my case encrypted with AWS KMS but could be something else) and be able to reference it similarly to how environment variables are sourced [here](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-mysql-ha.yaml#L67).

**Describe the solution you'd like**
I can use something like `${ file "/path/to/file" }` to reference a volume mount that has the secret I injected securely, `${ awskms "SomeKMSEncryptedString" }` so I can keep the manifest in source control, including `"SomeKMSEncryptedString"`, or even maybe something like `${ keybase "username:SomeGPGEncryptedString" }`. Maybe add custom template functions in addition to the Sprig ones [here](https://github.com/banzaicloud/bank-vaults/blob/master/internal/configuration/template.go#L62)? Or maybe set additional fields in [this](https://github.com/banzaicloud/bank-vaults/blob/master/internal/configuration/template.go#L46) `env` struct that can be queried from the template using dot notation?

**Describe alternatives you've considered**
I tried generating the plain-text string in an init container, write it to a volume that is also mounted on the main `vault-configurer` container and read if from there, but the Sprig library doesn't provide access to the file system or to external binaries.

There could be potential workarounds with creating read-write configmaps, or maybe even a webhook that can modify things on the fly but I think those could add significant complexiy.

**Additional context**
Vault 1.3.2
Bank-vaults operator: 0.9.0
Tried on Kubernetes 1.17, but ideally it would also be supported at least on 1.12

**Comment by bonifaido** [comment]
Hi @patoarvizu, I really like the idea of extending the template functions even with all fo these options, namely to support cloud provider KMS/Keybase decryption functions and also file reading functions in the templates, probably this would give the required flexibility to everyone.

Are you planning to submit a PR for this feature? I would be happy to review and discuss it further!

**Comment by patoarvizu** [comment]
I wasn't necessarily planning on submitting a PR, but I'd be happy to help. I'll get back to you when I have something worth reviewing.

**Comment by bonifaido** [comment]
Great no worries, we can join forces here as well, I'm planning to help in this!

**Comment by patoarvizu** [comment]
Hey @bonifaido, I have something working locally that I've verified "manually" by running the operator with `make operator-up` against a local k3d cluster. I can push it to my fork soon and open a PR here so you can take a look, but I first wanted to ask: is there any script or `make` target I can run for automated testing? I'd like to make sure my changes pass CI/CD before I push.

**Comment by bonifaido** [comment]
Hi @patoarvizu, great stuff!

There are 3 levels of tests here :)

`make test` Runs a few unit tests.
`make test-integration` Runs a few integration tests.
`make test-sdk` Runs a few SDK module unit tests.
`make test-sdk-integration` Runs a few SDK module integration tests.

And there is a file called hack/acceptance-test.sh which runs a full test in kind/minikube, but that is enough to run when you submit a PR (it does a lot of things).
