### ISSUE TITLE
Installation on Any Kubernetes?

### ISSUE THREAD

**Issue by ashishxooa** [banzaicloud/bank-vaults#947]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
Hi guys, is this operator supported for any Kubernetes installation or it's just Banzai's Kubernetes? 

I am trying to follow https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/ and can't move ahead as one of the secrets seems to be missing. 
```

➜  bank-vaults git:(master) export VAULT_TOKEN=$(kubectl get secrets vault-unseal-keys -o jsonpath={.data.vault-root} | base64 --decode)
Error from server (NotFound): secrets "vault-unseal-keys" not found
```

**Expected behaviour**:

I should get this secret to move ahead. 

**Steps to reproduce the bug**:
Follow the exact steps from the bug. 

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.15.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS using KOPS
- bank-vaults version (e.g. 0.4.17): Not sure. Just following the blog. 
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by bonifaido** [comment]
HI @ashishxooa,

the operator runs on any kind of Kubernetes installations and has no dependencies on the Banzai Cloud Kubernetes Distribution (PKE), the CI tests (if you check them) run on Minikube and KinD for example.

Could you please check the logs of the Pods first?

**Comment by ashishxooa** [comment]
@bonifaido thanks for the clarification. 

So I did a re-installation again and still having the same issue. I found one of the pod is crashing, not sure if that was the case last time also. 

> ➜  helm-new git:(master) ✗ kubectl logs -f vault-operator-549cf4bc89-blv82
{"level":"info","ts":1586869928.524237,"logger":"cmd","msg":"Watched namespace: "}
{"level":"info","ts":1586869933.1233077,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8383"}
{"level":"info","ts":1586869933.1236484,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1586869936.637184,"logger":"cmd","msg":"Starting the Cmd."}
I0414 13:12:16.721974       1 leaderelection.go:242] attempting to acquire leader lease  vault-infra/vault-operator-lock...
{"level":"info","ts":1586869936.7224932,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I0414 13:12:34.160710       1 leaderelection.go:252] successfully acquired lease vault-infra/vault-operator-lock
{"level":"info","ts":1586869954.1610103,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"vault-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1586869954.4215934,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"vault-controller"}
{"level":"info","ts":1586869954.4218082,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"vault-controller","worker count":1}
{"level":"info","ts":1586870103.2286444,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-infra","Request.Name":"vault"}
{"level":"info","ts":1586870131.1221032,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-infra","Request.Name":"vault"}
{"level":"info","ts":1586870133.2322128,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-infra","Request.Name":"vault"}
{"level":"info","ts":1586870173.4761329,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-infra","Request.Name":"vault"}
{"level":"info","ts":1586870228.2673376,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-infra","Request.Name":"vault"}
{"level":"info","ts":1586870283.0550942,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-infra","Request.Name":"vault"}
{"level":"info","ts":1586870337.8428705,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-infra","Request.Name":"vault"}
{"level":"info","ts":1586870392.63062,"logger":"controller_vault","msg":"Reconciling Vault","Request.Namespace":"vault-infra","Request.Name":"vault"}

=============================================


> ➜  helm-new git:(master) ✗ kubectl logs -f vault-0 vault
telemetry.disable_hostname has been set to false. Recommended setting is true for Prometheus to avoid poorly named metrics.
==> Vault server configuration:

                     Cgo: disabled
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
               Log Level: debug
                   Mlock: supported: true, enabled: true
           Recovery Mode: false
                 Storage: file
                 Version: Vault v1.3.1

==> Vault server started! Log data will stream in below:

2020-04-14T13:15:34.662Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2020-04-14T13:15:34.663Z [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
2020-04-14T13:15:34.663Z [DEBUG] storage.cache: creating LRU cache: size=0
2020-04-14T13:15:34.722Z [DEBUG] cluster listener addresses synthesized: cluster_addresses=[0.0.0.0:8201]
2020-04-14T13:15:34.826Z [INFO]  core: security barrier not initialized
2020-04-14T13:15:36.419Z [INFO]  core: security barrier not initialized

======================================================================

> ➜  helm-new git:(master) ✗ kubectl logs -f vault-0 bank-vaults
time="2020-04-14T13:21:27Z" level=info msg="initializing vault..."
time="2020-04-14T13:21:27Z" level=info msg="vault metrics exporter enabled: :9091/metrics"
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :9091
time="2020-04-14T13:21:27Z" level=info msg="initializing vault"
time="2020-04-14T13:21:27Z" level=fatal msg="error initializing vault: error testing keystore before init: error getting secret for key 'vault-test': secrets \"vault-unseal-keys\" is forbidden: User \"system:serviceaccount:vault-infra:vault\" cannot get resource \"secrets\" in API group \"\" in the namespace \"default\""



Anywhere else to check? I can't see any logs for the init container config-templating. Which pod is supposed to create the secret?

**Comment by bonifaido** [comment]
There is a missing RBAC role issue here:

```bash
time="2020-04-14T13:21:27Z" level=fatal msg="error initializing vault: error testing keystore before init: error getting secret for key 'vault-test': secrets "vault-unseal-keys" is forbidden: User "system:serviceaccount:vault-infra:vault" cannot get resource "secrets" in API group "" in the namespace "default""
```

You have to apply the rbac.yaml as well first. From the blog:

> # Create a Vault instance with the operator which has the Kubernetes auth method configured
> kubectl apply -f operator/deploy/rbac.yaml
> kubectl apply -f operator/deploy/cr.yaml

**Comment by ashishxooa** [comment]
@bonifaido I did that already. 

**➜  bank-vaults git:(master) kubectl apply -f operator/deploy/rbac.yaml
serviceaccount/vault unchanged
role.rbac.authorization.k8s.io/vault-secrets unchanged
rolebinding.rbac.authorization.k8s.io/vault-secrets unchanged
clusterrolebinding.rbac.authorization.k8s.io/vault-auth-delegator unchanged**

**Comment by ashishxooa** [comment]
Oh! got it, need to have the RBAC in default namespace, I did that in the vault-infra namespace. Will check after doing it in the default ns.

**Comment by bonifaido** [comment]
Yes, the RBAC example in the repo is prepared for the `default` namespace ServiceAccount.

**Comment by ashishxooa** [comment]
@bonifaido thanks, that worked. 

Moving ahead with the demo, one of the command says "vault kv put secret/accounts/aws AWS_SECRET_ACCESS_KEY=s3cr3t", 

I was getting some error there, doubted it to be with Istio which was enabled on my default namespace. Removed Istio from default and it worked. So is there any compatibility issue with Istio? as Istio is a must for my workload. 

`➜  bank-vaults git:(master) ✗ vault kv put secret/accounts/aws AWS_SECRET_ACCESS_KEY=s3cr3t
Get https://127.0.0.1:8200/v1/sys/internal/ui/mounts/secret/accounts/aws: EOF`

On the proxy also, I could see some error. 

```
Handling connection for 8200
E0414 19:54:27.712763   10911 portforward.go:400] an error occurred forwarding 8200 -> 8200: error forwarding port 8200 to pod 1fe23c493be9edf756619fddf5af03eb86e4d33f91d43ae60b05f49eb368b0d9, uid : exit status 1: 2020/04/14 14:24:28 socat[28660] E connect(5, AF=2 127.0.0.1:8200, 16): Connection refused
```

**Comment by bonifaido** [comment]
Istio is supported, but you have to enable the support first, see: https://github.com/banzaicloud/bank-vaults/blob/2481a75e3767e2cf3e4cf5e948692ce83b9f44ca/operator/deploy/cr.yaml#L195

**Comment by bonifaido** [comment]
Closing this, since the original issue has been answered.

**Comment by abdennour** [comment]
this issue happen to me when I delete/redeploy everything, except the namespace.
After investigation, I found that `vault-unseal-keys` secret has not been deleted when I deleted vault-operator, vault-cluster,... etc. 

So to fix the issue, I just delete the secret manually: 
```sh
k -n vault delete secret vault-unseal-keys
```
