### ISSUE TITLE
CLI usage shouldn't result in infinite loops

### ISSUE THREAD

**Issue by jacohend** [banzaicloud/bank-vaults#95]
**Describe the bug**

There's an infinite retry loop in unseal. This makes sense for the operator, but when used from a CLI should retry once (or configurable n times) and then return an appropriate exit code upon failure, as CLI tools do.

**To Reproduce**
1. Run an unseal command from a terminal without specifying VAULT_ADDR
2. The resulting command will not return, but will continue to check on the bad address indefinitely. 

**Expected behavior**
When called from bash by a user (instead of by operator), the binary should never loop indefinitely.

**Comment by bonifaido** [comment]
Hi @jacohend, I totally agree that there are certain use cases when a user would like to unseal Vault without a loop, however, we have never faced it, so we haven't implemented this feature. For preserving backward compatibility I propose to add an option to specify the number of loops with `--loops=5` or a `--once` flag, but by default, it should loop. How does it sound?

**Comment by matyix** [comment]
Any preference @jacohend? This is a rather small/quick fix just wanted to know your feedback. We lean towards the `--once` flag.

**Comment by bonifaido** [comment]
https://github.com/banzaicloud/bank-vaults/pull/101 has been opened to fix this.

**Comment by bonifaido** [comment]
Fixed and released: https://github.com/banzaicloud/bank-vaults/releases/tag/0.2.7
