### ISSUE TITLE
[QUESTION] Broken hook after full velero restore ?

### ISSUE THREAD

**Issue by sparqueur** [banzaicloud/bank-vaults#950]
We are using velero in order to backup/restore our cluster.
The operator, the webhook and the vault instance are deployed in the same namespace.
A third party app, using vault secret is in a second namespace.

We perform a backup of both namespaces.
I then delete both namespaces and perform a restoration.
Bank vault seems to be up and running.

Unfortunalty the webhooks does not seem to apply anymore => My third party app does not load the secrets (even when deploying a new pod).

I have to perform a helm upgrade in order to make everything work again.

Did you ever try this use case ?

**Comment by bonifaido** [comment]
Hi @sparqueur,

the Velero integration has been tested only with the operator and vault instances, so not with the webhook. This can be an ordering issue as well (the webhook gets deployed back after your application pods). Are you backing up the Pods as well, or just the deployment itself?

**Comment by sparqueur** [comment]
Hi,

It is not release a restore order. Even when I first restore vault namespace, the webhook is broken.

Strange behavior : It only when I delete the vault namespace ! If i delete all objects inside the namespace but keep it and then restore the content, everything works fine.

Really strange :'( . It might be a kubernetes behavior

**Comment by sparqueur** [comment]
I fixed my problem. It was an incomplete velero backup/restore configuration.
In order to make it work I had to set "includeClusterResources" to "true" in backup / restore objects as I was specifying "includedNamespaces"

**Comment by bonifaido** [comment]
I'm glad @sparqueur that it works now, I would check the example backup manifest we suggest: https://github.com/banzaicloud/bank-vaults-docs/blob/5a4d1110d2228e6eefdc1af034ce444a89ddaa2a/docs/backup/backup.yaml
