### ISSUE TITLE
[vault-secrets-webhook] Container fails to start after CA certificate in Kubernetes secret renewed

### ISSUE THREAD

**Issue by cablespaghetti** [banzaicloud/bank-vaults#960]
**Describe the bug**:
So my environment uses the vault-secrets-webhook and a certificate (self signed by cert-manager) mounted from a secret. Helm chart setup:
```
certificate:
  useCertManager: true
  generate: false
```

Annotations on my container:
```
  vault.security.banzaicloud.io/vault-addr: "https://vault:8200"
  vault.security.banzaicloud.io/vault-tls-secret: "vault-server-tls"
```

Today my certificate got renewed by cert-manager and now if one of my pods crashes and is restarted I get an error like this:
```
OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/f60f1274-34e3-4c86-8c5d-317e1818b17b/volume-subpaths/vault-tls/cms-api/2\\\" to rootfs \\\"/var/lib/docker/overlay2/d76402adf3a76689023c7de2fdb06fd75b26f9017b002575043b7fb82202d703/merged\\\" at \\\"/var/lib/docker/overlay2/d76402adf3a76689023c7de2fdb06fd75b26f9017b002575043b7fb82202d703/merged/vault/tls/ca.crt\\\" caused \\\"no such file or directory\\\"\"": unknown
```

Deleting the pod and letting the Deployment recreate it fixes the issue. The secret shows as 60 days old and has all the expected files.

**Expected behaviour**:
Certificate gets renewed, secret is updated with the new certificate files, containers continue to work as expected.

**Steps to reproduce the bug**:
Run a container using a vault-secrets-webhook injected secret (environment variable) and have the vault CA certificate stored in a secret. Renew this 

**Additional context**:

**Environment details**:
- Kubernetes version: v1.15.10
- Cloud-provider/provisioner: EKS:
- bank-vaults version (e.g. 0.4.17): banzaicloud/vault-secrets-webhook:0.9.0
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): See above
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: Hopefully shared enough above.

/kind bug

**Comment by bonifaido** [comment]
I guess this could be related to that we are mounting only a subPath (ca.crt) from the secret and Kubernetes has various issues with that. Let me look into this, I will try to reproduce it.

**Comment by bonifaido** [comment]
I guess this could be related to that we are mounting only a subPath (ca.crt) from the secret and Kubernetes has various issues with that. Let me look into this, I will try to reproduce it.

**Comment by cablespaghetti** [comment]
Thanks. To be honest I've disabled cert verification in my environments to get around this for the moment and haven't had a chance to do further debugging. I'll read up on potential bugs around subPath.

**Comment by bonifaido** [comment]
I just found the most possibly related issue for this: https://github.com/kubernetes/kubernetes/issues/68211

So this is not a Bank-Vaults but a Kubernetes upstream issue.

**Comment by cablespaghetti** [comment]
That's true but as this bug has been around for so long and doesn't look very close to being fixed, is it possible to try and work around it in Bank Vaults?

**Comment by bonifaido** [comment]
Yes, I was thinking about that, what kind of fields does this secret have? Only `ca.crt`?

**Comment by cablespaghetti** [comment]
`ca.crt`, `tls.crt`, `tls.key`

I think that's standard with cert-manager.

**Comment by bonifaido** [comment]
Currently, the only "workaround" I can imagine is not using `subPath` at all here, but then all the certificate and key material would end up in an application pod, which is also bad here.

**Comment by cablespaghetti** [comment]
Agreed that's not ideal at all. Just seeing if cert-manager supports a secret with just the cert but it doesn't look like that's possible: https://cert-manager.io/docs/usage/certificate/

**Comment by bonifaido** [comment]
This sounds like a possible workaround (using projected keys): https://github.com/kubernetes/kubernetes/issues/68211#issuecomment-467032048

**Comment by cablespaghetti** [comment]
Great. I'm very short on time at the moment but I'll try and find time to test that solution and get cert-manager to rotate the certificate in the next few days.

**Comment by bonifaido** [comment]
I think we can pull in that fix shortly of projected volumes.

**Comment by bonifaido** [comment]
@cablespaghetti if you could test that the issue disappears with the linked PR here ☝️ that would be great!

**Comment by cablespaghetti** [comment]
Great. Will do!

**Comment by bonifaido** [comment]
TBH seems to be working fine locally.

**Comment by cablespaghetti** [comment]
@bonifaido Is there a binary or even better a docker container I can run, or do I need to build it all locally?

**Comment by bonifaido** [comment]
This landed in master, please pull the latest master image from the webhook. When you test it please make sure that the application pod mounts the vault CA Secret from a projected volume instead directly from the Secret.

**Comment by cablespaghetti** [comment]
```
  - name: vault-tls
    projected:
      defaultMode: 420
      sources:
      - secret:
          items:
          - key: ca.crt
            path: ca.crt
          name: vault-server-tls
```

Good start. Now I'll try and reproduce the bug by setting a very short expiry on the cert.

**Comment by cablespaghetti** [comment]
Confirmed fixed in my environment :+1: Thanks!

**Comment by bonifaido** [comment]
Welcome, this would probably bite us as well, we just haven't experienced it by accident.

**Comment by nitinmohan87** [comment]
Cool! Hope this also fixes the issue that I was facing with pod restarts - https://community-banzaicloud.slack.com/archives/CFJJW9L94/p1583441404091100
