### ISSUE TITLE
Mutate Configmap in place 

### ISSUE THREAD

**Issue by avaussant** [banzaicloud/bank-vaults#965]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:

**Expected behaviour**:
I m trying bank-vaults and follow each example available on the code base.
I have tried to deploy this cr: operator/deploy/cr.yaml with this cm deploy/test-configmap.yaml
But i don't know why, the webhook server doesn't react and the value is not mutated.

$ k get configmap/sample-configmap -oyaml | ksd
apiVersion: v1
binaryData:
  aws-access-key-id-binary: dmF1bHQ6c2VjcmV0L2RhdGEvYWNjb3VudHMvYXdzI0FXU19BQ0NFU1NfS0VZX0lE
kind: ConfigMap
metadata:
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
    vault.security.banzaicloud.io/vault-addr: https://vault.default.svc.cluster.local:8200
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/vault-role: default
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  creationTimestamp: "2020-05-06T14:34:36Z"
  name: sample-configmap
  namespace: default
  resourceVersion: "18015"
  selfLink: /api/v1/namespaces/default/configmaps/sample-configmap
  uid: b5a4c102-8fa6-11ea-ad46-0ec55573adb5
stringData:
  aws-access-key-id: vault:secret/data/accounts/aws#AWS_ACCESS_KEY_ID
  aws-access-key-id-formatted: 'vault:secret/data/accounts/aws#AWS key in base64:
    ${.AWS_ACCESS_KEY_ID | b64enc}'   

**Steps to reproduce the bug**:
git clone https://github.com/banzaicloud/bank-vaults.git
cd bank-vaults
kubectl config set-context --current --namespace=default
kubectl apply -f operator/deploy/cr.yaml
kubectl apply -f deploy/test-configmap.yaml

**Additional context**:
helm charts used ;
- banzaicloud-stable/vault-operator latest
- banzaicloud-stable/vault-secrets-webhook latest

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.14.9
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- bank-vaults version (e.g. 0.4.17):
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): no logs - no events
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: operator/deploy/cr.yaml

/kind bug

**Comment by bonifaido** [comment]
Please install the webhook with enabled failure policy and enabled mutation for ConfigMaps, check the helm chart for more details.

**Comment by avaussant** [comment]
Great it ' s working, sorry  for the inconvenience

**Comment by bonifaido** [comment]
No problem.
