### ISSUE TITLE
[vault-secrets-webhook] Webhook should support major clouds container registries (ACR, etc...)

### ISSUE THREAD

**Issue by amit-o** [banzaicloud/bank-vaults#966]
Right now, the webhook only supports ECR's authentication out of the box.
It should probably support GCR and ACR, as well.

**Comment by leominov** [comment]
Look's like a part of my closed pull request #654 :D

**Comment by bonifaido** [comment]
Still happy to merge it, if it up-to-date! :)

**Comment by bonifaido** [comment]
GCR got implemented already.

**Comment by sebader** [comment]
are there any news around this for ACR (Azure Container Registry)? We are using an AKS cluster and have "AcrPull" permissions assigned to the kubelet identity which works fine for image pulling but it does not look like the webhook takes that into account

**Comment by bonifaido** [comment]
Hi @sebader we have migrated the registry code to [go-containerregistry](https://github.com/vdemeester/k8s-pkg-credentialprovider/tree/v1.21.0/azure) already, which should support ACR as well. If not that is a bug, please provide some logs from the webhook and some environment issues (versions used) on a new Github issue.

**Comment by bonifaido** [comment]
Originally fixed by: https://github.com/banzaicloud/bank-vaults/pull/1236

**Comment by sebader** [comment]
thanks @bonifaido! Looking [at the code](https://github.com/vdemeester/k8s-pkg-credentialprovider/blob/74c721a3e6ab7a5eea42230cdb92412b8df78537/azure/azure_credentials.go#L254), there seems to be some reference to MSI (which is what we are looking for). I just don't see any docs on how to configure this. Do you have any pointers to a sample config/docs? thanks!

**Comment by bonifaido** [comment]
Unfortunately no, I don't have, since this library is not really well documented. From go-containerregistry there is no way to programatically configure it that is for sure.

Can you enable some logging in the webhook? This file [https://github.com/vdemeester/k8s-pkg-credentialprovider/blob/master/azure/azure_credentials.go#L254] seems to have some useful log messages.

**Comment by bonifaido** [comment]
A snippet from the docs of go-containerregistry:
>>> k8schain

>>> This is an implementation of the github.com/google/go-containerregistry library's authn.Keychain interface based on the authentication semantics used by the Kubelet when performing the pull of a Pod's images.

**Comment by bonifaido** [comment]
I think this is the same issue: https://github.com/banzaicloud/bank-vaults/issues/927#issuecomment-878857469
