### ISSUE TITLE
[vswh:chart] objectSelector

### ISSUE THREAD

**Issue by tony-kerz** [banzaicloud/bank-vaults#967]
**Is your feature request related to a problem? Please describe.**

`objectSelector` value is not documented

**Describe the solution you'd like**

document `objectSelector` [here](https://github.com/banzaicloud/bank-vaults/tree/master/charts/vault-secrets-webhook#configuration)

**Describe alternatives you've considered**

**Additional context**

i came across it via the [values.yaml](https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/values.yaml#L106) file, and it implies that you can use it in k8s versions `1.15+`,
and shows an example of what you might want to use it for:
```
objectSelector: {}
  # matchExpressions:
  # - key: security.banzaicloud.io/mutate
  #   operator: NotIn
  #   values:
  #   - skip
```
but the suggestion is actually already being added [here](https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/templates/apiservice-webhook.yaml#L184-L195) (with a clever technique using awareness of k8s version that i have never seen before 😃)

so maybe just describe what the value does, and what the default effect is in k8s `1.15+`?

from what i can gather, it is being used to omit things from being mutated, but does this mean that i don't need to isolate the webhook in it's own namespace with that `name` label discussed [here](https://github.com/banzaicloud/bank-vaults/tree/master/charts/vault-secrets-webhook#installing-the-chart)?

**Comment by pbalogh-sa** [comment]
@tony-kerz  Thanks for reporting the missing documentation. We will update it soon.
With `objectSelector` you can include or exclude objects from mutation based on labels. In that case, when you exclude the webhook pod,  you don't have to isolate the whole namepesce containing it.

**Comment by pbalogh-sa** [comment]
By default in case of K8s 1.15 and above, the deployment already contains the label which prevent the mutation:
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/templates/webhook-deployment.yaml#L26
The related part of the webhook config:
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/templates/apiservice-webhook.yaml#L83-L86
