### ISSUE TITLE
Unable to update vault config

### ISSUE THREAD

**Issue by blazed** [banzaicloud/bank-vaults#99]
**Describe the bug**
When we make changes to `spec.config` in the crd, the deployment doesn't get updated. 

**To Reproduce**
Download https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/cr.yaml
Run `kubectl create -f cr.yaml`
Change `ui: true` to `ui: false`
Run `kubectl apply -f cr.yaml`

Do a describe on the deployment and see that `VAULT_LOCAL_CONFIG` haven't change.
If you do a describe on the vault crd you can see that it has changed.

**Expected behavior**
That the deployment gets updated so kubernetes can do a rolling-update

**Comment by matyix** [comment]
Thx @blazed for reporting this. We pushed a fix, let us know how it works for you.

**Comment by bonifaido** [comment]
The fix is in the latest image, tagged with `master`.

**Comment by blazed** [comment]
@matyix works as expected now, thanks!
