### ISSUE TITLE
[vault-secrets-webhook] Helm install failing when `vault-skip-verify` specified 

### ISSUE THREAD

**Issue by gw0** [banzaicloud/bank-vaults#990]
**Describe the bug**:
I attempted to follow [this MySQL example](https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/#mysql-example), but in a different setup. Because of an invalid TLS certificate, I wanted to set `VAULT_SKIP_VERIFY=true` and with [these official docs](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/#podspec-secret-configmap-and-crd-annotations) I came up with the following Helm command. Unfortunately, it failed with a weird error:

```bash
$ helm upgrade --install tmp-mysql stable/mysql \
>   --set mysqlRootPassword=vault:kv/data/mysql#MYSQL_ROOT_PASSWORD \
>   --set mysqlPassword=vault:kv/data/mysql#MYSQL_PASSWORD \
>   --set "podAnnotations.vault\.security\.banzaicloud\.io/vault-addr"=https://vault.example.invalid \
>   --set "podAnnotations.vault\.security\.banzaicloud\.io/vault-skip-verify"="true" \
>   --set "podAnnotations.vault\.security\.banzaicloud\.io/vault-role"=tmp-mysql \
>   --wait
Release "tmp-mysql" does not exist. Installing it now.
Error: release tmp-mysql failed: Deployment in version "v1" cannot be handled as
a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template:
v1.PodTemplateSpec.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects "
or n, but found t, error found in #10 byte of ...|-verify":true},"labe|...,
bigger context
...|vault.security.banzaicloud.io/vault-skip-verify":true},"labels":{"app":"tmp-mysql","release":"|...
```

I attempted different variations of `--set "podAnnotations.vault\.security\.banzaicloud\.io/vault-skip-verify"="true"`, but as the error says it only accepts `"` or `n`. But then `vault-env` complains because it is an invalid value.

If I set this parameter in a `values.yaml`, it works.

**Expected behaviour**:
The Helm parameter `--set "podAnnotations.vault\.security\.banzaicloud\.io/vault-skip-verify"="true"` should work like other string parameters. Using `--set` should work the same as if it was specified in a `values.yaml`.

**Steps to reproduce the bug**:
See above.

**Additional context**:
Please verify if it works in the official setup of Bank-Vaults with Helm v2 and v3. If it does, feel free to close this issue.

**Environment details**:
Helm 2.14.1, Vault 1.4.1, vault-secrets-webhook 1.2.0. Custom setup of Vault.

/kind bug

**Comment by bonifaido** [comment]
Hi @gw0,

the issue is here with the `"true"` literal in the annotation, that needs to be a `string` since annotations are handled as `map[string]string` in Kubernetes code. So you have to escape the `"` like in the following example:


```bash
helm upgrade --install tmp-mysql stable/mysql \ 
   --set mysqlRootPassword=vault:kv/data/mysql#MYSQL_ROOT_PASSWORD \
   --set mysqlPassword=vault:kv/data/mysql#MYSQL_PASSWORD \
   --set "podAnnotations.vault\.security\.banzaicloud\.io/vault-addr"=https://vault.example.invalid \
   --set "podAnnotations.vault\.security\.banzaicloud\.io/vault-skip-verify"=\"true\" \
   --set "podAnnotations.vault\.security\.banzaicloud\.io/vault-role"=tmp-mysql
```

See: https://github.com/helm/helm/issues/2848

**Comment by bonifaido** [comment]
I hope it helps! If not, please feel free to reopen.
