### ISSUE TITLE
[vault] ClusterRoleBinding name conflict in Helm chart

### ISSUE THREAD

**Issue by cablespaghetti** [banzaicloud/bank-vaults#991]
**Is your feature request related to a problem? Please describe.**
In Helm 3, releases are namespaced so we can deploy many releases with the same name in our dev environments. Unfortunately the ClusterRoleBinding is a cluster-wide resource and is linked to the release name, which means I can only deploy one "vault" release per cluster.

**Describe the solution you'd like**
I've fixed this by forking the chart and prefixing the ClusterRoleBinding with the `.Release.Namespace`, but any unique prefix would work for me.

**Describe alternatives you've considered**
I could use different release names but I want to have vault accessible as https://vault:8200 in each namespace.

**Comment by bonifaido** [comment]
If you have a fork, would you mind submitting a PR for this?

**Comment by cablespaghetti** [comment]
Hi. Yes I will do today if you think the solution is ok. Thanks
