### ISSUE TITLE
Comment for external vault config example is broken

### ISSUE THREAD

**Issue by jmgilman** [banzaicloud/bank-vaults#992]
> Bugs should be filed for issues encountered whilst operating bank-vaults.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors.
> Please provide as much detail as possible.

**Describe the bug**:
This link is littered throughout the deployment examples and is supposed to link to an example of how to use the external configuration feature: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration. It appears whatever this used to point to is no longer there. [Here is an example](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr.yaml#L119).

**Expected behaviour**:
The link points to an example of using the external configuration feature.

**Steps to reproduce the bug**:
N/A

**Additional context**:
I did a little digging but was unable to come up with a comprehensive example showing what details can be configured. For example, how would I configure Github auth backend? 

**Environment details**:
N/A

/kind bug

**Comment by bonifaido** [comment]
Sorry for the broken link, please check https://github.com/banzaicloud/bank-vaults/blob/master/vault-config.yml#L35 in the meantime.

**Comment by jmgilman** [comment]
Excellent, thank you!
