### ISSUE TITLE
OCP 4.3: runAsUser in Vault Secrets webhook chart should be configurable

### ISSUE THREAD

**Issue by dakine1111** [banzaicloud/bank-vaults#994]
**Is your feature request related to a problem? Please describe.**
When using the vault secrets webhook chart in OCP 4.3.x for security reasons the runAsUser must be in the range between 1000570000 and 1000579999 and not 65534.

**Describe the solution you'd like**
The secrets webhook chart should be deployable in openshift.
With something like this:

```bash
--- a/charts/vault-secrets-webhook/templates/webhook-deployment.yaml
+++ b/charts/vault-secrets-webhook/templates/webhook-deployment.yaml
@@ -77,7 +77,9 @@ spec:
 {{ toYaml .Values.volumeMounts | indent 12 }}
 {{- end }}
           securityContext:
-            runAsUser: 65534
+            {{- if .Values.securityContext.runAsUser }}
+            runAsUser: {{ .Values.securityContext.runAsUser }}
+            {{- end }}
             allowPrivilegeEscalation: false
           resources:
 {{ toYaml .Values.resources | indent 12 }}
diff --git a/charts/vault-secrets-webhook/values.yaml b/charts/vault-secrets-webhook/values.yaml
index a4f442d..9cf51f0 100644
--- a/charts/vault-secrets-webhook/values.yaml
+++ b/charts/vault-secrets-webhook/values.yaml
@@ -46,6 +46,9 @@ metrics:
     tlsConfig:
       insecureSkipVerify: true
 
+securityContext:
+  runAsUser: 65534
+
 volumes: []
 # - name: vault-tls
 #   secret:
```
I was able to deploy the chart in OCP 4.3 with:
`helm upgrade --namespace vswh --install vswh banzaicloud-stable/vault-secrets-webhook --set-string securityContext.runAsUser="" --wait`
It would be great to have the ability to use a different runAsUser in the helm chart.

**Comment by bonifaido** [comment]
Please feel free to send a PR for the chart. (it looks to me that you have the right solution already) I'm happy to merge it!
